homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret lon_home
  elevation: !secret elev
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  packages: !include_dir_named conf/packages/
  allowlist_external_dirs:
  - /config/.other
  external_url: !secret base_url
amcrest: !include conf/amcrest.yaml
automation: !include_dir_merge_list conf/automations/
binary_sensor: !include conf/binary_sensor.yaml
camera: !include conf_pkg/camera.yaml
climate: !include conf_pkg/climate.yaml
config:
discovery: !include conf_settings/discovery.yaml
fan: !include conf_pkg/fan.yaml
frontend: !include conf_settings/frontend.yaml
google: !include conf_static/calendar.yaml
google_assistant: !include conf_static/google_assistant.yaml
group: !include conf/groups.yaml
history: !include conf_settings/history.yaml
http: !include conf_settings/http.yaml
input_boolean: !include conf/helpers/input_boolean.yaml
input_datetime: !include conf/helpers/input_datetime.yaml
input_number: !include conf/helpers/input_number.yaml
input_select: !include conf/helpers/input_select.yaml
input_text: !include conf/helpers/input_text.yaml
light: !include conf/light.yaml
logbook: !include conf_settings/logbook.yaml
logger: !include conf_settings/logger.yaml
media_source:
mobile_app:
mqtt: !include conf_static/mqtt.yaml
notify: !include conf/notify.yaml
panel_custom: !include conf_settings/panel_custom.yaml
recorder: !include conf_settings/recorder.yaml
rest_command: !include conf/rest_command.yaml
scene: !include conf/scenes.yaml
script: !include conf/scripts.yaml
sensor: !include_dir_merge_list conf/sensors/
shell_command: !include conf/shell_command.yaml
ssdp:
stream:
sun:
switch: !include conf/switch.yaml
system_health:
timer: !include conf_pkg/timer.yaml
tts: !include conf/tts.yaml
wake_on_lan:
weather: !include conf/weather.yaml
zeroconf:
zone: !include conf/zone.yaml
