automation: !include_dir_merge_list conf/automations/
binary_sensor:
bluetooth:
climate:
config:
counter:
discovery:
fan:
frontend: !include conf_settings/frontend.yaml
google_assistant: !include conf/google_assistant.yaml
group: !include conf/groups.yaml
history: !include conf_settings/history.yaml
homeassistant: !include conf_settings/home-assistant.yaml
http: !include conf_settings/http.yaml
input_boolean:
input_datetime:
input_number:
input_select:
input_text:
light:
logbook: !include conf_settings/logbook.yaml
logger: !include conf_settings/logger.yaml
media_source:
mobile_app:
mqtt: !include conf/mqtt.yaml
notify: !include conf/notify.yaml
panel_custom: !include conf_settings/panel_custom.yaml
recorder: !include conf_settings/recorder.yaml
scene: !include conf/scenes.yaml
script:
sensor: !include conf/sensors.yaml
shell_command: !include conf/shell_command.yaml
ssdp:
stream:
sun:
switch:
system_health:
timer:
tts: !include conf/tts.yaml
wake_on_lan:
zeroconf:
zone: !include conf/zone.yaml