homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret lon_home
  elevation: !secret elev
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  packages: !include_dir_named conf/packages/
  whitelist_external_dirs:
  - /config
apcupsd:
automation: !include_dir_merge_list conf/automations/
binary_sensor: !include conf/binary_sensor.yaml
climate: !include conf/.climate.yaml
cloudflare: !include conf/.cloudflare.yaml
config:
discovery: !include settings/discovery.yaml
frontend: !include settings/frontend.yaml
google: !include conf/.calendar.yaml
google_assistant: !include conf/google.yaml
group: !include settings/groups.yaml
hacs: !include conf/.hacs.yaml
history: !include settings/history.yaml
http: !include settings/http.yaml
hue: !include conf/.hue.yaml
input_boolean: !include conf/input_boolean.yaml
input_datetime: !include conf/input_datetime.yaml
input_number: !include conf/input_number.yaml
input_select: !include conf/input_select.yaml
input_text: !include conf/input_text.yaml
light: !include conf/light.yaml
logbook:
logger: !include settings/logger.yaml
mobile_app:
notify: !include conf/.notify.yaml
recorder: !include settings/recorder.yaml
scene: !include conf/.scenes.yaml
script: !include_dir_merge_named conf/scripts/
sensor: !include_dir_merge_list conf/sensors/
ssdp:
sun:
switch: !include conf/switch.yaml
system_health:
telegram_bot: !include conf/.telegram.yaml
timer: !include conf/timer.yaml
tplink: !include conf/tplink.yaml
tts: !include conf/.tts.yaml
updater: !include settings/updater.yaml
vizio: !include conf/vizio.yaml
zeroconf:
zha: !include conf/.zha.yaml
zone: !include settings/zone.yaml
zwave: !include conf/.zwave.yaml