apcupsd:
automation: !include_dir_merge_list conf/automations/
binary_sensor: !include conf/binary_sensor.yaml
climate: !include conf/climate.yaml
config:
discovery:
fan: !include conf/fan.yaml
frontend: !include conf_settings/frontend.yaml
google: !include conf_static/calendar.yaml
google_assistant: !include conf_static/google_assistant.yaml
group: !include conf/groups.yaml
history: !include conf_settings/history.yaml
homeassistant: !include conf/main.yaml
http: !include conf_settings/http.yaml
input_boolean: !include conf/helpers/input_boolean.yaml
input_datetime: !include conf/helpers/input_datetime.yaml
input_number: !include conf/helpers/input_number.yaml
input_select: !include conf/helpers/input_select.yaml
input_text: !include conf/helpers/input_text.yaml
light: !include conf/light.yaml
logbook: !include conf_settings/logbook.yaml
logger: !include conf_settings/logger.yaml
media_source:
mobile_app:
notify: !include conf/notify.yaml
panel_custom: !include conf_settings/panel_custom.yaml
recorder: !include conf_settings/recorder.yaml
rest_command: !include conf/rest_command.yaml
scene: !include conf/scenes.yaml
script: !include conf/scripts.yaml
sensor: !include_dir_merge_list conf/sensors/
shell_command: !include conf/shell_command.yaml
ssdp:
stream:
sun:
switch: !include conf/switch.yaml
system_health:
timer: !include conf/timer.yaml
tts: !include conf/tts.yaml
wake_on_lan:
zeroconf:
zone: !include conf/zone.yaml