homeassistant:
  name: Home
  latitude: !secret lat_home
  longitude: !secret lon_home
  elevation: !secret elev
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  auth_providers:
  - type: homeassistant
  packages: !include_dir_named packages/
  whitelist_external_dirs:
  - /config
apcupsd:
automation: !include_dir_merge_list config/automations/
binary_sensor: !include config/binary_sensor.yaml
climate: !include config/.climate.yaml
cloudflare: !include config/.cloudflare.yaml
config:
discovery:
frontend: !include config/.frontend.yaml
google: !include config/.calendar.yaml
google_assistant: !include config/google.yaml
group: !include config/groups.yaml
hacs: !include config/.hacs.yaml
history: !include config/history.yaml
hpprinter: !include config/.printer.yaml
http: !include config/.http.yaml
input_boolean: !include config/flippy_bois.yaml
input_number: !include config/input_number.yaml
input_text: !include config/input_text.yaml
light: !include config/light.yaml
logbook:
logger: !include config/logger.yaml
mobile_app:
notify: !include config/.notify.yaml
recorder: !include config/recorder.yaml
scene: !include config/.scenes.yaml
script: !include_dir_merge_named config/scripts/
sensor: !include_dir_merge_list config/sensors/
ssdp:
sun:
switch: !include config/switch.yaml
system_health:
telegram_bot: !include config/.telegram.yaml
tplink: !include config/tplink.yaml
tts: !include config/.tts.yaml
updater: !include config/.updater.yaml
vizio: !include config/vizio.yaml
zeroconf:
zha: !include config/.zha.yaml
zone: !include config/zone.yaml
zwave: !include config/.zwave.yaml