gr_lights_on:
  alias: Game room lights on
  sequence:
  - service: hue.hue_activate_scene
    data:
      group_name: Game room
      scene_name: Read

gr_lights_off:
  alias: Game room lights off
  sequence:
  - service: light.turn_off
    entity_id: light.game_room
    data:
      transition: 60

none:
  alias: Dummy script
  sequence:
  - service: switch.turn_off
    entity_id: switch.not_an_actual_switch