gr_lights_on:
  alias: Game room lights on
  sequence:
  - service: light.turn_on
    entity_id: light.game_room
    data:
      kelvin: 3000
      transition: 5
      brightness_pct: 100

gr_lights_off:
  alias: Game room lights off
  sequence:
  - service: light.turn_off
    entity_id: light.game_room
    data:
      transition: 30

none:
  alias: Dummy script
  sequence:
  - service: switch.turn_off
    entity_id: switch.not_an_actual_switch