xbox_on:
  sequence:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - service: switch.turn_on
    entity_id: switch.plug_3
  - service: media_player.turn_off
    entity_id:
    - media_player.all_speakers
    - media_player.portable_speaker
  - service: script.gr_lights_on
  - condition: state
    entity_id: climate.thermostat
    state: 'heat'
  - service: climate.turn_on
    entity_id: climate.space_heater

xbox_off:
  sequence:
  - service: homeassistant.turn_off
    entity_id: 
    - switch.plug_3
    - climate.space_heater
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'on'
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: state
    entity_id: sensor.living_room_tv
    state: 'off'
  - service: scene.turn_on
    entity_id: scene.before_gaming

gr_lights_on:
  alias: Game room lights on
  sequence:
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'on'
  - service: light.turn_on
    entity_id: light.game_room
    data:
      kelvin: 3000
      transition: 5
      brightness_pct: 100

gr_lights_off:
  alias: Game room lights off
  sequence:
  - service: light.turn_off
    entity_id: light.game_room
    data:
      transition: 30

dummy:
  alias: Dummy script
  sequence:
  - service: homeassistant.turn_off
    entity_id: none