good_morning:
  alias: Good morning
  sequence:
  - service: light.turn_on
    entity_id: light.master_bedroom
    data:
      brightness_pct: 1
      kelvin: 3000
  - delay: '00:00:30'
  - service: light.turn_on
    entity_id: light.master_bedroom
    data:
      kelvin: 3000
      transition: 30
      brightness_pct: 100
  - condition: state
    entity_id: input_boolean.christmas_mode
    state: 'on'
  - service: switch.turn_on
    entity_id: switch.tuya_plug2