good_night:
  alias: Good night routine
  sequence:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.abode
  - service: homeassistant.turn_off
    entity_id: group.lights_interior
  - service: switch.turn_off
    entity_id: switch.bedroom_tv
  - service: media_player.volume_mute
    entity_id: media_player.bedroom_speaker
    data:
      is_volume_muted: yes
  - service: media_player.play_media
    entity_id: media_player.bedroom_speaker
    data:
      media_content_id: "http://10.0.0.2:8123/local/audio/pink_noise.mp3"
      media_content_type: audio/mp3
  - delay: '00:00:01'
  - service: media_player.volume_mute
    entity_id: media_player.bedroom_speaker
    data:
      is_volume_muted: no
  - service: media_player.volume_set
    entity_id: media_player.bedroom_speaker
    data:
      volume_level: 0.65
  - service: switch.turn_off
    entity_id: switch.tuya_plug2
  - service: switch.turn_off
    entity_id: switch.plug2
  - service: switch.turn_on
    entity_id: switch.plug1


good_night_no_noise:
  alias: Good night routine - no white noise
  sequence:
  - service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.abode
  - service: homeassistant.turn_off
    entity_id: group.lights_interior
  - service: switch.turn_off
    entity_id: switch.tuya_plug2
  - service: switch.turn_off
    entity_id: 
    - switch.plug2
    - switch.bedroom_tv
  - service: switch.turn_on
    entity_id: switch.plug1


white_noise_bedroom:
  alias: Play white noise on bedroom speaker
  sequence:
  - service: media_player.volume_mute
    entity_id: media_player.bedroom_speaker
    data:
      is_volume_muted: yes
  - service: media_player.play_media
    entity_id: media_player.bedroom_speaker
    data:
      media_content_id: "http://10.0.0.2:8123/local/audio/pink_noise.mp3"
      media_content_type: audio/mp3
  - delay: '00:00:01'
  - service: media_player.volume_mute
    entity_id: media_player.bedroom_speaker
    data:
      is_volume_muted: no
  - service: media_player.volume_set
    entity_id: media_player.bedroom_speaker
    data:
      volume_level: 0.65
