pre_media:
  alias: Pre-media
  sequence:
  - service: light.turn_off
    entity_id: light.living_room
    data:
      transition: 3
  - service: switch.turn_off
    entity_id: switch.tuya_plug_2
  - service: hue.hue_activate_scene
    data:
      group_name: Dining room
      scene_name: Media

post_media:
  alias: Post-media
  sequence:
  - service: light.turn_on
    entity_id: light.living_room_lamps
    data:
      kelvin: 3000
      transition: 5
      brightness_pct: 100
  - service: light.turn_on
    entity_id: light.dining_room
    data:
      kelvin: 3000
      transition: 5
      brightness_pct: 100
  # - service: switch.turn_on
  #   entity_id: switch.tuya_plug_2