reload_input_boolean:
  alias: Input boolean
  sequence:
  - service: input_boolean.reload
  - service: flippy_boi.reload

reload_input_number:
  alias: Input number
  sequence:
  - service: input_number.reload

reload_input_text:
  alias: Input text
  sequence:
  - service: input_text.reload