tv_vol_up:
  alias: Increase TV volume by 5
  sequence:
  - service: script.turn_on
    entity_id: script.soundbar_vol_up
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_up
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_up
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_up
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_up


tv_vol_dn:
  alias: Decrease TV volume by 5
  sequence:
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn


tv_vol_up_heat:
  alias: Increase TV volume by 3
  sequence:
  - service: script.turn_on
    entity_id: script.soundbar_vol_up
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_up
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_up


tv_vol_dn_heat:
  alias: Decrease TV volume by 3
  sequence:
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn
  - delay:
      milliseconds: 300
  - service: script.turn_on
    entity_id: script.soundbar_vol_dn