automation:
- alias: Thermostat resume schedule
  id: 'Xo9chon6esieF5Wai1chie'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
  - platform: state
    entity_id: 
    - input_boolean.tstat_sched_resume
    - input_boolean.tstat_hold
    from: 'on'
    to: 'off'
  action:
  - service: button.press
    entity_id: button.thermostat_clear_hold


- alias: Thermostat away
  id: 'ohy9quaeph1eikohxieCei'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    to: 'armed_away'
    for: '00:30:00'
  - platform: state
    entity_id: input_text.alarm
    to: 'armed_away'
    for: '00:30:30'
  condition:
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  action:
  - service: select.select_option
    entity_id: select.thermostat_current_mode
    data:
      option: 'away'
  - service: input_boolean.turn_off
    entity_id: input_boolean.tstat_smart


- alias: Resume tstat schedule if hold flag not set
  id: 'Eishufe7uach4eimaiquik'
  initial_state: true
  trigger:
  - platform: time
    at:
    - '06:15:00'
    - '21:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  - not:
      condition: state
      entity_id: sensor.tstat_profile
      state: 'Away'
  action:
  - service: button.press
    entity_id: button.thermostat_clear_hold