### Cooling
automation:
- alias: Thermostat home - cool
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.sensor_tripped
    - input_boolean.tstat_sched_resume
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_number.cool_home
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret cool_home_work
  - platform: time
    at: !secret cool_home_weekend
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: 'cool'
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  - condition: template
    value_template: "{{ not is_state('sensor.tstat_profile', 'Home') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: or
    conditions:
    - condition: time
      after: !secret cool_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      after: !secret cool_home_weekend
      weekday: ['sat', 'sun']
  - condition: or
    conditions:
    - condition: time
      before: !secret cool_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      before: !secret cool_sleep_weekend
      weekday: ['fri', 'sat']
  action:
  - service: script.cool_home
  - service: input_boolean.turn_off
    entity_id: input_boolean.tstat_smart


- alias: Thermostat sleep - cool
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.sensor_tripped
    - input_boolean.tstat_sched_resume
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_number.cool_sleep
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret cool_sleep_work
  - platform: time
    at: !secret cool_sleep_weekend
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: 'cool'
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  - condition: template
    value_template: "{{ not is_state('sensor.tstat_profile', 'Sleep') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: or
    conditions:
    - condition: time
      after: !secret cool_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      after: !secret cool_sleep_weekend
      weekday: ['fri', 'sat']
    - condition: time
      before: !secret cool_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      before: !secret cool_home_weekend
      weekday: ['sat', 'sun']
  action:
  - service: script.cool_sleep
  - service: input_boolean.turn_off
    entity_id: input_boolean.tstat_smart


### Heating
- alias: Thermostat home - heat
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.sensor_tripped
    - input_boolean.tstat_sched_resume
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_number.heat_home
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret heat_home_work
  - platform: time
    at: !secret heat_home_weekend
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: 'heat'
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  - condition: template
    value_template: "{{ not is_state('sensor.tstat_profile', 'Home') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: or
    conditions:
    - condition: time
      after: !secret heat_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      after: !secret heat_home_weekend
      weekday: ['sat', 'sun']
  - condition: or
    conditions:
    - condition: time
      before: !secret heat_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      before: !secret heat_sleep_weekend
      weekday: ['fri', 'sat']
  action:
  - service: script.heat_home
  - service: input_boolean.turn_off
    entity_id: input_boolean.tstat_smart


- alias: Thermostat sleep - heat
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.sensor_tripped
    - input_boolean.tstat_sched_resume
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_number.heat_sleep
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret heat_sleep_work
  - platform: time
    at: !secret heat_sleep_weekend
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: 'heat'
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  - condition: template
    value_template: "{{ not is_state('sensor.tstat_profile', 'Sleep') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: or
    conditions:
    - condition: time
      after: !secret heat_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      after: !secret heat_sleep_weekend
      weekday: ['fri', 'sat']
    - condition: time
      before: !secret heat_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      before: !secret heat_home_weekend
      weekday: ['sat', 'sun']
  action:
  - service: script.heat_sleep
  - service: input_boolean.turn_off
    entity_id: input_boolean.tstat_smart


### Away
- alias: Thermostat away
  initial_state: true
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    to: 'armed_away'
  - platform: state
    entity_id: alarm_control_panel.abode
    to: 'armed_away'
    for: '00:00:30'
  condition:
  - condition: template
    value_template: "{{ states('climate.thermostat') in ['cool', 'heat'] and not is_state('sensor.tstat_profile', 'Away') }}"
  action:
  - service_template: "script.{{ states('climate.thermostat') }}_away"
  - service: input_boolean.turn_off
    entity_id: 
    - input_boolean.tstat_hold
    - input_boolean.tstat_smart