automation:
- alias: Turn thermostat off if window opened
  id: 'eeCu9yoothielah9Xeiroe'
  initial_state: true
  trigger:
  - platform: state
    entity_id: &windows group.windows
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: *windows
    from: 'on'
    to: 'off'
    for: '00:01:00'
  action:
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'on' }}"
      - condition: state
        entity_id: &window_bool input_boolean.tstat_window_off
        state: 'off'
      sequence:
      - service: climate.turn_off
        entity_id: climate.thermostat
      - service: input_boolean.turn_on
        entity_id: *window_bool
    default:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.thermostat
        hvac_mode: "{{ states('input_text.tstat_prev_mode') }}"
    - wait_template: "{{ states('climate.thermostat') == states('input_text.tstat_prev_mode') }}"
    - service: button.press
      entity_id: button.thermostat_clear_hold
    - service: input_boolean.turn_off
      entity_id: *window_bool


- alias: Record previous thermostat mode
  id: 'OhLoe1Ge6oGo0aiPhoJoo2'
  initial_state: true
  trigger:
  - platform: state
    entity_id: climate.thermostat
    from:
    - 'heat'
    - 'cool'
    to: 'off'
  action:
  - service: input_text.set_value
    entity_id: input_text.tstat_prev_mode
    data_template:
      value: "{{ trigger.from_state.state }}"


- alias: Resume tstat schedule - set mode
  id: 'Iro8kaedahchux6oki9pee'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.tstat_sched_resume
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_boolean.tstat_peak_savings
    from: 'on'
    to: 'off'
  action:
  - service: climate.set_temperature
    entity_id: climate.thermostat
    data:
      temperature: "{{ 65 if is_state('input_text.tstat_prev_mode', 'heat') else 80 }}"
      hvac_mode: "{{ states('input_text.tstat_prev_mode') }}"
  - wait_template: "{{ states('climate.thermostat') == states('input_text.tstat_prev_mode') }}"
  - service: button.press
    entity_id: button.thermostat_clear_hold
  - service: input_boolean.turn_off
    entity_id: input_boolean.tstat_sched_resume


- alias: Start home mode earlier when cold in master bedroom
  id: 'iu9ahs1Aigoophien7xei4'
  initial_state: true
  trigger:
  - platform: time_pattern
    minutes: '/10'
  condition:
  - condition: time
    after: '04:49:00'
    before: '06:00:00'
  - condition: state
    entity_id: climate.thermostat
    state: 'heat'
  - "{{ states('input_text.alarm') in ['armed_home', 'disarmed'] }}"
  - condition: or
    conditions:
    - "{{ states('sensor.tstat_current_temp') | float < 62 and now().hour < 5 and now().minute < 51 }}"
    - "{{ states('sensor.tstat_current_temp') | float < 63 and now().hour < 6 and now().minute < 11 }}"
    - "{{ states('sensor.tstat_current_temp') | float < 64 and now().hour < 6 and now().minute < 31 }}"
    - "{{ states('sensor.tstat_current_temp') | float < 65 and now().hour < 6 and now().minute < 51 }}"
  action:
  - service: climate.set_temperature
    entity_id: climate.thermostat
    data:
      temperature: 70


script:
  tstat_smart_resume_cool:
    sequence:
    - condition: state
      entity_id: input_boolean.tstat_peak_savings
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.tstat_current_temp
      above: 77.9
    - condition: numeric_state
      entity_id: sensor.outside_temp
      above: 74.9
    - service: input_text.set_value
      entity_id: input_text.tstat_prev_mode
      data:
        value: 'cool'
    - service: input_boolean.turn_on
      entity_id: input_boolean.tstat_sched_resume


input_boolean:
  tstat_window_off: