automation:
- alias: Turn basement stairs light on/off with door
  id: 'ixegoogee0ohSh4deekeer'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'on'
    to: 'off'
    for: '00:00:30'
  action:
  - service: "light.turn_{{ trigger.to_state.state }}"
    entity_id: light.basement_stairs


- alias: Turn basement stairs bottom light on/off with basement stairs
  id: 'Afie9Daez7dohfooDoovai'
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.basement_stairs
    to:
    - 'on'
    - 'off'
  condition:
  - "{{ not is_state('light.basement_stairs_bottom', trigger.to_state.state) }}"
  action:
  - service: "light.turn_{{ trigger.to_state.state }}"
    entity_id: light.basement_stairs_bottom


- alias: Turn basement bathroom night light on
  id: 'aiyahfah9aexah8Zoh6oad'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.dark_inside
    - group.basement_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
  condition:
  - condition: state
    entity_id: 
    - group.basement_lights
    - input_boolean.dark_inside
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.basement_bath_night_light


- alias: Turn basement bathroom night light off
  id: 'aa4xooBuy2iexaulah0Iuf'
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - group.basement_lights
    - input_boolean.dark_inside
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id:
    - light.basement_bath_night_light
    - light.basement_hallway


- alias: Sync basement color lights
  id: 'ooxaa2sae3ei0yeboo0Dai'
  initial_state: true
  trigger:
  - platform: state
    entity_id: &basement_color_lights
    - light.bar_lights
    - light.basement_fireplace_lights
  condition:
  - condition: state
    entity_id: input_boolean.sync_basement_color_lights
    state: 'on'
  action:
  - delay: 1
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'off' }}"
      sequence:
      - service: light.turn_off
        entity_id: *basement_color_lights
    default:
    - service: light.turn_on
      entity_id: *basement_color_lights
      data:
        brightness: "{{ state_attr(trigger.to_state.entity_id, 'brightness') }}"
        rgb_color: "{{ state_attr(trigger.to_state.entity_id, 'rgb_color') }}"
  - delay: 2


mqtt:
  light:
  - name: Basement stairs
    state_topic: "stat/basement_stairs/POWER1"
    command_topic: "cmnd/basement_stairs/EVENT"
    availability_topic: "tele/basement_stairs/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"


light:
- platform: group
  name: Basement stairs lights
  entities:
  - light.basement_stairs
  - light.basement_stairs_bottom

- platform: group
  name: Basement fireplace lights
  entities:
  - light.basement_fireplace_left
  - light.basement_fireplace_right

- platform: group
  name: Basement lamps
  entities:
  - light.basement_lamp_left
  - light.basement_lamp_right

- platform: group
  name: Bar lights
  entities:
  - light.bar_front
  - light.bar_side

group:
  basement_lights:
    name: Basement lights
    entities:
    - light.bar_lights
    - light.basement
    - light.basement_lamps
    - light.basement_stairs_lights
    - light.craft_room
    - light.craft_room_lamps
    - light.guest_bedroom
    - light.right_lamp_basement


input_boolean:
  sync_basement_color_lights: