automation:
- alias: Notify when garage door opened/closed
  id: 'notify-garage-open-closed'
  initial_state: true
  mode: 'parallel'
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
  action:
  - service: notify.gotify_high
    data:
      message: >
        {% set state = trigger.to_state.state %}
        {% set states = {
          'on': 'opened',
          'off': 'closed',
          'unavailable': 'unavailable'
        } %}
        Garage door {{ states[state] }}