automation:
- alias: Dim down/up cabinet lights with kitchen lights
  id: 'theit5ait1MieDi3Geixee'
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.kitchen
    to:
    - 'on'
    - 'off'
  action:
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'on' }}"
      - condition: state
        entity_id: light.cabinet_lights_dimmer
        state: 'on'
      - "{{ state_attr('light.cabinet_lights_dimmer', 'brightness') | int(0) < 254 }}"
      sequence:
      - service: scene.create
        data:
          scene_id: kitchen_cabinets
          snapshot_entities:
          - light.cabinet_lights_dimmer
      - service: light.turn_on
        entity_id: light.cabinet_lights_dimmer
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_cabinet_light_ctl
    - conditions:
      - "{{ trigger.to_state.state == 'off' }}"
      - condition: state
        entity_id: input_boolean.kitchen_cabinet_light_ctl
        state: 'on'
      sequence:
      - scene: scene.kitchen_cabinets
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_cabinet_light_ctl


- alias: Record coffeemaker on/off
  id: 'gai4IeyaewaxuyeeWipei2'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: &coffeemaker sensor.coffeemaker_power
    above: 1000
  - platform: numeric_state
    entity_id: *coffeemaker
    below: 10
    for: '00:00:10'
  action:
  - service_template: "input_boolean.turn_{{ 'on' if trigger.to_state.state | float(0) > 500 else 'off' }}"
    data:
      entity_id: "input_boolean.{{ 'basement_' if 'basement' in trigger.to_state.entity_id else '' }}coffeemaker"


- alias: Notify when coffee done
  id: 'ul9ein6Faicheim9Chahku'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.coffeemaker
    from: 'on'
    to: 'off'
  action:
  - service: notify.gotify
    data:
      title: "Coffee is ready"
      message: "Enjoy!"


mqtt:
  light:
  - name: Kitchen
    state_topic: "stat/kitchen_lights/POWER1"
    command_topic: "cmnd/kitchen_lights/EVENT"
    availability_topic: "tele/kitchen_lights/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"


input_boolean:
  kitchen_cabinet_light_ctl:
  coffeemaker: