automation:
- alias: Record coffeemaker on/off
  id: 'gai4IeyaewaxuyeeWipei2'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: &coffeemaker sensor.coffeemaker_power
    above: 700
  - platform: numeric_state
    entity_id: *coffeemaker
    below: 10
    for: '00:01:30'
  action:
  - service: "input_boolean.turn_{{ 'on' if trigger.to_state.state | float(0) > 500 else 'off' }}"
    entity_id: input_boolean.coffeemaker


- alias: Notify when coffee done
  id: 'ul9ein6Faicheim9Chahku'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.coffeemaker
    from: 'on'
    to: 'off'
  action:
  - service: notify.gotify
    data:
      title: "Coffee is ready"
      message: "Enjoy!"


- alias: Turn cabinet lights on/off with switch
  id: 'cabinet-lights-on-off-w-switch'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.cabinet_light_switch
    to:
    - 'enter'
    - 'leave'
  action:
  - service: "light.turn_{{ 'on' if trigger.to_state.state == 'enter' else 'off' }}"
    entity_id: light.cabinet_lights


light:
- platform: group
  name: Cabinet lights
  entities:
  - light.cabinet_lights_n
  - light.cabinet_lights_microwave


# mqtt:
#   light:
#   - name: Kitchen
#     state_topic: "stat/kitchen_lights/POWER1"
#     command_topic: "cmnd/kitchen_lights/EVENT"
#     availability_topic: "tele/kitchen_lights/LWT"
#     payload_on: "ON"
#     payload_off: "OFF"
#     payload_available: "Online"
#     payload_not_available: "Offline"


input_boolean:
  coffeemaker: