automation:
- alias: Turn bedroom lights off in morning on workday
  id: 'saoNg0IeZahlaiRuu4lahl'
  initial_state: true
  trigger:
  - platform: time
    at: '07:45:00'
  condition:
  - condition: state
    entity_id: light.main_bedroom_lamps
    state: 'on'
  - condition: or
    conditions:
    - condition: template
      value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') == as_timestamp(state_attr('calendar.andy_work', 'start_time')) | timestamp_custom('%d') }}"
    - condition: template
      value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') }}"
  - condition: template
    value_template: "{{ states('input_text.alarm') in ['armed_home', 'armed_night', 'disarmed'] }}"
  action:
  - service: light.turn_off
    entity_id: light.main_bedroom_lamps
    data:
      transition: 60


- alias: Adjust main floor chime volume
  id: 'adjust-main-floor-chime-volume'
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep
    to: 'on'
  - platform: state
    entity_id: input_boolean.sleep_mode
    to: 'off'
  action:
  - service: media_player.volume_set
    entity_id: media_player.main_floor_chime
    data:
      volume_level: "{{ 0.2 if trigger.to_state.state == 'on' else 0.4 }}"


light:
- platform: group
  name: Main bedroom lamps
  entities:
  - light.andy
  - light.matt


# switch:
# - platform: template
#   switches:
#     bedroom_fan:
#       friendly_name: Bedroom fan
#       value_template: "{{ is_state('switch.main_bedroom_fan', 'on') }}"
#       turn_on:
#       - service: switch.turn_on
#         entity_id: switch.main_bedroom_fan
#       - delay: 1
#       - service: mqtt.publish
#         data:
#           topic: 'cmnd/main_bedroom_fan/tuyasend4'
#           payload: '3,3' # max speed
#       turn_off:
#         service: switch.turn_off
#         entity_id: switch.main_bedroom_fan