automation:
- alias: Toggle dark inside boolean
  id: 'ainei8ohpetaa2cheLeilu'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sun.sun
    to:
    - 'below_horizon'
    - 'above_horizon'
    for: &horizon_time '00:20:00'
  action:
  - service: "homeassistant.turn_{{ 'on' if trigger.to_state.state == 'below_horizon' else 'off' }}" 
    entity_id: input_boolean.dark_inside


- alias: Turn on sunset lights - light level
  id: 'ieb7uceicaejai0eiLaoza'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: &outdoor_light sensor.outdoor_light_level
    below: &outdoor_light_threshold 80
    for: &light_threshold_time '00:05:00'
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
  condition:
  - condition: time
    after: '14:00:00'
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'off'
  - condition: state
    entity_id: input_text.alarm
    state:
    - 'disarmed'
    - 'armed_home'
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: *outdoor_light
      below: *outdoor_light_threshold
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
      for: *horizon_time
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.dark_inside


- alias: Turn lights back off if light level goes back up
  id: 'eeXus7ugei6eirieGhivoh'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: *outdoor_light
    above: *outdoor_light_threshold
    for: '00:10:00'
  condition:
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  - condition: state
    entity_id: input_text.alarm
    state:
    - 'disarmed'
    - 'armed_home'
  action:
  - service: script.turn_on
    entity_id: script.lights_sunrise


- alias: Dim cabinet and buffet lights at night
  id: 'faShei9wi9de8ia4aquoag'
  initial_state: true
  trigger:
  - platform: time
    at: &time '23:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: input_boolean.overnight_guest
    state: 'off'
  - condition: or
    conditions:
    - condition: state
      entity_id: light.kitchen_cabinets
      state: 'on'
    - condition: state
      entity_id: light.buffet
      state: 'on'
    - condition: state
      entity_id: light.hallway
      state: 'on'
    - condition: state
      entity_id: light.entrance
      state: 'on'
  - condition: time
    after: *time
  action:
  - wait_template: "{{ is_state('media_player.living_room_vizio', 'off') }}"
    timeout: '00:30:00'
    continue_on_timeout: false
  - service: light.turn_on
    entity_id:
    - light.kitchen_cabinets
    - light.hallway
    - light.entrance
    - light.other_buffet
    data:
      brightness_pct: 66
      transition: 10
      kelvin: 2700
  - condition: template
    value_template: "{{ state_attr('light.buffet', 'brightness') | int(0) > 170 }}"
  - service: light.turn_on
    entity_id: light.buffet
    data:
      brightness_pct: 66
      transition: 10
      kelvin: 2700


- alias: Turn lights on/off at sunset/sunrise
  id: 'eifait7ohwo4haeW9oozah'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.dark_inside
    to:
    - 'on'
    - 'off'
  action:
  - service: script.turn_on
    data:
      entity_id: >
        script.{%- set alarm = states('alarm_control_panel.home') -%}
        {%- if trigger.to_state.state == 'on' -%}
          {%- if alarm == 'armed_away' -%}
            lights_kitty
          {%- else -%}
            lights_sunset
          {%- endif -%}
        {%- else -%}
          lights_sunrise
        {%- endif -%}


- alias: Sync Tasmota device states on restart
  id: 'Neruw7Phaew0iuquai4eQu'
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/state
      payload: ''


script:
  lights_sunset:
    sequence:
    - service: script.turn_on
      entity_id: 
      - script.christmas_lights_on
    - service: light.turn_on
      entity_id: light.cabinet_lights_dimmer
      data:
        brightness_pct: 100
        transition: 10
    - service: light.turn_on
      entity_id: light.entrance
      data:
        brightness_pct: "{{ 25 if is_state('media_player.living_room_vizio', 'on') else 100 }}"
        kelvin: 2700
        transition: 10
    - service: light.turn_on
      entity_id:
      - light.hall_light_dimmer
      - light.buffet
      data:
        brightness_pct: "{{ 50 if is_state('media_player.living_room_vizio', 'on') else 100 }}"
        kelvin: 2700
        transition: 10
    - service: light.turn_on
      entity_id: 
      - light.hall_bath_night_light
      - light.master_bath_night_light
      data:
        brightness_pct: 100
    - service: script.turn_on
      entity_id: script.lr_lights_sunset
    - condition: state
      entity_id: media_player.living_room_vizio
      state: 'off'
    - service: light.turn_on
      entity_id: light.other_buffet
      data:
        brightness_pct: 100
        kelvin: 2700
        transition: 10

  lr_lights_sunset:
    sequence:
    - choose:
      - conditions:
        - condition: state
          entity_id: media_player.living_room_vizio
          state: 'on'
        sequence:
        - service: light.turn_on
          entity_id: light.living_room_bias_lighting
          data:
            brightness_pct: 100
            kelvin: 5000
            transition: 10
      default:
      - wait_template: "{{ states('sensor.outdoor_light_level') | int(0) < 10 }}"
        timeout: "00:30:00"
        continue_on_timeout: true
      - condition: template
        value_template: "{{ states('input_text.alarm') in ['armed_home', 'disarmed'] }}"
      - condition: state
        entity_id: media_player.living_room_vizio
        state: 'off'
      - service: light.turn_on
        data:
          entity_id: light.living_room_lamps
          brightness_pct: 100
          kelvin: 2700
          transition: 10
  
  lights_sunrise:
    sequence:
    - service: input_boolean.turn_off
      entity_id: input_boolean.dark_inside
    - service: light.turn_off
      entity_id: 
      - light.buffet
      - light.other_buffet
      - light.entrance
      - light.hall_light_dimmer
      - light.cabinet_lights_dimmer
      data:
        transition: 10
    - delay: '00:00:10'
    - service: light.turn_off
      entity_id: 
      - light.hall_bath_night_light
      - light.master_bath_night_light
      data:
        transition: 1
    - service: script.turn_on
      entity_id: script.christmas_lights_off

  christmas_tree_on:
    sequence:
    - condition: state
      entity_id: input_boolean.christmas
      state: 'on'
    - service: light.turn_on
      entity_id: 
      - light.christmas_tree
      - light.star_lights
    - wait_template: "{{ is_state('light.dining_room', 'off') }}"
      timeout: '08:00:00'
      continue_on_timeout: false
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - service: light.turn_on
      entity_id: light.portable_mini_christmas_tree

  christmas_lights_on:
    sequence:
    - condition: state
      entity_id: input_boolean.christmas
      state: 'on'
    - service: light.turn_on
      entity_id: 
      - light.christmas_lights
    - wait_template: "{{ is_state('media_player.living_room_vizio', 'off') or is_state('input_boolean.lr_tv_ir', 'on') }}"
      timeout: '08:00:00'
      continue_on_timeout: false
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - service: light.turn_on
      entity_id:
      - light.christmas_tree
      - light.portable_mini_christmas_tree
      - light.star_lights

  christmas_lights_off:
    sequence:
    - condition: state
      entity_id: input_boolean.christmas
      state: 'on'
    - service: homeassistant.turn_off
      entity_id: group.lights_christmas

  brightness_preset:
    sequence:
    - service: mqtt.publish
      data:
        topic: "cmnd/{{ device }}/dimmer"
        payload: "{{ brightness_pct }}"

  main_floor_lights_off:
    sequence:
    - service: scene.create
      data:
        scene_id: main_floor_lights
        snapshot_entities: &main_floor_lights
        # - light.buffet
        # - light.entrance
        # - light.hallway
        - light.hall_bath_night_light
        - light.kitchen_cabinets
        - light.living_room_lamps
        - light.master_bath_night_light
        - light.other_buffet
    - service: light.turn_off
      entity_id: *main_floor_lights
    - service: input_boolean.turn_on
      entity_id: input_boolean.main_floor_lights_off


group:
  lights_christmas:
    name: Christmas lights
    entities:
    - light.christmas_lights
    - light.christmas_tree
    - light.mini_christmas_tree
    - light.portable_mini_christmas_tree
    - light.star_lights


input_boolean:
  dark_inside:
  overnight_guest:
  main_floor_lights_off:
