automation:
- alias: Turn bedroom lights off in morning on workday
  initial_state: true
  trigger:
  - platform: time
    at: '07:45:00'
  condition:
  - condition: state
    entity_id: light.master_bedroom_lamps
    state: 'on'
  - condition: or
    conditions:
    - condition: template
      value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') == as_timestamp(state_attr('calendar.andy_work', 'start_time')) | timestamp_custom('%d') }}"
    - condition: template
      value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') }}"
  - condition: template
    value_template: "{{ states('input_text.alarm') in ['armed_home', 'disarmed'] }}"
  action:
  - service: light.turn_off
    entity_id: light.master_bedroom_lamps
    data:
      transition: 60


# - alias: Turn master bedroom closet light on/off with motion
#   initial_state: true
#   trigger:
#   - platform: state
#     entity_id: binary_sensor.master_bedroom_closet_motion # 30 second cooldown
#     to: 
#     - 'on'
#     - 'off'
#   condition:
#   - "{{ trigger.to_state.state != states('light.master_bedroom_closet') }}"
#   - condition: state
#     entity_id:
#     - input_boolean.sleep_mode
#     - input_boolean.andy_sleep
#     state: 'off'
#   action:
#   - service: light.turn_on
#     entity_id: light.master_bedroom_closet
#     data:
#       brightness_pct: >
#         {% if trigger.to_state.state == 'on' %}
#           {% if is_state('light.master_bedroom_lamps', 'off') and is_state('input_boolean.dark_inside', 'on') %}
#             50
#           {% else %}
#             {{ 100 if 6 < now().hour < 21 else 50 }}
#           {% endif %}
#         {% else %}
#           0
#         {% endif %}


- alias: Transition master bedroom lights to warm
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.dark_inside
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.matt
    state: 'on'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Master bedroom lamps
      scene_name: Read
      transition: 200


- alias: Turn mini Christmas tree on
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_motion
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  - "{{ now().month in [11, 12, 1, 2] }}"
  action:
  - service: light.turn_on
    entity_id: light.mini_christmas_tree


- alias: Turn mini Christmas tree off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_motion
    to: 'off'
    for: '00:05:00'
  - platform: state
    entity_id: light.matt
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: light.matt
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.mini_christmas_tree


- alias: Turn generic tstats on with buttons on plugs
  initial_state: true
  trigger:
  - platform: mqtt
    topic: stat/master_bedroom_ac/power
    id: bedroom_ac
  - platform: mqtt
    topic: stat/box_fan/power
    id: box_fan
  action:
  - service: "climate.turn_{{ 'on' if is_state('climate.' + trigger.id, 'off') else 'off' }}"
    data:
      entity_id: "climate.{{ trigger.id }}"


- alias: Turn closet lights on/off with doors
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.andy_closet_door
    - binary_sensor.matt_closet_door
    to:
    - 'on'
    - 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: "light.{{ trigger.to_state.object_id.replace('_door','') }}"
      brightness_pct: "{{ 67 if (trigger.to_state.state == 'on' and is_state('input_boolean.dark_inside', 'on')) else 0 }}"


switch:
- platform: template
  switches:
    bedroom_fan:
      friendly_name: Bedroom fan
      value_template: "{{ is_state('switch.master_bedroom_fan', 'on') }}"
      turn_on:
      - service: switch.turn_on
        entity_id: switch.master_bedroom_fan
      - delay: 1
      - service: mqtt.publish
        data:
          topic: 'cmnd/master_bedroom_fan/tuyasend4'
          payload: '3,3' # max speed
      turn_off:
        service: switch.turn_off
        entity_id: switch.master_bedroom_fan


climate:
- platform: generic_thermostat
  name: Bedroom AC 
  heater: switch.bedroom_ac
  ac_mode: true
  target_sensor: &bedroom_temp sensor.master_bedroom_temp
  min_temp: 66
  max_temp: 75
  cold_tolerance: 0
  hot_tolerance: 2
  precision: 0.1
  min_cycle_duration: '00:05:00'

- platform: generic_thermostat
  name: Box fan
  heater: switch.box_fan
  ac_mode: true
  target_sensor: *bedroom_temp
  min_temp: 64
  max_temp: 75
  cold_tolerance: 0
  hot_tolerance: 2
  precision: 0.5


input_number:
  bedroom_ac_temp_matt:
    name: Matt sleep
    min: 65
    max: 75
    step: 1
    mode: box

  bedroom_ac_temp_andy:
    name: Andy sleep
    min: 65
    max: 75
    step: 1
    mode: box