##############################
##### Cooling
##############################
automation:
- alias: Thermostat home - cool
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.cool_home
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret cool_home_work
  - platform: time
    at: !secret cool_home_weekend
  condition:
  - condition: or
    conditions:
    - condition: time
      after: !secret cool_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      after: !secret cool_home_weekend
      weekday: ['sat', 'sun']
  - condition: or
    conditions:
    - condition: time
      before: !secret cool_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      before: !secret cool_sleep_weekend
      weekday: ['fri', 'sat']
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  action:
  - service: script.cool_home


- alias: Thermostat sleep - cool
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.cool_sleep
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret cool_sleep_work
  - platform: time
    at: !secret cool_sleep_weekend
  condition:
  - condition: or
    conditions:
    - condition: time
      after: !secret cool_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      after: !secret cool_sleep_weekend
      weekday: ['fri', 'sat']
    - condition: time
      before: !secret cool_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      before: !secret cool_home_weekend
      weekday: ['sat', 'sun']
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  action:
  - service: script.cool_sleep


##############################
##### Heating
##############################

- alias: Thermostat home - heat
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.heat_home
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret heat_home_work
  - platform: time
    at: !secret heat_home_weekend
  condition:
  - condition: or
    conditions:
    - condition: time
      after: !secret heat_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      after: !secret heat_home_weekend
      weekday: ['sat', 'sun']
  - condition: or
    conditions:
    - condition: time
      before: !secret heat_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      before: !secret heat_sleep_weekend
      weekday: ['fri', 'sat']
  - condition: state
    entity_id: climate.thermostat
    state: heat
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  action:
  - service: script.heat_home


- alias: Thermostat sleep - heat
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.heat_sleep
  - platform: homeassistant
    event: start
  - platform: time
    at: !secret heat_sleep_work
  - platform: time
    at: !secret heat_sleep_weekend
  condition:
  - condition: or
    conditions:
    - condition: time
      after: !secret heat_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      after: !secret heat_sleep_weekend
      weekday: ['fri', 'sat']
    - condition: time
      before: !secret heat_home_work
      weekday: ['mon', 'tue', 'wed', 'thu', 'fri']
    - condition: time
      before: !secret heat_home_weekend
      weekday: ['sat', 'sun']
  - condition: state
    entity_id: climate.thermostat
    state: heat
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  action:
  - service: script.heat_sleep


##############################
##### Special
##############################

- alias: Start sleep mode early if running
  initial_state: 'on'
  trigger:
  - platform: time
    at: '20:45:00'
  - platform: time
    at: '21:15:00'
  condition:
  - condition: or
    conditions:
    - condition: time
      after: '20:45:00'
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      after: '21:15:00'
      weekday: ['fri', 'sat']
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: template
    value_template: "{{ is_state_attr('climate.thermostat', 'hvac_action', 'cooling') and states('sensor.tstat_comfort_setting') != 'Sleep' }}"
  action:
  - service: script.cool_sleep


- alias: Start home schedule earlier - sound check
  initial_state: 'on'
  trigger:
  - platform: time
    at: '06:40:00'
  condition:
  - condition: template
    value_template: "{{ state_attr('calendar.church', 'message') != None and 'sound check' in state_attr('calendar.church', 'message').lower() }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: template
    value_template: "{{ states('climate.thermostat') in ['cool', 'heat'] }}"
  - condition: time
    weekday: sun
  action:
  - service_template: "{{ 'script.cool_home' if is_state('climate.thermostat', 'cool') else 'script.heat_home' }}"


- alias: Thermostat away
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    to: armed_away
  - platform: state
    entity_id: alarm_control_panel.abode
    to: armed_away
    for: '00:00:30'
  condition:
  - condition: template
    value_template: "{{ states('climate.thermostat') in ['cool', 'heat'] }}"
  action:
  - service_template: "{{ 'script.cool_away' if is_state('climate.thermostat', 'cool') else 'script.heat_away' }}"