automation:
- alias: Start sleep mode cool early if running
  initial_state: true
  trigger:
  - platform: time
    at: !secret cool_sleep_work_early
  - platform: time
    at: !secret cool_sleep_weekend_early
  condition:
  - condition: or
    conditions:
    - condition: time
      after: !secret cool_sleep_work_early
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      after: !secret cool_sleep_weekend_early
      weekday: ['fri', 'sat']
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: template
    value_template: "{{ is_state_attr('climate.thermostat', 'hvac_action', 'cooling') and not is_state('sensor.tstat_comfort_setting', 'Sleep') }}"
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  action:
  - service: script.cool_sleep


- alias: Start home schedule earlier - sound check
  initial_state: true
  trigger:
  - platform: time
    at: '06:40:00'
  condition:
  - condition: template
    value_template: "{{ state_attr('calendar.church', 'message') != None and 'sound check' in state_attr('calendar.church', 'message').lower() }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: template
    value_template: "{{ states('climate.thermostat') in ['cool', 'heat'] }}"
  - condition: state
    entity_id: input_boolean.tstat_hold
    state: 'off'
  - condition: time
    weekday: sun
  action:
  - service_template: "script.{{ states('climate.thermostat') }}_home"
  - service: script.good_morning
  - service: homeassistant.turn_off
    entity_id:
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep
    - switch.plug_1


- alias: Turn heat off when away if warm outside
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    above: 50
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: 'heat'
  - condition: state
    entity_id: sensor.tstat_comfort_setting
    state: 'Away'
  action:
  - service: climate.turn_off
    entity_id: climate.thermostat


- alias: Ask to turn heat back on
  initial_state: true
  trigger:
  - platform: time
    at: !secret heat_sleep_work
  - platform: time
    at: !secret heat_sleep_weekend
  condition:
  - condition: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 35
  - condition: state
    entity_id: climate.thermostat
    state: 'off'
  - condition: or
    conditions:
    - condition: time
      after: !secret heat_sleep_work
      weekday: ['sun', 'mon', 'tue', 'wed', 'thu']
    - condition: time
      after: !secret heat_sleep_weekend
      weekday: ['fri', 'sat']
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Turn heat back on in sleep mode?"
      message: "It's currently {{ states('sensor.dark_sky_temperature') | float | round(0) }}° outside."
      data:
        actions:
        - action: heat_reenable
          title: Turn heat on


- alias: Action - turn heat back on
  initial_state: true
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: heat_reenable
  action:
  - service: script.heat_sleep