automation:
- alias: Lights off backup attempt
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.sleep_mode
    to: 'on'
    for: '00:00:05'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.lights_interior
      state: 'on'
    - condition: state
      entity_id: light.kitchen_cabinets
      state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.good_night_no_noise


- alias: Repeat white noise in sleep mode
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.bedroom_speaker
    from: 'playing'
    to: 'idle'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.andy_sleep
      state: 'on'
  action:
  - service: media_player.play_media
    entity_id: media_player.bedroom_speaker
    data:
      media_content_id: !secret white_noise
      media_content_type: audio/mp3


script:
  good_night:
    alias: Good night
    sequence:
    - service: input_boolean.turn_on
      data_template:
        entity_id: 
        - "input_boolean.{{ 'extra_sleep' if 6 <= now().hour < 18 else 'sleep_mode' }}"
        - input_boolean.andy_sleep
    - service: script.turn_on
      entity_id: script.white_noise_bedroom
    - service: homeassistant.turn_off
      entity_id: 
      - group.lights_interior
      - input_boolean.washer
      - input_boolean.dryer
      - input_boolean.christmas_porch_light_loop
      - switch.candle_warmer
    - service: script.turn_on
      entity_id: 
      - script.media_players_off
      - script.sleep_switches
      - script.porch_light_security
      - script.christmas_lights_off
    - service: climate.turn_on
      entity_id: climate.master_bedroom_fan
    - service: light.turn_on
      entity_id: light.master_bath_night_light
      data:
        brightness_pct: 10
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - service: script.alarm_arm_home


  good_night_no_noise:
    alias: Good night routine - no white noise
    sequence:
    - service: homeassistant.turn_off
      entity_id: 
      - group.lights_interior
      - input_boolean.christmas_porch_light_loop
      - media_player.living_room_vizio
    - service: script.turn_on
      entity_id: 
      - script.sleep_switches
      - script.christmas_lights_off
    - service: climate.turn_on
      entity_id: climate.master_bedroom_fan
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: script.turn_on
      entity_id: script.alarm_arm_home


  good_night_andy:
    sequence:
    - service: input_boolean.turn_on
      entity_id: input_boolean.andy_sleep
    - service: script.turn_on
      entity_id: 
      - script.white_noise_bedroom
      - script.porch_light_security
    - service: homeassistant.turn_off
      entity_id:
      - light.master_bedroom
      - media_player.bedroom_tv
      - light.dining_room
      - switch.air_freshener
      - light.tea_lights
      - group.lights_christmas
      - switch.candle_warmer
    - service: light.turn_on
      entity_id: light.master_bath_night_light
      data:
        brightness_pct: 10
    - service: light.turn_on
      entity_id: light.hall_bath_night_light
      data:
        brightness_pct: 50
    - service: light.turn_on
      entity_id: light.buffet
      data:
        brightness_pct: 25
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
        brightness_pct: "{{ 30 if is_state('binary_sensor.kitchen_motion', 'on') else 10 }}"
        transition: 5
    - condition: state
      entity_id: light.game_room
      state: 'on'
    - service: homeassistant.turn_off
      entity_id: light.living_room


  white_noise_bedroom:
    alias: Play white noise on bedroom speaker
    sequence:
    - service: input_boolean.turn_on
      entity_id: input_boolean.white_noise
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: true
    - service: media_player.turn_on
      entity_id: media_player.bedroom_speaker
    - service: media_player.play_media
      entity_id: media_player.bedroom_speaker
      data:
        media_content_id: 'http://10.0.0.2:8123/local/audio/silence.mp3'
        media_content_type: audio/mp3
    - delay: '00:00:02'
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data_template:
        volume_level: "{{ states('input_number.white_noise_vol') | int / 100 }}"
    - delay: '00:00:02'
    - service: media_player.play_media
      entity_id: media_player.bedroom_speaker
      data:
        media_content_id: !secret white_noise
        media_content_type: audio/mp3
    - wait_template: "{{ is_state('media_player.bedroom_speaker', 'playing') }}"
      timeout: '00:00:10'
      continue_on_timeout: true
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: false
    - service: input_boolean.turn_off
      entity_id: input_boolean.white_noise


  media_players_off:
    sequence:
    - service: media_player.turn_off
      entity_id:
      - media_player.bedroom_tv
      - media_player.living_room_vizio
      - media_player.living_room_speaker
      - media_player.portable_speaker
      - media_player.hub
      - media_player.kitchen_speaker


  sleep_switches:
    sequence:
    - service: homeassistant.turn_off
      entity_id: 
      - climate.space_heater
      - switch.space_heater
      - switch.air_freshener
      - switch.old_style_sign


input_number:
  white_noise_vol:
    name: White noise volume
    min: 40
    max: 80
    step: 2
    unit_of_measurement: '%'
    mode: slider


input_boolean:
  sleep_mode:
  andy_sleep:
  white_noise: