automation:
- alias: Turn bedroom lights off when curtains opened during day
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_curtains
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: light.master_bedroom
    state: 'on'
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.master_bedroom


- alias: Turn master bedroom closet light on/off with motion
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_closet_motion
    to: 
    - 'on'
    - 'off'
  - platform: state
    entity_id: light.master_bedroom_closet
    from: 'on'
    to: 'off'
  condition:
  - "{{ trigger.to_state.domain == 'light' or (trigger.to_state.domain == 'binary_sensor' and trigger.to_state.state != states('light.master_bedroom_closet')) }}"
  - "{{ trigger.to_state.state != states('input_boolean.master_bedroom_closet') }}"
  - condition: state
    entity_id:
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep
    state: 'off'
  action:
  - service: "input_boolean.turn_{{ trigger.to_state.state }}"
    entity_id: input_boolean.master_bedroom_closet
  - service: "light.turn_{{ states('input_boolean.master_bedroom_closet') }}"
    entity_id: light.master_bedroom_closet
  - condition: template
    value_template: "{{ trigger.to_state.state == 'on' }}"
  - service: light.turn_on
    entity_id: light.master_bedroom_closet_led
    data:
      brightness_pct: 100
      color_temp: 500


- alias: Turn master bedroom closet light off with remote
  initial_state: true
  trigger:
  - platform: device
    device_id: 55b3b74407f211eba837e390742b5002
    domain: homekit_controller
    type: button4
    subtype: single_press
  action:
  - service: light.turn_off
    entity_id: 
    - light.master_bedroom_closet
    - light.mini_christmas_tree


- alias: Turn master bedroom night light on with lights
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: light.matt_hk
    to: 'off'
  - platform: state
    entity_id: input_boolean.dark_inside
    to: 'on'
    for: '00:30:00'
  condition:
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  - condition: state
    entity_id: input_text.abode
    state:
    - 'armed_home'
    - 'disarmed'
  - condition: state
    entity_id:
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.master_bedroom_night_light
    data:
      brightness_pct: 100


- alias: Turn master bedroom night light off with lights
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: light.matt_hk
    to: 'on'
  condition:
  - condition: state
    entity_id: input_text.abode
    state:
    - 'armed_home'
    - 'disarmed'
  - condition: state
    entity_id:
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.master_bedroom_night_light
  - service: light.turn_on
    entity_id: light.mini_christmas_tree


- alias: Transition master bedroom lights to warm
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.dark_inside
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.matt_hk
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.master_bedroom
    data:
      kelvin: 3000
      brightness_pct: 100
      transition: 20


- alias: Turn mini Christmas tree on/off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.master_bedroom_motion
    to: 'off'
    for: '00:05:00'
  - platform: device
    device_id: 55b3b74407f211eba837e390742b5002
    domain: homekit_controller
    type: button1
    subtype: single_press
  condition:
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  action:
  - service: "light.turn_{{ 'on' if trigger.platform == 'device' or trigger.to_state.state == 'on' else 'off' }}"
    entity_id: light.mini_christmas_tree


switch:
- platform: template
  switches:
    bedroom_fan:
      friendly_name: Bedroom fan
      value_template: "{{ is_state('switch.master_bedroom_fan_plug', 'on') }}"
      turn_on:
        service: &power script.toggle_bedroom_fan
      turn_off:
        service: *power


climate:
- platform: generic_thermostat
  name: Master bedroom fan
  heater: switch.master_bedroom_fan_plug
  ac_mode: true
  target_sensor: sensor.master_bedroom_temp_calibrated
  min_temp: 63
  max_temp: 75
  cold_tolerance: 0
  hot_tolerance: 1


input_boolean:
  master_bedroom_closet: