automation:
- alias: Enable/disable hall bath night light motion sensor
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.dark_inside
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/hall_bath_night_light/backlog
      payload: "{{ 'rule1 1; rule2 0' if trigger.to_state.state == 'on' else 'rule1 0; rule2 1' }}"

- alias: Turn master bath nightlight on
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: input_boolean.dark_inside
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_text.alarm
    state:
    - 'armed_home'
    - 'disarmed'
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.master_bath_night_light
    data:
      brightness_pct: 100