automation:
- alias: Turn garage lights on with garage door
  id: 'oshugh9chie0gohtieR1Fi'
  initial_state: true
  trigger:
  - platform: state
    entity_id: &garage_door cover.garage_door
    from: 'closed'
    to: 'open'
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
  - condition: state
    entity_id: *garage_door
    state: 'open'
  action:
  - service: switch.turn_on
    entity_id: &garage_lights switch.garage_lights


- alias: Turn garage lights on with service door
  id: 'OoPeiy9eBaek4ha3Pooc3u'
  initial_state: true
  trigger:
  - platform: state
    entity_id: &service_door binary_sensor.garage_service_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: *garage_lights
    state: 'off'
  - condition: or
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: *garage_door
      state: 'closed'
  action:
  - service: switch.turn_on
    entity_id: *garage_lights


- alias: Turn garage lights off when garage and service door closed for 10 minutes
  id: 'echai5koodooza6Zeequar'
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - *garage_door
    - *service_door
    to:
    - 'closed'
    - 'off'
    for: &closed_time '00:10:00'
  condition:
  - condition: state
    entity_id: *garage_door
    state: 'closed'
    for: *closed_time
  - condition: state
    entity_id: *service_door
    state: 'off'
    for: *closed_time
  action:
  - service: switch.turn_off
    entity_id: *garage_lights


- alias: Open garage door when service door opened if leaving
  id: 'Aabee2Ne3engeichoomu8a'
  initial_state: true
  trigger:
  - platform: state
    entity_id: *service_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.leaving
    state: 'on'
  - condition: state
    entity_id: *garage_door
    state: 'closed'
  action:
  - service: cover.open_cover
    entity_id: *garage_door
  - service: input_boolean.turn_off
    entity_id: input_boolean.leaving


cover:
  - platform: mqtt
    name: Garage door
    command_topic: "cmnd/garage_door/POWER"
    state_topic: "stat/garage_door/status"
    availability_topic: "tele/garage_door/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "open"
    state_closed: "closed"
    device_class: garage