automation:
- alias: Turn garage door lights on with garage door
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_door
    from: 'off'
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.dark_inside
      state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.garage


- alias: Turn garage door lights on with service door
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.garage_service_door
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.garage_service_door
    - binary_sensor.garage_door
    from: 'on'
    to: 'off'
    for: '00:02:00'
  action:
  - service: "light.turn_{{ trigger.to_state.state }}"
    entity_id: light.garage


- alias: Turn garage lights off after power restored
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.garage
    to: 'on'
  condition:
  - condition: state
    entity_id: 
    - binary_sensor.garage_service_door
    - binary_sensor.garage_door
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.garage