automation:
- alias: Turn garage lights on/off with garage door
  initial_state: true
  trigger:
  - platform: state
    entity_id: &garage_door cover.garage_door
    to:
    - 'open'
    - 'closed'
  - platform: state
    entity_id: *garage_door
    to: 'open'
    for: &open_time '00:00:05'
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
  condition:
  - "{{ trigger.from_state.state not in ['unavailable', 'unknown'] }}"
  action:
  - choose:
    # when the garage door is opened or is already open at sunset, turn the garage lights on
    - conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
      - condition: state
        entity_id: *garage_door
        state: 'open'
      - condition: state
        entity_id: &garage_lights switch.garage_lights
        state: 'off'
      sequence:
      - service: switch.turn_on
        entity_id: *garage_lights

    # when the garage door is opened during the day and the lights are on, turn the garage lights off
    - conditions:
      - condition: state
        entity_id: *garage_door
        state: 'open'
        for: *open_time
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
      - condition: state
        entity_id: *garage_lights
        state: 'on'
      sequence:
      - service: switch.turn_off
        entity_id: *garage_lights

    # when the garage door is closed, turn the garage lights on
    - conditions:
      - "{{ trigger.to_state.state == 'closed' }}"
      - condition: state
        entity_id: *garage_lights
        state: 'off'
      sequence:
      - service: switch.turn_on
        entity_id: *garage_lights


- alias: Turn garage lights on with service door
  initial_state: true
  trigger:
  - platform: state
    entity_id: &service_door binary_sensor.garage_service_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: *garage_lights
    state: 'off'
  - condition: or
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: *garage_door
      state: 'closed'
  action:
  - service: switch.turn_on
    entity_id: *garage_lights


- alias: Turn garage lights on/off with motion
  initial_state: true
  trigger:
  - platform: state
    entity_id: &garage_motion binary_sensor.garage_motion
    to: 'on'
  - platform: state
    entity_id: *garage_motion
    to: 'off'
    for: '00:10:00'
  action:
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'on' }}"
      - condition: state
        entity_id: *garage_lights
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: state
          entity_id: *garage_door
          state: 'closed'
      sequence:
      - service: switch.turn_on
        entity_id: *garage_lights
    - conditions:
      - "{{ trigger.to_state.state == 'off' }}"
      - condition: state
        entity_id: *garage_lights
        state: 'on'
      sequence:
      - service: switch.turn_off
        entity_id: *garage_lights


- alias: Turn garage lights off when garage and service door closed for 10 minutes
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - *garage_door
    - *service_door
    - *garage_motion
    to:
    - 'closed'
    - 'off'
    for: &closed_time '00:10:00'
  condition:
  - condition: state
    entity_id: *garage_door
    state: 'closed'
    for: *closed_time
  - condition: state
    entity_id: *service_door
    state: 'off'
    for: *closed_time
  - condition: or
    conditions:
    - condition: state
      entity_id: *garage_motion
      state: 'unavailable'
    - condition: state
      entity_id: *garage_motion
      state: 'off'
      for: *closed_time
  action:
  - service: switch.turn_off
    entity_id: *garage_lights


- alias: Open garage door when service door opened if leaving
  initial_state: true
  trigger:
  - platform: state
    entity_id: *service_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.leaving
    state: 'on'
  - condition: state
    entity_id: *garage_door
    state: 'closed'
  action:
  - service: cover.open_cover
    entity_id: *garage_door
  - service: input_boolean.turn_off
    entity_id: input_boolean.leaving


cover:
  - platform: mqtt
    name: Garage door
    command_topic: "cmnd/garage_door/POWER"
    state_topic: "stat/garage_door/status"
    availability_topic: "tele/garage_door/LWT"
    qos: 1
    payload_available: "Online"
    payload_not_available: "Offline"
    payload_open: "ON"
    payload_close: "ON"
    payload_stop: "ON"
    state_open: "open"
    state_closed: "closed"
    device_class: garage