automation:
- alias: Turn on hall bath lights with motion
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.hall_bath_motion
    from: 'off'
    to: 'on'
  action:
  - choose:
    - conditions:
      - condition: time
        after: '22:00:00'
        before: '05:00:00'
      sequence:
      - service: light.turn_on
        entity_id: light.hall_bath_night_light
        data:
          brightness_pct: 100
    - conditions:
      - condition: state
        entity_id: light.living_room
        state: 'off'
      - condition: or
        conditions:
        - condition: time
          after: '21:00:00'
        - condition: sun
          after: sunset
          after_offset: "+02:00:00"
      sequence:
      - service: light.turn_on
        entity_id: light.hall_bath_night_light
        data:
          brightness_pct: 1
    - conditions:
      - condition: or
        conditions:
        - condition: time
          after: '21:00:00'
        - condition: sun
          after: sunset
          after_offset: "+02:00:00"
      sequence:
      - service: light.turn_on
        entity_id: light.hall_bath
        data:
          brightness_pct: 34
    default:
    - service: light.turn_on
      entity_id: light.hall_bath
      data:
        brightness_pct: 66


- alias: Turn on hall bath night light with lights
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.hall_bath
    to: 'off'
  - platform: time
    at: '22:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: time
    after: '22:00:00'
    before: '05:00:00'
  - condition: state
    entity_id: light.hall_bath
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.hall_bath_night_light
    data:
      brightness_pct: 100


- alias: Turn on/off hall bath lights with linen closet
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.linen_closet_door
    to:
    - 'on'
    - 'off'
  condition:
  - "{{ trigger.from_state.state != 'unavailable' }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.state == 'on' }}"
      - condition: state
        entity_id: light.hall_bath
        state: 'off'
      sequence:
      - service: light.turn_on
        entity_id: light.hall_bath
        data:
          brightness_pct: 100
    - conditions:
      - condition: template
        value_template: "{{ trigger.to_state.state == 'off' }}"
      sequence:
      - service: light.turn_on
        entity_id: light.hall_bath
        data:
          brightness_pct: 0


- alias: Dim hall bath night light with no motion
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.hall_bath_motion
    from: 'on'
    to: 'off'
    for: '00:10:00'
  condition:
  - condition: state
    entity_id: light.hall_bath_night_light
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.hall_bath_night_light
    data:
      brightness_pct: 34