automation:
- alias: Dim down/up cabinet lights with kitchen lights
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.kitchen
    to:
    - 'on'
    - 'off'
  action:
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'on' }}"
      - condition: state
        entity_id: light.kitchen_cabinets
        state: 'on'
      - "{{ state_attr('light.kitchen_cabinets', 'brightness') | int < 254 }}"
      sequence:
      - service: scene.create
        data:
          scene_id: kitchen_cabinets
          snapshot_entities:
          - light.kitchen_cabinets
      - service: light.turn_on
        entity_id: light.kitchen_cabinets
        data:
          brightness_pct: 100
      - service: input_boolean.turn_on
        entity_id: input_boolean.kitchen_cabinet_light_ctl
    - conditions:
      - "{{ trigger.to_state.state == 'off' }}"
      - condition: state
        entity_id: input_boolean.kitchen_cabinet_light_ctl
        state: 'on'
      sequence:
      - scene: scene.kitchen_cabinets
      - service: input_boolean.turn_off
        entity_id: input_boolean.kitchen_cabinet_light_ctl


light:
- platform: mqtt
  name: Kitchen
  state_topic: "stat/kitchen_lights/POWER1"
  command_topic: "cmnd/kitchen_lights/EVENT"
  availability_topic: "tele/kitchen_lights/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: group
  name: Kitchen cabinets
  entities:
  - light.cabinet_lights_n
  - light.cabinet_lights_s

input_boolean:
  kitchen_cabinet_light_ctl: