- platform: mqtt
  name: Basement fridge temp
  state_topic: &fridge_topic "rtl_433/107/event"
  value_template: "{{ '{:.1f}'.format((value_json.temperature_C | float * 9/5) + 32) }}"
  device_class: temperature
  json_attributes_topic: *fridge_topic
  force_update: true
  expire_after: &433-expiration 1200
  unit_of_measurement: '°F'

- platform: mqtt
  name: Main fridge temp
  state_topic: &freezer_topic "rtl_433/72/event"
  value_template: "{{ '{:.1f}'.format((value_json.temperature_C | float * 9/5) + 32) }}"
  device_class: temperature
  json_attributes_topic: *freezer_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°F'

- platform: mqtt
  name: Attic temp
  state_topic: &attic_temp_topic "rtl_433/5801/event"
  value_template: "{{ '{:.1f}'.format(((value_json.temperature_C | float * 9/5) + 32) + states('input_number.outside_temp_calib') | int) }}"
  device_class: temperature
  json_attributes_topic: *attic_temp_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°F'

- platform: mqtt
  name: Attic humidity
  state_topic: &attic_hum_topic "rtl_433/5801/event"
  value_template: "{{ '{:.0f}'.format(value_json.humidity) }}"
  device_class: temperature
  json_attributes_topic: *attic_hum_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '%'

- platform: mqtt
  name: Outside temp
  state_topic: &weather_station_topic "rtl_433/1291/event"
  value_template: "{{ '{:.1f}'.format(value_json.temperature_F) }}"
  device_class: temperature
  json_attributes_topic: *weather_station_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°F'

- platform: mqtt
  name: Outside humidity
  state_topic: *weather_station_topic
  value_template: "{{ '{:.0f}'.format(value_json.humidity) }}"
  device_class: humidity
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '%'

- platform: mqtt
  name: Wind speed
  state_topic: *weather_station_topic
  value_template: "{{ '{:.2f}'.format(value_json.wind_avg_km_h | float / 1.609) }}"
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: 'mph'

- platform: mqtt
  name: Wind direction degrees
  state_topic: *weather_station_topic
  value_template: "{{ '{:.0f}'.format(value_json.wind_dir_deg) }}"
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°'