- platform: attributes
  attribute: battery_low
  entities:
  - binary_sensor.storage_cloud
  - binary_sensor.keypad
  - binary_sensor.front_door_cloud
  - binary_sensor.balcony_door_cloud
  - camera.motion_camera

- platform: attributes
  attribute: app_name
  entities:
  - media_player.portable_speaker
  - media_player.bedroom_speaker
  - media_player.hub
  - media_player.kitchen_speaker
  - media_player.living_room_speaker
  - media_player.living_room_vizio
  - media_player.living_room_cast

- platform: attributes
  attribute: media_title
  entities:
  - media_player.portable_speaker
  - media_player.bedroom_speaker
  - media_player.hub
  - media_player.kitchen_speaker
  - media_player.living_room_speaker