- platform: attributes
  attribute: app_name
  entities:
  - media_player.office_speaker
  - media_player.bedroom_speaker
  - media_player.hub
  - media_player.kitchen_speaker
  - media_player.living_room_speaker
  - media_player.living_room_vizio
  - media_player.living_room_cast

- platform: attributes
  attribute: media_title
  entities:
  - media_player.office_speaker
  - media_player.bedroom_speaker
  - media_player.hub
  - media_player.kitchen_speaker
  - media_player.living_room_speaker
  - media_player.craft_room_speaker