- platform: history_stats
  name: Xbox time today
  entity_id: binary_sensor.xbox
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: Xbox time yesterday
  entity_id: binary_sensor.xbox
  state: 'on'
  type: time
  duration:
    hours: 24
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'

- platform: history_stats
  name: Xbox time last 7 days
  entity_id: binary_sensor.xbox
  state: 'on'
  type: time
  duration:
    days: 7
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'