- platform: systemmonitor
  resources:
  - type: memory_use
  - type: memory_use_percent
  - type: processor_use
  - type: load_1m
  - type: load_5m
  - type: load_15m


- platform: statistics
  name: Indoor temp stats
  entity_id: sensor.tstat_current_temp
  sampling_size: 30
  max_age: 1800
  precision: 1

- platform: template
  sensors:
    indoor_temp_trend:
      friendly_name: Indoor temp trend
      value_template: "{{ state_attr('sensor.indoor_temp_stats', 'average_change') }}"
      unit_of_measurement: '°F'

- platform: dewpoint
  sensors:
    dewpoint_inside:
      friendly_name: Indoor dew point
      temperature: sensor.tstat_current_temp
      rel_hum: sensor.tstat_current_humidity
    dewpoint_outside:
      friendly_name: Outdoor dew point
      temperature: sensor.outside_temp
      rel_hum: sensor.outside_humidity
    dewpoint_attic:
      friendly_name: Attic dew point
      temperature: sensor.attic_temp
      rel_hum: sensor.attic_humidity
    dewpoint_laundry_room:
      friendly_name: Laundry room dew point
      temperature: sensor.laundry_room_temp
      rel_hum: sensor.laundry_room_humidity
    dewpoint_basement:
      friendly_name: Basement dew point
      temperature: sensor.basement_temp
      rel_hum: sensor.basement_humidity

- platform: time_date
  display_options:
  - date
  - time
  - date_time_iso

- platform: uptime