# - platform: mqtt
#   state_topic: !secret covid_sensor_1_topic
#   json_attributes_topic: !secret covid_sensor_1_attr
#   unique_id: !secret covid_sensor_1_id

#- platform: mqtt
#  state_topic: tracking/ebay
#  name: Smart plug order
#  value_template: "{{ value_json.status }}"

- platform: systemmonitor
  resources:
  - type: memory_use
  - type: memory_use_percent
  - type: processor_use
  - type: load_1m
  - type: load_5m
  - type: load_15m

- platform: rest
  resource: !secret hue_rest
  name: Hue bridge
  value_template: "{{ value_json['swupdate2']['bridge']['state'] }}"
  json_attributes:
  - name
  - zigbeechannel
  - ipaddress
  - modelid
  - swversion
  - apiversion
  scan_interval: 30

# - platform: command_line
#   name: CPU temp # this one is to force Celcius in frontend, but will not have history graph
#   command: "cat /sys/class/thermal/thermal_zone9/temp"
#   value_template: "{{ (value | multiply(0.001)) | round(0) }} °C"

# - platform: command_line
#   name: CPU temp hist
#   command: "cat /sys/class/thermal/thermal_zone9/temp"
#   value_template: "{{ (value | multiply(0.001)) | round(0) }}"

- platform: dewpoint
  sensors:
    dewpoint_inside:
      friendly_name: Indoor dew point
      temperature: sensor.tstat_current_temp
      rel_hum: sensor.tstat_current_humidity
    dewpoint_outside:
      friendly_name: Outdoor dew point
      temperature: sensor.outside_temp_dewpoint
      rel_hum: sensor.outside_humidity_dewpoint

- platform: time_date
  display_options:
  - date
  - time
  - date_time_iso

- platform: uptime

- platform: darksky
  api_key: !secret darksky_key
  scan_interval: '00:03:00'
  monitored_conditions:
  - temperature
  - apparent_temperature
  - dew_point
  - cloud_cover
  - temperature_high
  - temperature_low

- platform: mqtt
  name: SSD temp
  state_topic: "ssd_temp/temp"

- platform: mqtt
  name: Server battery
  state_topic: &server_battery_topic "battery2mqtt/server/BAT0"
  value_template: "{{ value_json.capacity }}"
  unit_of_measurement: '%'
  device_class: battery
  json_attributes_topic: *server_battery_topic

- platform: mqtt
  name: Mouse battery
  state_topic: &mouse_battery_topic "battery2mqtt/mouse/hid-34:88:5d:93:15:6b-battery"
  value_template: "{{ value_json.capacity }}"
  unit_of_measurement: '%'
  device_class: battery
  json_attributes_topic: *mouse_battery_topic

- platform: mqtt
  name: Server CPU temp
  state_topic: "temp2mqtt/server/cpu_temp"
  value_template: "{{ value_json.cpu_temp }}"
  unit_of_measurement: 'C'
  device_class: temperature

- platform: mqtt
  name: Server fan speed
  state_topic: "temp2mqtt/server/cpu_temp"
  value_template: "{{ value_json.fan_speed }}"
  unit_of_measurement: 'RPM'