- platform: systemmonitor
  resources:
  - type: memory_use
  - type: memory_use_percent
  - type: processor_use
  - type: load_1m
  - type: load_5m
  - type: load_15m

- platform: rest
  resource: !secret hue_rest
  name: Hue bridge
  value_template: "{{ value_json['swupdate2']['bridge']['state'] }}"
  json_attributes:
  - name
  - zigbeechannel
  - ipaddress
  - modelid
  - swversion
  - apiversion
  scan_interval: 30

- platform: dewpoint
  sensors:
    dewpoint_inside:
      friendly_name: Indoor dew point
      temperature: sensor.tstat_current_temp
      rel_hum: sensor.tstat_current_humidity
    dewpoint_outside:
      friendly_name: Outdoor dew point
      temperature: sensor.outside_temp
      rel_hum: sensor.outside_humidity

- platform: time_date
  display_options:
  - date
  - time
  - date_time_iso

- platform: uptime

- platform: darksky
  api_key: !secret darksky_key
  scan_interval: '00:03:00'
  monitored_conditions:
  - temperature
  - apparent_temperature
  - dew_point
  - cloud_cover
  - temperature_high
  - temperature_low