- platform: template
  sensors:
    # outside_temp_darksky:
    #   friendly_name: "Outside"
    #   value_template: "{{ state_attr('weather.dark_sky', 'temperature') | float('-') | round(0) }}"
    #   unit_of_measurement: '°F'

    # outside_temp_display:
    #   friendly_name: "Outside"
    #   value_template: "{{ states('sensor.outside_temp') | round(0) | int }}"
    #   unit_of_measurement: '°F'

    # outside_humidity_darksky:
    #   friendly_name: "Outside"
    #   value_template: "{{ 50 if is_state('weather.dark_sky', 'unavailable') else state_attr('weather.dark_sky', 'humidity') | round(0) }}"
    #   unit_of_measurement: '%'
    
    dewpoint_outside_display:
      friendly_name: "Dew point"
      value_template: "{{ states('sensor.dewpoint_outside') | float | round(0) }}"
      unit_of_measurement: '°F'

    dewpoint_inside_display:
      friendly_name: "Dew point"
      value_template: "{{ states('sensor.dewpoint_inside') | float | round(0) }}"
      unit_of_measurement: '°F'

    ssd_temp_disp:
      friendly_name: SSD temp
      value_template: "{{ states('sensor.ssd_temp') }} °C"

    attic_temp_delta:
      friendly_name: Attic temp delta
      value_template: "{{ (states('sensor.attic_temp') | float - states('sensor.outside_temp') | float) | round(1) }}"
      unit_of_measurement: '°F'

    server_fan_speed_pct:
      friendly_name: Server fan speed
      value_template: >
        {% set speed = states('sensor.server_fan_speed') | int %}
        {% if speed < 3200 %}
          Low
        {% elif speed < 3600 %}
          Medium
        {% elif speed < 3900 %}
          High
        {% else %}
          Max
        {% endif %}

    wind_direction:
      friendly_name: Wind direction
      value_template: >
        {% set degrees = ((states('sensor.wind_direction_degrees') | float - 11.25) / 22.5) | round(0, 'ceil') | int %}
        {% set compass = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'] %}
        {{ compass[degrees] }}