- platform: template
  sensors:
    dewpoint_outside_display:
      friendly_name: "Dew point"
      value_template: "{{ states('sensor.dewpoint_outside') | float | round(0) }}"
      unit_of_measurement: '째F'

    dewpoint_inside_display:
      friendly_name: "Dew point"
      value_template: "{{ states('sensor.dewpoint_inside') | float | round(0) }}"
      unit_of_measurement: '째F'

    ssd_temp_disp:
      friendly_name: SSD temp
      value_template: "{{ states('sensor.ssd_temp') }} 째C"

    attic_temp_delta:
      friendly_name: Attic temp delta
      value_template: "{{ (states('sensor.attic_temp') | float - states('sensor.outside_temp') | float) | round(1) }}"
      unit_of_measurement: '째F'

    wind_direction:
      friendly_name: Wind direction
      value_template: >
        {% set degrees = ((states('sensor.wind_direction_degrees') | float - 11.25) / 22.5) | round(0, 'ceil') | int %}
        {% set compass = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW'] %}
        {{ compass[degrees] }}