# - alias: Sync portable speaker to all speakers
#   trigger:
#   - platform: state
#     entity_id: binary_sensor.all_speakers
#     to: 'on'
#   action:
#   - service: media_player.play_media
#     entity_id: media_player.portable_speaker
#     data_template:
#       media_content_id: "{{ state_attr('media_player.living_room_speaker', 'media_content_id') }}"
#       media_content_type: music