### Arrival
- alias: Turn lights on upon entrance
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.front_door
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1
  - service: media_player.turn_on
    entity_id: media_player.living_room_speaker
  - delay: '00:01:00'
  - service: switch.turn_off
    entity_id: switch.light_switch_1


- alias: Turn lights on when alarm disarmed dark inside
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    from: armed_away
    to: disarmed
  condition:
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'on'
  action:
  - service_template: "{{ 'script.arrival' if is_state('input_boolean.christmas_mode', 'off') else 'script.arrival_christmas' }}"


- alias: Turn lights on when alarm disarmed not dark inside
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    from: armed_away
    to: disarmed
  condition:
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1
  - wait_template: "{{ is_state('binary_sensor.front_door', 'on') }}"
    timeout: '00:10:00'
    continue_on_timeout: 'false'
  - delay: '00:01:00'
  - service: switch.turn_off
    entity_id: switch.light_switch_1


### Departure
- alias: Activate away mode when armed away
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: armed_away
  action:
  - service: script.away_mode


- alias: Away mode backup attempt
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: armed_away
    for: '00:00:30'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.lights_all
      state: 'on'
    - condition: state
      entity_id: binary_sensor.any_media_player
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: all
  - service: media_player.turn_off
    entity_id: all
