- alias: Turn entrance light on before work
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:25:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%-d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%-d') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1


- alias: Turn entrance light on before sound check
  initial_state: 'on'
  trigger:
  - platform: time
    at: '06:55:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%-H') | int < state_attr('calendar.church', 'start_time')[11:13] | int }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: time
    weekday: sun
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1


- alias: Turn entrance light off
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:50:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%-d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%-d') }}"
  action:
  - service: switch.turn_off
    entity_id: switch.light_switch_1


- alias: Turn front closet light on when door opened
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.front_closet
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_on
    entity_id: light.front_closet
    data_template:
      brightness: >
        {% set dark = states('binary_sensor.dark_inside') %}
        {% if dark == 'on' %}
          128
        {% else %}
          255
        {% endif %}


- alias: Turn front closet light off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.front_closet
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    data:
      entity_id: light.front_closet