- alias: Good morning - workday
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: script.good_morning
  - service: switch.turn_off
    entity_id: switch.plug_1


- alias: Turn fan off at 7:30am on day off
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:30:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') != as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') }}"
  action:
  - service: switch.turn_off
    entity_id: switch.plug_1


- alias: Reset bedroom speaker volume
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_speaker
      volume_level: 0.4


- alias: Turn off sleep mode
  initial_state: 'on'
  trigger:
  - platform: time
    at: '06:00:00'
  action:
  - service: input_boolean.turn_off
    entity_id:
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep