- alias: Activate away mode when armed away
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: armed_away
  action:
  - service: script.away_mode


- alias: Away mode backup attempt
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: armed_away
    for: '00:00:30'
  condition:
  - condition: state
    entity_id: group.lights_interior
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: group.lights_interior