- alias: Turn space heater on when gaming
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.xbox
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: 'heat'
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
  action:
  - service: climate.turn_on
    entity_id: climate.space_heater


- alias: Turn space heater off after gaming
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.xbox
    platform: state
    from: 'on'
    to: 'off'
  action:
  - service: climate.turn_off
    entity_id: climate.space_heater


- alias: Turn bias light on when Xbox on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.xbox
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
  action:
  - service: switch.turn_on
    entity_id: switch.plug3
  - service: media_player.turn_off
    entity_id:
    - media_player.all_speakers
    - media_player.portable_speaker


- alias: Turn bias light off when Xbox off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.xbox
    from: 'on'
    to: 'off'
  action:
  - service: switch.turn_off
    entity_id: switch.plug3


- alias: Reset game room lights when xbox turned on
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.xbox
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.game_room
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Game room
      scene_name: Read


- alias: Turn on game room lights when bias light turned on
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.xbox
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: light.game_room
    state: 'off'
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Game room
      scene_name: Read


- alias: Turn game room lights on at sunset when gaming
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.dark_inside
    from: 'off'
    to: 'on'
  condition: 
  - condition: state
    entity_id: binary_sensor.xbox
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Game room
      scene_name: Read


- alias: Turn space heater off if on for 1 hour
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.plug4
    to: 'on'
    for: '01:00:00'
  action:
  - service: switch.turn_off
    entity_id: switch.plug4
  - service: climate.turn_off
    entity_id: climate.space_heater