- alias: Dim lights when LR playing
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
  - platform: state
    entity_id: media_player.vizio_smartcast
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: and
      conditions:
      - condition: state
        entity_id: light.right_lamp
        state: 'on'
      - condition: state
        entity_id: light.left_lamp
        state: 'on'
  action:
  - service_template: >-
      {% if is_state('binary_sensor.dark_inside', 'on') %}
        script.dark_inside_premedia
      {% else %}
        script.not_dark_inside_premedia
      {% endif %}


- alias: Restore lights when TV turned off
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'idle'
    to: 'off'
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'paused'
    to: 'off'
  - platform: state
    entity_id: media_player.living_room_tv
    from: 'playing'
    to: 'off'
  - platform: state
    entity_id: media_player.vizio_smartcast
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service_template: >-
      {% if is_state('input_boolean.not_dark', 'on') %}
        script.not_dark_inside_postmedia
      {% else %}
        script.dark_inside_postmedia
      {% endif %}


- alias: Boost TV volume when furnace on - cool
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'cooling'
  condition:
    condition: state
    entity_id: media_player.vizio_smartcast
    state: 'on'
  action:
  - service: script.tv_vol_up


- alias: Boost TV volume when furnace on - heat
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'heating'
    for: '00:00:15'
  condition:
    condition: state
    entity_id: media_player.vizio_smartcast
    state: 'on'
  action:
  - service: script.tv_vol_up_heat


- alias: Lower TV volume when furnace off - cool
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'cooling'
    to: 'idle'
    for: '00:00:15'
  - platform: state
    entity_id: sensor.hvac_action
    from: 'cooling'
    to: 'off'
    for: '00:00:15'
  condition:
    condition: state
    entity_id: media_player.vizio_smartcast
    state: 'on'
  action:
  - service: script.tv_vol_dn


- alias: Lower TV volume when furnace off - heat
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'heating'
    to: 'idle'
    for: '00:01:30'
  - platform: state
    entity_id: sensor.hvac_action
    from: 'heating'
    to: 'off'
    for: '00:01:30'
  condition:
    condition: state
    entity_id: media_player.vizio_smartcast
    state: 'on'
  action:
  - service: script.tv_vol_dn_heat