- alias: Turn lights on upon entrance
  initial_state: 'on'
  trigger:
  - entity_id: binary_sensor.front_door
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch1
  - service: media_player.turn_on
    entity_id: media_player.living_room_speaker
  - delay: '00:01:00'
  - service: switch.turn_off
    entity_id: switch.light_switch1


- alias: Turn lights on when alarm disarmed dark inside
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: disarmed
    from: armed_away
  condition:
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'on'
  action:
  - service_template: >
      {% if is_state('input_boolean.christmas_mode', 'off') %}
        script.arrival
      {% else %}
        script.arrival_christmas
      {% endif %}


- alias: Turn lights on when alarm disarmed not dark inside
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: disarmed
    from: armed_away
  condition:
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch1
  - wait_template: "{{ is_state('binary_sensor.front_door', 'on') }}"
    timeout: '00:10:00'
    continue_on_timeout: 'false'
  - delay: '00:01:00'
  - service: switch.turn_off
    entity_id: switch.light_switch1
