- alias: Turn lights on at sunset if home
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.dark_inside
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: light.turn_on
    entity_id: light.dining_room
    data:
      kelvin: 3000
      transition: 30
      brightness_pct: 100
  - delay: '00:00:30'
  - service: switch.turn_on
    entity_id: 
    - switch.plug_2
    - switch.tuya_plug_2