- alias: Record time when cycle starts
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to:
    - 'cooling'
    - 'heating'
  action:
  - service: input_text.set_value
    entity_id: input_text.time_cycle_start
    data_template:
      value: '{{ now() }}'


- alias: Record time when cycle ends
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'idle'
  - platform: state
    entity_id: sensor.hvac_action
    from:
    - 'cooling'
    - 'heating'
    to: 'off'
  action:
  - service: input_text.set_value
    entity_id: input_text.time_cycle_end
    data_template:
      value: '{{ now() }}'


- alias: HVAC runtime adjustment
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_number.runtime_adjustment
  action:
  - service: script.hvac_runtime_adjustment