- alias: Turn lights on at sunset if home
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.dark_inside
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: light.turn_on
    entity_id: light.dining_room
    data:
      kelvin: 3000
      transition: 30
      brightness_pct: 100
  - delay: '00:01:00'
  - service: switch.turn_on
    entity_id: switch.plug_2
  - condition: state
    entity_id: input_boolean.christmas_mode
    state: 'on'
  - service: switch.turn_on
    entity_id: switch.tuya_plug_2


- alias: Toggle Christmas mode
  initial_state: 'on'
  trigger:
  - platform: time
    at: '00:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: template
    value_template: "{{ (now().month == 12 and now().day == 1) or (now().month == 1 and now().day == 2) }}"
  action:
  - service_template: "{{ 'input_boolean.turn_on' if now().month == 12 else 'input_boolean.turn_off' }}"
    entity_id: input_boolean.christmas_mode