- alias: Turn lights on when leak detected
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_sensor_1
    - binary_sensor.water_sensor_2
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode_alarm
    state: 'armed_home'
  action:
  - service: hue.hue_activate_scene
    data:
      group_name: Master bedroom
      scene_name: Water
  - service: hue.hue_activate_scene
    data:
      group_name: Living room
      scene_name: Water


- alias: Turn stuff off after power outage
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - switch.hdmi_0
    - switch.plug3
    - light.porch_light
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.router_uptime
      below: 0.01
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_away
  action:
  - service: homeassistant.turn_off
    entity_id: 
    - switch.hdmi_0
    - switch.plug3
    - light.porch_light


- alias: Record washer on
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.washer_power
    above: 550
  condition:
    condition: state
    entity_id: input_boolean.washer
    state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washer


- alias: Record washer off
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.washer_power
    below: 1.5
  condition:
    condition: state
    entity_id: input_boolean.washer
    state: 'on'
  action: 
  - service: input_boolean.turn_off
    entity_id: input_boolean.washer


- alias: Turn Christmas mode on
  initial_state: 'on'
  trigger:
  - platform: time
    at: '00:00:00'
  condition:
  - condition: template
    value_template: "{{ now().month == 12 and now().day == 1 }}"
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.christmas_mode


- alias: Turn Christmas mode off
  initial_state: 'on'
  trigger:
  - platform: time
    at: '00:00:00'
  condition:
  - condition: template
    value_template: "{{ now().month == 12 and now().day == 26 }}"
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.christmas_mode


- alias: Dismiss discovery notification
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: persistent_notification.config_entry_discovery
    to: 'notifying'
  action:
    service: persistent_notification.dismiss
    data:
      notification_id: config_entry_discovery





