- alias: Speak alarm disarmed - home
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    from: armed_home
    to: disarmed
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: media_player.living_room_speaker
      state: 'off'
    - condition: state
      entity_id: media_player.living_room_speaker
      state: 'idle'
  action:
  - service: tts.google
    entity_id: media_player.living_room_speaker
    data:
      message: "Alarm off."
  # - service: media_player.play_media
  #   entity_id: media_player.living_room_speaker
  #   data:
  #     media_content_id: "http://10.0.0.2:8123/local/audio/Alarm_off.mp3"
  #     media_content_type: audio/mp3
  - delay: '00:00:10'
  - service: media_player.turn_off
    entity_id: media_player.living_room_speaker


- alias: Speak welcome home
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    from: armed_away
    to: disarmed
  action:
  - service: tts.google
    entity_id: media_player.living_room_speaker
    data:
      message: "Welcome home."
  # - service: media_player.play_media
  #   entity_id: media_player.living_room_speaker
  #   data:
  #     media_content_id: "http://10.0.0.2:8123/local/audio/welcome_home.mp3"
  #     media_content_type: audio/mp3
  - delay: '00:00:10'
  - service: media_player.volume_set
    data:
      entity_id: media_player.living_room_speaker
      volume_level: 0.36
  - service: media_player.turn_off
    entity_id: media_player.living_room_speaker
  - service: cloud.remote_disconnect


- alias: Speak alarm on home
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: armed_home
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: media_player.living_room_speaker
      state: 'off'
    - condition: state
      entity_id: media_player.living_room_speaker
      state: 'idle'
  action:
  - service: tts.google
    entity_id: media_player.living_room_speaker
    data:
      message: "Alarm on, home."
  # - service: media_player.play_media
  #   entity_id: media_player.living_room_speaker
  #   data:
  #     media_content_id: "http://10.0.0.2:8123/local/audio/Alarm_home.mp3"
  #     media_content_type: audio/mp3
  - delay: '00:00:10'
  - service: media_player.turn_off
    entity_id: media_player.living_room_speaker


- alias: Speak when Home Assistant starts
  initial_state: 'on'
  trigger:
    platform: homeassistant
    event: start
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.portable_speaker
      state: 'off'
    - condition: state
      entity_id: media_player.portable_speaker
      state: 'idle'
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: 'armed_home'
    - condition: state
      entity_id: alarm_control_panel.abode
      state: 'disarmed'
  action:
  - service: tts.google
    entity_id: media_player.portable_speaker
    data:
      message: "Server online."
  # - service: media_player.play_media
  #   entity_id: media_player.portable_speaker
  #   data:
  #     media_content_id: "http://10.0.0.2:8123/local/audio/server_online.mp3"
  #     media_content_type: audio/mp3
  - delay: '00:00:10'
  - service: media_player.turn_off
    entity_id: media_player.portable_speaker