- alias: Set speaker volume based on app
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - sensor.portable_speaker_app_name
    - sensor.bedroom_speaker_app_name
    - sensor.hub_app_name
    - sensor.kitchen_speaker_app_name
    - sensor.living_room_speaker_app_name
  condition:
  - condition: state
    entity_id: binary_sensor.quiet_hours
    state: 'off'
  - condition: template
    value_template: "{{ trigger.to_state.state != '' }}"
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: "media_player.{{ trigger.to_state.name.lower().replace(' ','_') }}"
      volume_level: >
        {% set speaker = trigger.to_state.entity_id.replace('sensor.','').replace('_app_name','').replace('_',' ') %}
        {% set app = trigger.to_state.state %}
        {% if app in ['iHeartRadio', 'Default Media Receiver'] %}
          {% if speaker in ['portable speaker', 'living room speaker'] %}
            0.45
          {% elif speaker in ['bedroom speaker', 'kitchen speaker'] %}
            0.4
          {% elif speaker in ['hub'] %}
            0.5
          {% else %}
            0.4
          {% endif %}
        {% elif app in ['Google Play Music', 'Spotify'] %}
          {% if speaker in ['bedroom speaker', 'kitchen speaker'] %}
            0.36
          {% elif speaker in ['portable speaker'] %}
            0.3
          {% elif speaker in ['living room speaker', 'hub'] %}
            0.4
          {% else %}
            0.36
          {% endif %}
        {% else %}
          0.4
        {% endif %}


- alias: Boost speaker volume when furnace on
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'cooling'
  - platform: state
    entity_id: sensor.hvac_action
    to: 'heating'
    for: '00:00:15'
  condition:
  - condition: state
    entity_id: binary_sensor.quiet_hours
    state: 'off'
  - condition: template
    value_template: "{{ not is_state('sensor.living_room_speaker_app_name', '') }}"
  action:
    service: media_player.volume_set
    entity_id: media_player.living_room_speaker
    data_template:
      volume_level: >
        {% set app = states('sensor.living_room_speaker_app_name') %}
        {% if app == 'iHeartRadio' %}
          0.5
        {% else %}
          0.42
        {% endif %}


- alias: Lower speaker volume when furnace off
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'cooling'
    to:
    - 'idle'
    - 'off'
    for: '00:00:15'
  - platform: state
    entity_id: sensor.hvac_action
    from: 'heating'
    to:
    - 'idle'
    - 'off'
    for: '00:01:00'
  condition:
  - condition: state
    entity_id: binary_sensor.quiet_hours
    state: 'off'
  - condition: template
    value_template: "{{ not is_state('sensor.living_room_speaker_app_name', '') }}"
  action:
    service: media_player.volume_set
    entity_id: media_player.living_room_speaker
    data_template:
      volume_level: >
        {% set app = states('sensor.living_room_speaker_app_name') %}
        {% if app == 'iHeartRadio' %}
          0.45
        {% else %}
          0.36
        {% endif %}