#################################
###  Cool - Arriving home
#################################

- alias: Home mode - cool - arrival
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.cool_home
  condition:
  - condition: time
    after: '07:00:00'
    before: '21:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: climate.thermostat
    state: cool
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_home


- alias: Home mode - cool - arrival - weekend
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.cool_home
  condition:
  - condition: time
    after: '07:00:00'
    before: '21:30:00'
    weekday:
    - fri
    - sat
  - condition: state
    entity_id: climate.thermostat
    state: cool
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_home


- alias: Sleep mode - cool - arrival work night
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.cool_sleep
  condition:
  - condition: time
    after: '21:00:00'
    before: '07:00:00'
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: state
    entity_id: climate.thermostat
    state: cool
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_sleep


- alias: Sleep mode - cool - arrival weekend
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.cool_sleep
  condition:
  - condition: time
    after: '21:30:00'
    before: '07:00:00'
    weekday:
    - fri
    - sat
  - condition: state
    entity_id: climate.thermostat
    state: cool
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_sleep



#################################
###  Cool - Already at home
#################################

- alias: Cool - Home mode - workday
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_home


- alias: Cool - Home mode - weekend
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:30:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: time
    weekday:
    - sat
    - sun
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_home


- alias: Cool - Sleep mode - work night
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_sleep


- alias: Cool - Sleep mode - weekend
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:30:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: time
    weekday:
    - fri
    - sat
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_sleep



#################################
###  Heat - Arriving home
#################################

- alias: Heat - Home mode - arrival
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.heat_home
  condition:
  - condition: time
    after: '07:00:00'
    before: '21:00:00'
  - condition: state
    entity_id: climate.thermostat
    state: heat
  action:
  - service: script.turn_on
    data:
      entity_id: script.heat_home


- alias: Heat - Sleep mode - arrival
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode
    from: armed_away
    to: disarmed
  - platform: state
    entity_id: input_number.heat_sleep
  condition:
  - condition: time
    after: '21:00:00'
    before: '07:00:00'
  - condition: state
    entity_id: climate.thermostat
    state: heat
  action:
  - service: script.turn_on
    data:
      entity_id: script.heat_sleep



#################################
###  Heat - Already at home
#################################

- alias: Heat - Home mode - workday
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:00:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: heat
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: script.turn_on
    data:
      entity_id: script.heat_home


- alias: Heat - Home mode - weekend
  initial_state: 'on'
  trigger:
    platform: time
    at: '07:30:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: heat
  - condition: time
    weekday:
    - sat
    - sun
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: script.turn_on
    data:
      entity_id: script.heat_home


- alias: Heat - Sleep mode
  initial_state: 'on'
  trigger:
    platform: time
    at: '21:00:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: heat
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: disarmed
    - condition: state
      entity_id: alarm_control_panel.abode
      state: armed_home
  action:
  - service: script.turn_on
    data:
      entity_id: script.heat_sleep



#################################
###  Away mode
#################################

- alias: Cool - Away mode
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.abode
    to: armed_away
  condition:
    condition: state
    entity_id: climate.thermostat
    state: cool
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_away


- alias: Heat - away mode
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.abode
    to: armed_away
  condition:
    condition: state
    entity_id: climate.thermostat
    state: heat
  action:
  - service: script.turn_on
    data:
      entity_id: script.heat_away



#################################
###  Intelligence
#################################

- alias: Start sleep mode early if running (cool - week)
  initial_state: 'on'
  trigger:
  - platform: time
    at: '20:45:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: template
    value_template: "{{ is_state_attr('climate.thermostat', 'hvac_action', 'cooling') }}"
  - condition: time
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_sleep


- alias: Start sleep mode early if running (cool - weekend)
  initial_state: 'on'
  trigger:
  - platform: time
    at: '21:15:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: template
    value_template: "{{ is_state_attr('climate.thermostat', 'hvac_action', 'cooling') }}"
  - condition: time
    weekday:
    - fri
    - sat
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_sleep


- alias: Start home mode early if not running (cool - week)
  initial_state: 'on'
  trigger:
  - platform: time
    at: '06:45:00'
  condition:
  - condition: template
    value_template: "{{ is_state_attr('climate.thermostat', 'hvac_action', 'off') }}"
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_home


- alias: Start home mode early if not running (cool - weekend)
  initial_state: 'on'
  trigger:
  - platform: time
    at: '07:15:00'
  condition:
  - condition: template
    value_template: "{{ is_state_attr('climate.thermostat', 'hvac_action', 'off') }}"
  - condition: state
    entity_id: climate.thermostat
    state: cool
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: script.turn_on
    data:
      entity_id: script.cool_home


- alias: Start sleep mode early if not running (heat)
  initial_state: 'on'
  trigger:
  - platform: time
    at: '20:50:00'
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: heat
  - condition: template
    value_template: "{{ is_state_attr('climate.thermostat', 'hvac_action', 'heating') }}"
  action:
  - service: script.turn_on
    data:
      entity_id: script.heat_sleep