- platform: history_stats
  name: Cooling time today
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: history_stats
  name: Cooling cycles today
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: count
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: history_stats
  name: Cooling percent today
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: ratio
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


- platform: history_stats
  name: Cooling cycles yesterday
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: count
  duration:
    hours: 24
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'


- platform: history_stats
  name: Cooling percent yesterday
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: ratio
  duration:
    hours: 24
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'


- platform: history_stats
  name: Cooling percent last 7 days
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: ratio
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7


- platform: history_stats
  name: Cooling cycles last 7 days
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: count
  end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  duration:
    days: 7


- platform: history_stats
  name: Cooling since cycle start
  entity_id: sensor.hvac_action
  state: 'cooling'
  type: time
  start: "{{ states('input_text.time_cycle_start') }}"
  end: '{{ now() }}'