- platform: attributes
  friendly_name: 'Battery'
  attribute: battery
  unit_of_measurement: '%'
  entities:
  - sensor.dining_room_remote
  - sensor.game_room_remote
  - sensor.living_room_remote
  - sensor.master_bedroom_remote

- platform: attributes
  friendly_name: 'Battery'
  attribute: battery_level
  unit_of_measurement: '%'
  entities:
  - binary_sensor.motion_sensor_motion
  - binary_sensor.motion_sensor_1
  - binary_sensor.front_closet
  - binary_sensor.storm_door

- platform: attributes
  friendly_name: 'Battery'
  attribute: battery_low
  entities:
  - binary_sensor.drawer
  - binary_sensor.keypad
  - binary_sensor.front_door
  - binary_sensor.balcony_door
  - camera.motion_camera