- platform: rest
  resource: http://localhost:5557/device?ipaddr=10.0.0.49/status
  name: Xbox status
  value_template: !secret xbox_rest
  verify_ssl: false
  scan_interval: 5

- platform: rest
  resource: !secret hue_rest
  name: Hue bridge
  value_template: "{{ value_json['swupdate2']['bridge']['state'] }}"
  json_attributes:
  - name
  - zigbeechannel
  - ipaddress
  - modelid
  - swversion
  - apiversion
  scan_interval: 1800

- platform: rest
  resource: !secret abode_rest
  name: Abode
  value_template: "{{ value_json['updates']['em_ver'] }}"
  scan_interval: 43200