- platform: template
  sensors:
    all_speakers:
      friendly_name: All speakers
      value_template: >
        {% set state = ['playing', 'paused', 'idle'] %}
        {% set speakers = [
          states('media_player.bedroom_speaker') in values,
          states('media_player.living_room_speaker') in values,
          states('media_player.kitchen_speaker') in values, 
          states('media_player.hub') in values
          ] %}
        {{ (speakers | sum == speakers | count) or states('media_player.all_speakers') in state }}

    front_speakers:
      friendly_name: Front speakers
      value_template: >
        {% set state = ['playing', 'paused', 'idle'] %}
        {% set speakers = [
          states('media_player.kitchen_speaker') in values, 
          states('media_player.hub') in values
          ] %}
        {{ (speakers | sum == speakers | count) or states('media_player.front_speakers') in state }}

    any_speaker:
      friendly_name: Any speaker
      value_template: >
        {% set rejects = ['off', 'unavailable'] %}
        {% set speakers = [
          states('media_player.bedroom_speaker') not in rejects, 
          states('media_player.living_room_speaker') not in rejects, 
          states('media_player.kitchen_speaker') not in rejects,
          states('media_player.hub') not in rejects,
          states('media_player.office_speaker') not in rejects
          ] %}
        {{ speakers | sum > 0 }}

    any_tv:
      friendly_name: Any TV
      value_template: >
        {% set rejects = ['off', 'unavailable'] %}
        {% set tvs = [
          states('media_player.bedroom_tv') not in rejects, 
          states('media_player.living_room_vizio') not in rejects 
          ] %}
        {{ tvs | sum > 0 }}

    # xbox:
    #   friendly_name: Xbox
    #   value_template: "{{ states('sensor.server_ups_load') | int > 30 }}"


- platform: trend
  sensors:
    dewpoint_inside:
      friendly_name: Indoor dewpoint trend
      entity_id: sensor.dewpoint_inside
      sample_duration: 1800
      max_samples: 60
      min_gradient: 0.005   # dew point increasing at least 3 degrees in a 10-minute period

- platform: mqtt
  name: "Hall bath motion"
  state_topic: "hall_bath_motion/state"
  availability_topic: "tele/hall_bath_night_light/LWT"
  qos: 1
  payload_on: "1"
  payload_off: "0"
  payload_available: "Online"
  payload_not_available: "Offline"
  device_class: motion