- platform: template
  sensors:
    all_speakers:
      friendly_name: All speakers
      value_template: >
        {% set bedroom = states('media_player.bedroom_speaker') %}
        {% set living = states('media_player.living_room_speaker') %}
        {% set kitchen = states('media_player.kitchen_speaker') %}
        {% set hub = states('media_player.hub') %}
        {{ (bedroom in ['playing', 'paused', 'idle'] and living in ['playing', 'paused', 'idle'] and kitchen in ['playing', 'paused', 'idle'] and hub in ['playing', 'paused', 'idle']) }}

    front_speakers:
      friendly_name: Front speakers
      value_template: >
        {% set kitchen = states('media_player.kitchen_speaker') %}
        {% set hub = states('media_player.hub') %}
        {{ kitchen in ['playing', 'paused', 'idle'] and hub in ['playing', 'paused', 'idle'] }}

    any_speaker:
      friendly_name: Any speaker
      value_template: >
        {% set bedroom = states('media_player.bedroom_speaker') %}
        {% set living = states('media_player.living_room_speaker') %}
        {% set kitchen = states('media_player.kitchen_speaker') %}
        {% set hub = states('media_player.hub') %}
        {% set portable = states('media_player.portable_speaker') %}
        {{ bedroom != 'off' or living != 'off' or kitchen != 'off' or hub != 'off' or portable != 'off' }}

    any_tv:
      friendly_name: Any TV
      value_template: >
        {% set bedroom_tv = states('media_player.bedroom_vizio') %}
        {% set living_tv = states('media_player.living_room_vizio') %}
        {{ bedroom_tv != 'off' or living_tv != 'off' }}

    xbox:
      friendly_name: Xbox
      value_template: "{{ is_state('sensor.xbox_status', 'Available') }}"


- platform: ping
  host: 8.8.8.8
  count: 4
  name: Internet
  scan_interval: 20

- platform: tod
  name: Quiet hours
  after: '23:00'
  before: '08:00'

- platform: apcupsd
- platform: wyzesense
  device: auto