- platform: template
  sensors:
    any_speaker:
      friendly_name: Any speaker
      value_template: >
        {% set rejects = ['off', 'unavailable'] %}
        {% set speakers = [
          states('media_player.bedroom_speaker') not in rejects, 
          states('media_player.living_room_speaker') not in rejects, 
          states('media_player.kitchen_speaker') not in rejects,
          states('media_player.craft_room_speaker') not in rejects,
          states('media_player.office_speaker') not in rejects,
          states('media_player.guest_bedroom_clock') not in rejects
          ] %}
        {{ speakers | sum > 0 }}

    any_tv:
      friendly_name: Any TV
      value_template: >
        {% set rejects = ['off', 'unavailable'] %}
        {% set tvs = [
          states('media_player.craft_room_tv') not in rejects,
          states('media_player.bedroom_tv') not in rejects, 
          states('media_player.living_room_vizio') not in rejects 
          ] %}
        {{ tvs | sum > 0 }}

    workday:
      value_template: >
        {{
          (((as_timestamp(now()) | timestamp_custom('%d') | int(0) == as_timestamp(state_attr('calendar.andy_work', 'start_time')) | timestamp_custom('%d') | int(0)) )) 
        or 
          (((as_timestamp(now()) | timestamp_custom('%d') | int(0) == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') | int(0) ))) 
        }}