- platform: template
  sensors:
    all_speakers:
      friendly_name: All speakers
      value_template: >
        {% set state = ['playing', 'paused', 'idle'] %}
        {% set speakers = [
          states('media_player.bedroom_speaker') in values,
          states('media_player.living_room_speaker') in values,
          states('media_player.laundry_room_speaker') in values, 
          states('media_player.hub') in values
          ] %}
        {{ (speakers | sum == speakers | count) or states('media_player.all_speakers') in state }}

    front_speakers:
      friendly_name: Front speakers
      value_template: >
        {% set state = ['playing', 'paused', 'idle'] %}
        {% set speakers = [
          states('media_player.kitchen_speaker') in values, 
          states('media_player.hub') in values
          ] %}
        {{ (speakers | sum == speakers | count) or states('media_player.front_speakers') in state }}

    any_speaker:
      friendly_name: Any speaker
      value_template: >
        {% set rejects = ['off', 'unavailable'] %}
        {% set speakers = [
          states('media_player.bedroom_speaker') not in rejects, 
          states('media_player.living_room_speaker') not in rejects, 
          states('media_player.kitchen_speaker') not in rejects,
          states('media_player.hub') not in rejects,
          states('media_player.office_speaker') not in rejects
          ] %}
        {{ speakers | sum > 0 }}

    any_tv:
      friendly_name: Any TV
      value_template: >
        {% set rejects = ['off', 'unavailable'] %}
        {% set tvs = [
          states('media_player.bedroom_tv') not in rejects, 
          states('media_player.living_room_vizio') not in rejects 
          ] %}
        {{ tvs | sum > 0 }}

    workday:
      value_template: >
        {{
          (((as_timestamp(now()) | timestamp_custom('%d') | int(0) == as_timestamp(state_attr('calendar.andy_work', 'start_time')) | timestamp_custom('%d') | int(0)) )) 
        or 
          (((as_timestamp(now()) | timestamp_custom('%d') | int(0) == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') | int(0) ))) 
        }}


- platform: trend
  sensors:
    inside_dew_point:
      friendly_name: Indoor dewpoint trend
      entity_id: sensor.inside_dew_point
      sample_duration: 1800
      max_samples: 60
      min_gradient: 0.005   # dew point increasing at least 3 degrees in a 10-minute period