- platform: mqtt
  name: Dining room
  state_topic: "stat/dining_room_light/POWER1"
  command_topic: "cmnd/dining_room_light/EVENT"
  availability_topic: "tele/dining_room_light/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"