binary_sensor:
- name: Weather station battery low
  state_topic: &weather_station_topic "rtl_433/1291/event"
  value_template: "{{ value_json.battery_ok }}"
  payload_on: "0"
  payload_off: "1"
  device_class: battery

sensor:
### 433 MHz sensors
- name: Basement fridge temp
  state_topic: &fridge_topic "rtl_433/107/event"
  value_template: &433_temp_c_to_f "{{ '{:.1f}'.format((value_json.temperature_C | float(0) * 9/5) + 32) }}"
  device_class: temperature
  json_attributes_topic: *fridge_topic
  force_update: true
  expire_after: &433-expiration 1200
  unit_of_measurement: '°F'

- name: Main fridge temp
  state_topic: &freezer_topic "rtl_433/72/event"
  value_template: *433_temp_c_to_f
  device_class: temperature
  json_attributes_topic: *freezer_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°F'

- name: Attic temp
  state_topic: &attic_temp_topic "rtl_433/5801/event"
  value_template: *433_temp_c_to_f
  device_class: temperature
  json_attributes_topic: *attic_temp_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°F'

- name: Attic humidity
  state_topic: &attic_hum_topic "rtl_433/5801/event"
  value_template: "{{ '{:.0f}'.format(value_json.humidity) }}"
  device_class: temperature
  json_attributes_topic: *attic_hum_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '%'

- name: Outside temp
  state_topic: *weather_station_topic
  value_template: "{{ '{:.1f}'.format(value_json.temperature_F) }}"
  device_class: temperature
  json_attributes_topic: *weather_station_topic
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°F'

- name: Outside humidity
  state_topic: *weather_station_topic
  value_template: "{{ '{:.0f}'.format(value_json.humidity) }}"
  device_class: humidity
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '%'

- name: Wind speed
  state_topic: *weather_station_topic
  value_template: "{{ '{:.2f}'.format(value_json.wind_avg_km_h | float(0) / 1.609) }}"
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: 'mph'

- name: Wind direction degrees
  state_topic: *weather_station_topic
  value_template: "{{ '{:.0f}'.format(value_json.wind_dir_deg) }}"
  force_update: true
  expire_after: *433-expiration
  unit_of_measurement: '°'


### Other
- name: SSD temp
  state_topic: "server_drives/ssd/temp"
  unit_of_measurement: 'C'

- name: HDD temp
  state_topic: "server_drives/hdd/temp"
  unit_of_measurement: 'C'

- name: Server CPU temp
  state_topic: "temp2mqtt/server/cpu_temp"
  value_template: "{{ value_json.cpu_temp }}"
  unit_of_measurement: 'C'
  device_class: temperature

- name: LR IR received
  state_topic: 'living_room/ir_received'

- name: Cell modem signal
  state_topic: &sms_topic 'sms2mqtt/signal'
  value_template: "{{ value_json['SignalPercent'] }}"
  json_attributes_topic: *sms_topic
  unit_of_measurement: '%'