- platform: rest
  name: Gotify
  resource: !secret gotify_url
  method: POST_JSON
  headers:
    X-Gotify-Key: &gotify_key !secret gotify_key
  message_param_name: message
  title_param_name: title
  data:
    priority: 5

- platform: rest
  name: Gotify high
  resource: !secret gotify_url
  method: POST_JSON
  headers:
    X-Gotify-Key: *gotify_key
  message_param_name: message
  title_param_name: title
  data:
    priority: 10
    extras:
      client::notification:
        bigImageUrl:
          url: "{{ img_url }}"