- platform: broadlink
  name: Living room
  host: !secret lr_ir_blaster
  mac: !secret broadlink_1_mac
  type: rm_mini
  timeout: 60

- platform: broadlink
  name: Game room
  host: !secret gr_ir_blaster
  mac: !secret broadlink_2_mac
  type: rm4c_mini
  timeout: 60