- platform: time_date
  display_options:
  - date
  - time
  - date_time_iso

- platform: template
  sensors:
    time_am_pm:
      friendly_name: Time
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%I:%M %p') }}"