- platform: time_date
  display_options:
  - date
  - time
  - date_time_iso

- platform: statistics
  name: Average voltage
  entity_id: sensor.ups_input_voltage
  state_characteristic: average_linear
  max_age:
    hours: 168
  sampling_size: 10000