- platform: command_line
  switches:
    laundry_room_motion_sensor:
      command_on: !secret hue_motion_on
      command_off: !secret hue_motion_off
      command_state: !secret hue_motion_state
      value_template: "{{ value_json.config.on }}"
      friendly_name: Laundry room motion sensor status