- platform: rest
  name: Hue dark inside
  resource: !secret hue_dark_inside
  state_resource: !secret hue_dark_inside_state
  method: put
  body_on: '{"flag":true}'
  body_off: '{"flag":false}'
  is_on_template: "{{ value_json.state.flag == true }}"