- alias: Notify when away mode activated
  initial_state: 'on'
  trigger:
  - entity_id: alarm_control_panel.abode
    platform: state
    to: armed_away
    for: '00:00:05'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.tstat_comfort_setting
      state: 'Away'
    - condition: state
      entity_id: climate.thermostat
      state: 'off'
  - condition: state
    entity_id: group.lights_interior
    state: 'off'
  action:
    service: notify.mobile_app_pixel_xl
    data_template:
      title: Away mode activated
      message: >
        {% set comfort = states('sensor.tstat_comfort_setting') %}
        {% set tstat = states('climate.thermostat') %}
        {% if tstat == 'off' %}
          Lights are off, thermostat is off.
        {% elif comfort == 'Away' %}
          Lights are off, thermostat is set to away.
        {% else %}
          Uhh... this shouldn't be possible.
        {% endif %}