# Yes, this automation works. Stop testing it.
- alias: Notify when sensor battery low
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.button_1_battery
    - sensor.button_2_battery
    - sensor.lumi_weather_1_battery
    - sensor.lumi_weather_2_battery
    - sensor.water_sensor_1_battery
    - sensor.water_sensor_2_battery
    - sensor.water_sensor_3_battery
    - sensor.water_sensor_4_battery
    - sensor.zcombo_1_battery_level
    - sensor.dining_room_remote_battery
    - sensor.game_room_remote_battery
    - sensor.living_room_remote_battery
    - sensor.master_bedroom_remote_battery
    - sensor.motion_sensor_motion_battery_level
    - sensor.motion_sensor_1_battery_level
    - sensor.front_closet_battery_level
    - sensor.storm_door_battery_level
    below: 21
    for: '01:00:00'
  - platform: state
    entity_id:
    - sensor.drawer_battery_low
    - sensor.keypad_battery_low
    - sensor.front_door_battery_low
    - sensor.balcony_door_battery_low
    - sensor.motion_camera_battery_low
    to: 'True'
    for: '01:00:00'
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Device battery low"
      message: "{{ trigger.to_state.name }} battery is low."