- alias: Notify when Zigbee device unavailable
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.button_1
    - binary_sensor.button_2
    - binary_sensor.water_sensor_1
    - binary_sensor.water_sensor_2
    - binary_sensor.water_sensor_3
    - binary_sensor.water_sensor_4
    - sensor.lumi_temp_1
    - sensor.lumi_temp_2
    to: 'unavailable'
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Device unavailable"
      message: "{{ trigger.to_state.name }} is unavailable"


- alias: Notify when switch unavailable
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - switch.washer_plug
    - switch.tuya_plug_2
    - switch.plug_1
    - switch.plug_2
    - switch.plug_3
    - switch.plug_4
    - switch.light_switch1
    to: 'unavailable'
    for: '00:10:00'
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Device unavailable"
      message: "{{ trigger.to_state.name }} is unavailable"


- alias: Notify when black ink is low
  trigger:
  - platform: numeric_state
    entity_id: sensor.printer_black_ink
    below: 25
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Printer black ink low"
      message: "Black ink is at {{ states('sensor.printer_black_ink') }}%."


- alias: Notify when color ink is low
  trigger:
  - platform: numeric_state
    entity_id: sensor.printer_cyan_magenta_yellow_ink
    below: 25
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Printer color ink low"
      message: "Color ink is at {{ states('sensor.printer_cyan_magenta_yellow_ink') }}%."


- alias: Notify when Hue bridge is ready to update
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    from: 'noupdates'
    to: 'readytoinstall'
  action:
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Hue bridge update available"
      message: "Please see Hue app for details."


- alias: Notify if space heater turned on when away
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.plug_4
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Space heater warning"
      message: "Space heater has been turned on."