- alias: Notify when water leak detected
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: 
    - binary_sensor.water_sensor_1
    - binary_sensor.water_sensor_2
    from: 'off'
    to: 'on'
  action:
  - service: notify.telegram
    data_template:
      message: "LEAK DETECTED BY {{ trigger.to_state.name }}!"
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "LEAK DETECTED!"
      message: "Leak detected by {{ trigger.to_state.name }}!"


- alias: Notify when water leak cleared
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: 
    - binary_sensor.water_sensor_1
    - binary_sensor.water_sensor_2
    from: 'on'
    to: 'off'
  action:
  - service: notify.telegram
    data_template:
      message: "{{ trigger.to_state.name }} cleared"
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Leak no longer detected"
      message: "{{ trigger.to_state.name }} cleared"


- alias: Notify when smoke or CO detected
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.zcombo_1_status
    to: 'Smoke'
  - platform: state
    entity_id: sensor.zcombo_1_status
    to: 'CO'
  condition:
    condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
  - service: notify.telegram
    data_template:
      message: "{{ trigger.to_state.state }} detected!"
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "{{ trigger.to_state.state }} warning"
      message: "{{ trigger.to_state.state }} detected!"


- alias: Notify when smoke or CO cleared
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.zcombo_1_status
    from: 'Smoke'
    to: 'OK'
  - platform: state
    entity_id: sensor.zcombo_1_status
    from: 'CO'
    to: 'OK'
  condition:
    condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
  - service: notify.telegram
    data_template:
      message: "{{ trigger.from_state.state }} no longer detected."
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "{{ trigger.from_state.state }} cleared"
      message: "{{ trigger.from_state.state }} no longer detected."