- alias: Notify lights on when away
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - light.dining_room
    - light.living_room
    - light.master_bedroom
    - light.game_room
    - light.laundry_room
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
    service: notify.mobile_app_pixel_xl
    data_template:
      title: "{{ trigger.to_state.name }} lights have been turned on."


- alias: Notify entrance light on when away
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.light_switch1
    from: 'off'
    to: 'on'
    for: '00:00:45'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
    service: notify.mobile_app_pixel_xl
    data:
      title: "Entrance light has been turned on."


- alias: Notify lights off when away
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.lights_interior
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
    for: '00:01:00'
  action:
    service: notify.mobile_app_pixel_xl
    data:
      title: "Lights have been turned off."


- alias: Notify when storm door opened
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.storm_door
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: 'armed_away'
    - condition: state
      entity_id: alarm_control_panel.abode
      state: 'armed_home'
  action:
    service: notify.mobile_app_pixel_xl
    data:
      title: "Storm door has been opened!"


- alias: Notify when storm door closed
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.storm_door
    from: 'on'
    to: 'off'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.abode
      state: 'armed_away'
    - condition: state
      entity_id: alarm_control_panel.abode
      state: 'armed_home'
  action:
    service: notify.mobile_app_pixel_xl
    data:
      title: "Storm door has been closed."


- alias: Notify when alarm not armed when away
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: device_tracker.pixel_xl
    to: 'not_home'
    for: '00:02:00'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: 'disarmed'
  action:
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Security system not armed"
      message: "You forgot to arm the alarm, dumbass."