automation:
- alias: Set speaker volume based on app
  id: 'rai2eifeijahvaeFeev7to'
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - sensor.kitchen_speaker_app_name
    - sensor.office_speaker_app_name
  condition:
  - "{{ trigger.to_state.state not in ['', 'unknown'] }}"
  - "{{ not ('main_bedroom' in trigger.to_state.object_id and is_state('input_boolean.white_noise', 'on')) }}"
  action:
  - wait_template: "{{ state_attr('media_player.' + trigger.to_state.object_id.replace('_app_name',''), 'media_album_name') != None }}"
    timeout: '00:00:03'
    continue_on_timeout: true
  - service: media_player.volume_set
    data:
      entity_id: "media_player.{{ trigger.to_state.object_id.replace('_app_name','') }}"
      volume_level: >
        {% set app = trigger.to_state.state %}
        {% set speaker = trigger.to_state.object_id.replace('_speaker_app_name','').replace('_',' ') %}
        {% set album = state_attr('media_player.' + trigger.to_state.object_id.replace('_app_name',''), 'media_album_name') %}
        {% if app in ['iHeartRadio', 'Audacy', 'Default Media Receiver'] %}
          {% if speaker in ['living room'] %}
            {{ 0.38 if album == '103.5 KISS FM' else 0.45 }}
          {% elif speaker in ['office', 'guest bedroom', 'bedroom'] %}
            {{ 0.28 if album == '103.5 KISS FM' else 0.36 }}
          {% else %}
            0.3
          {% endif %}
        {% elif app in ['Google Play Music', 'Spotify', 'YouTube Music'] %}
          {% if speaker in ['living room', 'office'] %}
            0.45
          {% elif speaker in ['kitchen', 'bedroom'] %}
            0.4
          {% else %}
            0.32
          {% endif %}
        {% else %}
          0.3
        {% endif %}


sensor:
- platform: attributes
  attribute: app_name
  entities: &media_players
  - media_player.kitchen_speaker
  - media_player.office_speaker

- platform: attributes
  attribute: media_album_name
  entities: *media_players