automation:
- alias: Matt button initial press
  initial_state: true
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: button_single
      device_ieee: !secret button_1_id
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service_template: "{{ 'script.good_night' if is_state('input_boolean.andy_sleep', 'off') else 'script.good_night_no_noise' }}"


- alias: Matt button toggle fan
  initial_state: true
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: button_single
      device_ieee: !secret button_1_id
  condition:
  - condition: state
    entity_id: media_player.bedroom_speaker
    state: 'playing'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  action:
  - service: switch.toggle
    entity_id: switch.plug_1


- alias: Matt button white noise only
  initial_state: true
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: button_single
      device_ieee: !secret button_1_id
  condition:
  - condition: template
    value_template: "{{ states('media_player.bedroom_speaker') in ['off', 'idle'] }}"
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  action:
  - service: script.white_noise_bedroom


- alias: Lights off backup attempt
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.sleep_mode
    to: 'on'
    for: '00:00:05'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.lights_interior
      state: 'on'
    - condition: state
      entity_id: switch.plug_2
      state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: 
    - group.lights_interior
    - switch.plug_2


script:
  good_night:
    alias: Good night
    sequence:
    - service: homeassistant.turn_off
      entity_id:
      - media_player.bedroom_vizio
      - group.lights_interior
    - service: script.sleep_switches
    - service: script.white_noise_bedroom
    - service: homeassistant.turn_off
      entity_id:
      - switch.tuya_plug_2
      - input_boolean.washer
      - input_boolean.dryer
      - media_player.living_room_vizio
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.abode

  good_night_no_noise:
    alias: Good night routine - no white noise
    sequence:
    - service: homeassistant.turn_off
      entity_id: 
      - media_player.bedroom_vizio
      - group.lights_interior
      - switch.tuya_plug_2
      - media_player.living_room_vizio
    - service: script.sleep_switches
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.abode

  white_noise_bedroom:
    alias: Play white noise on bedroom speaker
    sequence:
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: yes
    - service: media_player.play_media
      entity_id: media_player.bedroom_speaker
      data:
        media_content_id: !secret white_noise
        media_content_type: audio/mp3
    - delay: '00:00:01'
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: no
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data_template:
        volume_level: "{{ states('input_number.white_noise_vol') | int / 100 }}"

  sleep_switches:
    sequence:
    - service: switch.turn_off
      entity_id: switch.plug_2
    - service: switch.turn_on
      entity_id: switch.plug_1


input_number:
  white_noise_vol:
    name: White noise volume
    min: 40
    max: 80
    step: 2
    unit_of_measurement: '%'
    mode: slider


input_boolean:
  sleep_mode: