- alias: Suggest opening the windows #throttled
  initial_state: true
  trigger:
    platform: template
    value_template: "{{ (states('sensor.tstat_current_temp') | float - states('sensor.outside_temp') | float) >= 10 }}"
  condition:
  - condition: state
    entity_id: climate.thermostat
    state: 'cool'
  - condition: numeric_state
    entity_id: sensor.outside_dewpoint
    below: 58
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service: automation.turn_off
    entity_id: automation.suggest_opening_the_windows
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Consider opening the windows"
      message: "It's {{ states('sensor.tstat_current_temp') | float | round(0) }}° inside and only {{ states('sensor.outside_temp') | float | round(0) }}° outside."
      data:
        ttl: 0
        priority: high


- alias: Notify when humidity high #throttled
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.tstat_current_humidity
    above: 65
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service: automation.turn_off
    entity_id: automation.notify_when_humidity_high
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Humidity warning"
      message: "Humidity is currently {{ states('sensor.tstat_current_humidity') | float | round(0) }}%."
      data:
        ttl: 0
        priority: high