- alias: Notify when device unavailable
  id: 'Magah7iediTii3Bi'
  initial_state: true
  mode: parallel
  max: 100
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.back_door
    - binary_sensor.basement_door
    - binary_sensor.basement_fridge_door
    - binary_sensor.bathroom_ejector_closet_door
    - binary_sensor.front_door
    - binary_sensor.garage_service_door
    - binary_sensor.laundry_room_door_back
    - binary_sensor.laundry_room_door_front
    - binary_sensor.patio_door
    - binary_sensor.side_door

    - binary_sensor.guest_bedroom_window
    - binary_sensor.kitchen_window
    - binary_sensor.living_room_window_left
    - binary_sensor.living_room_window_right
    - binary_sensor.master_bedroom_window_left
    - binary_sensor.master_bedroom_window_right
    - binary_sensor.second_bedroom_window

    - binary_sensor.basement_motion
    - binary_sensor.deck_motion
    - binary_sensor.dining_room_motion
    - binary_sensor.hall_motion
    - binary_sensor.laundry_room_motion_front
    - binary_sensor.laundry_room_motion_back
    - binary_sensor.living_room_motion

    - binary_sensor.bar_leak
    - binary_sensor.basement_bathroom_leak
    - binary_sensor.water_main_leak
    - binary_sensor.dishwasher_leak
    - binary_sensor.fridge_leak
    - binary_sensor.water_heater_leak
    - binary_sensor.kitchen_sink_leak
    - binary_sensor.hall_bath_sink_leak
    - binary_sensor.hall_bath_toilet_leak
    - binary_sensor.kitchen_leak
    - binary_sensor.master_bath_sink_leak
    - binary_sensor.master_bath_toilet_leak
    - binary_sensor.sump_pump_leak
    - binary_sensor.washer_sink_leak

    - sensor.master_bedroom_temp
    - sensor.outdoor_light_level
    - light.kitchen_cabinets
    to: 'unavailable'
    for: '00:01:00'
  - platform: state
    entity_id: 
    - light.porch
    - light.entrance
    - binary_sensor.coffeemaker_status
    - light.dining_room
    - light.game_room_closet
    to: 'unavailable'
    for: '00:10:00'
  - platform: numeric_state
    entity_id: sensor.cell_modem_signal
    above: -1
  action:
  - service: notify.mobile_app_matt_phone
    data_template:
      title: "Device unavailable"
      message: "{{ trigger.to_state.name }} is unavailable"
      data:
        ttl: 0
        priority: high


- alias: Notify when Zigbee router unavailable for 5 minutes
  id: 'EphooCiob0oofaYo'
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - switch.air_freshener
    - switch.basement_fridge_plug
    - switch.bathroom_ejector_closet
    - switch.garage_lights
    - switch.guest_bedroom_plug
    - switch.master_bedroom_plug
    - sensor.siren_battery
    to: 'unavailable'
    for: '00:05:00'
  action:
  - service: notify.gotify_high
    data:
      title: &router_title Zigbee router warning
      message: &router_message "{{ trigger.to_state.name }} has been unavailable for 5 minutes."
  - service: persistent_notification.create
    data:
      title: *router_title
      message: *router_message


- alias: Notify when sensor battery low
  id: 'roo8eoBo2Meemi2s'
  initial_state: true
  mode: parallel
  max: 100
  trigger:

# {% for state in states.sensor if 'battery' in state.entity_id and 'phone' not in state.entity_id and 'low' not in state.entity_id and 'ups' not in state.entity_id and 'hk' not in state.entity_id %}
# - {{ state.entity_id -}}
# {% endfor %}
  - platform: numeric_state
    entity_id:
    - sensor.andy_s_button_battery
    - sensor.bar_leak_sensor_battery
    - sensor.bar_lights_remote_battery
    - sensor.basement_bathroom_sink_leak_sensor_battery
    - sensor.basement_bathroom_toilet_leak_sensor_battery
    - sensor.basement_door_battery
    - sensor.basement_lamp_button_battery
    - sensor.basement_temp_sensor_battery
    - sensor.craft_room_desk_button_battery
    - sensor.craft_room_desk_remote_battery
    - sensor.dishwasher_leak_sensor_battery
    - sensor.fridge_leak_sensor_battery
    - sensor.front_door_battery
    - sensor.front_door_keypad_battery
    - sensor.front_porch_door_battery
    - sensor.garage_motion_sensor_battery
    - sensor.garage_service_door_battery
    - sensor.guest_bedroom_window_battery
    - sensor.hall_bath_sink_leak_sensor_battery
    - sensor.hall_bath_toilet_leak_sensor_battery
    - sensor.hallway_motion_sensor_battery
    - sensor.hvac_leak_sensor_battery
    - sensor.kitchen_sink_leak_sensor_battery
    - sensor.kitchen_window_battery
    - sensor.laundry_room_door_front_battery
    - sensor.laundry_room_lights_button_battery
    - sensor.laundry_room_motion_sensor_battery
    - sensor.laundry_room_temp_sensor_battery
    - sensor.living_room_lamp_button_battery
    - sensor.living_room_remote_battery_level
    - sensor.living_room_window_left_battery
    - sensor.living_room_window_right_battery
    - sensor.master_bath_sink_leak_sensor_battery
    - sensor.master_bath_toilet_leak_sensor_battery
    - sensor.master_bedroom_remote_battery_level
    - sensor.master_bedroom_temp_sensor_battery
    - sensor.master_bedroom_window_left_battery
    - sensor.master_bedroom_window_right_battery
    - sensor.matt_s_button_battery
    - sensor.office_desk_button_battery
    - sensor.office_desk_remote_battery
    - sensor.office_temp_sensor_battery
    - sensor.outdoor_light_sensor_battery
    - sensor.second_bedroom_window_battery
    - sensor.server_battery
    - sensor.side_door_battery
    - sensor.side_door_keypad_battery
    - sensor.siren_battery
    - sensor.soldering_station_remote_battery
    - sensor.sump_pump_leak_sensor_battery
    - sensor.washer_sink_leak_sensor_battery
    - sensor.water_heater_leak_sensor_battery
    - sensor.water_main_leak_sensor_battery
    below: 21
    for: '08:00:00'

# {% for state in states.binary_sensor if 'battery' in state.entity_id %}
# - {{ state.entity_id -}}
# {% endfor %}
  - platform: state
    entity_id:
    - binary_sensor.back_door_battery_low
    - binary_sensor.bar_leak_sensor_battery_low
    - binary_sensor.basement_bathroom_sink_leak_sensor_battery_low
    - binary_sensor.basement_bathroom_toilet_leak_sensor_battery_low
    - binary_sensor.basement_door_battery_low
    - binary_sensor.basement_fridge_door_battery_low
    - binary_sensor.basement_lamp_button_battery_low
    - binary_sensor.basement_motion_sensor_battery_low
    - binary_sensor.bathroom_ejector_closet_door_battery_low
    - binary_sensor.craft_room_desk_button_battery_low
    - binary_sensor.dining_room_motion_sensor_battery_low
    - binary_sensor.dishwasher_leak_sensor_battery_low
    - binary_sensor.fridge_leak_sensor_battery_low
    - binary_sensor.front_door_battery_low
    - binary_sensor.front_door_keypad_battery_low
    - binary_sensor.front_porch_door_battery_low
    - binary_sensor.front_storm_door_battery_low
    - binary_sensor.garage_service_door_battery_low
    - binary_sensor.guest_bedroom_window_battery_low
    - binary_sensor.hall_bath_sink_leak_sensor_battery_low
    - binary_sensor.hall_bath_toilet_leak_sensor_battery_low
    - binary_sensor.hallway_motion_sensor_battery_low
    - binary_sensor.hvac_leak_sensor_battery_low
    - binary_sensor.kitchen_motion_sensor_battery_low
    - binary_sensor.kitchen_sink_leak_sensor_battery_low
    - binary_sensor.kitchen_window_battery_low
    - binary_sensor.laundry_room_door_back_battery_low
    - binary_sensor.laundry_room_door_front_battery_low
    - binary_sensor.laundry_room_lights_button_battery_low
    - binary_sensor.living_room_lamp_button_battery_low
    - binary_sensor.living_room_motion_battery_low
    - binary_sensor.living_room_window_left_battery_low
    - binary_sensor.living_room_window_right_battery_low
    - binary_sensor.master_bath_sink_leak_sensor_battery_low
    - binary_sensor.master_bath_toilet_leak_sensor_battery_low
    - binary_sensor.master_bedroom_window_left_battery_low
    - binary_sensor.master_bedroom_window_right_battery_low
    - binary_sensor.office_closet_door_left_battery_low
    - binary_sensor.office_closet_door_right_battery_low
    - binary_sensor.office_desk_button_battery_low
    - binary_sensor.second_bedroom_window_battery_low
    - binary_sensor.side_door_battery_low
    - binary_sensor.side_door_keypad_battery_low
    - binary_sensor.side_storm_door_battery_low
    - binary_sensor.storage_motion_sensor_battery_low
    - binary_sensor.sump_pump_leak_sensor_battery_low
    - binary_sensor.utility_sink_motion_sensor_battery_low
    - binary_sensor.washer_sink_leak_sensor_battery_low
    - binary_sensor.water_heater_leak_sensor_battery_low
    - binary_sensor.water_main_leak_sensor_battery_low
    - binary_sensor.weather_station_battery_low
    to: 'on'
  # condition:
  # - condition: template
  #   value_template: "{{ trigger.to_state.state != '' }}"
  action:
  - service: notify.gotify_high
    data_template:
      title: &batt_low_title Device battery low
      message: &batt_low_msg "{{ trigger.to_state.name.replace('battery low', '').replace('battery', '') }} battery is low."
      data:
        ttl: 0
        priority: high
  - service: persistent_notification.create
    data:
      title: *batt_low_title
      message: *batt_low_msg


- alias: Notify when fridge temp too high
  id: 'zasuuwohtieN4Wei'
  initial_state: true
  mode: parallel
  trigger:
  - platform: numeric_state
    entity_id: 
    - sensor.main_fridge_temp
    - sensor.basement_fridge_temp
    above: 45
    for: '02:00:00'
  action:
  - service: notify.mobile_app_matt_phone
    data:
      title: &fridge_title "{{ trigger.to_state.name }} is too high"
      message: &fridge_msg Fridge has been above 45° for more than two hours.
      data:
        ttl: 0
        priority: high
  - service: notify.gotify_high
    data:
      title: *fridge_title
      message: *fridge_msg
  - delay: 10
  - condition: state
    entity_id: input_boolean.fridge_temp_ack
    state: 'off'
  - service: script.sms_send
    data_template:
      number: !secret phone_matt
      message: *fridge_title


- alias: Notify when 433MHz temp sensor battery low
  id: 'idi6ahyahRupheir'
  initial_state: true
  mode: parallel
  max: 10
  trigger:
  - platform: template
    value_template: "{{ is_state_attr('sensor.main_fridge_temp', 'battery_ok', 0) }}"
  - platform: template
    value_template: "{{ is_state_attr('sensor.basement_fridge_temp', 'battery_ok', 0) }}"
  - platform: template
    value_template: "{{ is_state_attr('sensor.attic_temp', 'battery_ok', 0) }}"
  action:
  - service: notify.mobile_app_matt_phone
    data:
      title: &fridge_batt_title "{{ trigger.to_state.name }} sensor battery low"
      message: &fridge_batt_msg Change the temp sensor battery now.
      data:
        ttl: 0
        priority: high
  - service: notify.gotify_high
    data:
      title: *fridge_batt_title
      message: *fridge_batt_msg


- alias: Notify when basement fridge open more than 5 minutes
  id: 'ieFeih9taingievo'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_fridge
    to: 'on'
    for: '00:05:00'
  action:
  - service: notify.gotify_high
    data:
      title: "Basement fridge door has been open for 5 minutes"
      message: "Did you forget to close it?"