- alias: Notify when device unavailable
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    to: 'unavailable'
    for: '00:00:45'
  - platform: state
    entity_id:
    - binary_sensor.button_matt
    - binary_sensor.button_andy
    - binary_sensor.laundry_room_leak
    - binary_sensor.kitchen_leak
    - binary_sensor.hall_bath_toilet_leak
    - binary_sensor.master_bath_toilet_leak
    - binary_sensor.hall_bath_sink_leak
    - binary_sensor.master_bath_sink_leak
    - binary_sensor.entrance_motion
    - sensor.kitchen_light_level
    - sensor.game_room_light_level
    - sensor.master_bedroom_temp
    - sensor.game_room_temp
    - switch.air_freshener
    - switch.master_bedroom_fan_plug
    - light.kitchen_cabinets
    - switch.game_room_bias_lighting
    - light.front_closet
    to: 'unavailable'
    for: '00:00:10'
  - platform: state
    entity_id: 
    - light.porch
    - light.entrance
    - binary_sensor.coffeemaker_status
    - light.dining_room
    - light.game_room_closet
    to: 'unavailable'
    for: '00:10:00'
  - platform: numeric_state
    entity_id: !secret cell_modem
    above: -1
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Device unavailable"
      message: "{{ trigger.to_state.name }} is unavailable"
      data:
        ttl: 0
        priority: high


- alias: Notify when Hue light unreachable
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - light.andy
    - light.buffet
    - light.dresser
    - light.laundry_room
    - light.left_lamp
    - light.left_sconce
    - light.matt
    - light.right_lamp
    - light.right_sconce
    - light.stand_lamp
    to: 'unavailable'
    for: '00:10:00'
  condition:
  - condition: template
    value_template: "{{ not is_state('sensor.hue_bridge', 'unavailable') }}"
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Light unreachable"
      message: "{{ trigger.to_state.name }} is unreachable"
      data:
        ttl: 0
        priority: high


- alias: Notify when sensor battery low
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.button_matt_battery
    - sensor.button_andy_battery
    - sensor.dining_room_remote_battery_level
    - sensor.eco_remote_1_battery
    - sensor.front_closet_battery
    - sensor.game_room_remote_battery_level
    - sensor.hvac_closet_battery
    - sensor.laundry_room_door_battery
    - sensor.kitchen_light_level_battery
    - sensor.master_bedroom_curtains_battery
    - sensor.game_room_light_level_battery
    - sensor.living_room_fan_remote_battery
    - sensor.living_room_remote_battery_level
    - sensor.living_room_window_left_battery
    - sensor.living_room_window_right_battery
    - sensor.entrance_motion_battery
    - sensor.master_bedroom_temp_battery
    - sensor.game_room_temp_battery
    - sensor.master_bedroom_remote_battery_level
    - sensor.porch_light_remote_battery
    - sensor.storm_door_battery
    - sensor.laundry_room_leak_battery
    - sensor.kitchen_leak_battery
    - sensor.hall_bath_toilet_leak_battery
    - sensor.master_bath_toilet_leak_battery
    - sensor.hall_bath_sink_leak_battery
    - sensor.master_bath_sink_leak_battery
    - sensor.master_bedroom_motion_battery
    - sensor.smoke_alarm_battery
    below: 21
    for: '01:00:00'
  - platform: numeric_state
    entity_id:
    - binary_sensor.entrance_motion_battery
    - binary_sensor.front_closet_door_battery
    - binary_sensor.game_room_closet_door_battery
    - binary_sensor.game_room_closet_motion_battery
    - binary_sensor.hall_bath_motion_battery
    - binary_sensor.kitchen_window_left_battery
    - binary_sensor.living_room_window_left_battery
    - binary_sensor.living_room_window_right_battery
    - binary_sensor.master_bedroom_closet_motion_battery
    - binary_sensor.master_bedroom_motion_battery
    - binary_sensor.master_bedroom_window_right_battery
    below: 85
    for: '00:01:00'
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != '' }}"
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Device battery low {{ ' - URGENT!' if trigger.to_state | float > 30 else '' }}"
      message: "{{ trigger.to_state.name }} battery is low{{ '.' if trigger.to_state | float < 21 else ' - change ASAP' }}"
      data:
        ttl: 0
        priority: high


# - alias: Notify when printer ink is low
#   initial_state: true
#   trigger:
#   - platform: numeric_state
#     entity_id: 
#     - sensor.hp_photosmart_d110_series_black_ink
#     - sensor.hp_photosmart_d110_series_unknown_ink
#     below: 25
#   action:
#   - service: persistent_notification.create
#     data_template:
#       title: "{{ trigger.to_state.name }} low"
#       message: "{{ trigger.to_state.name }} is at {{ states(trigger.entity_id) }}%."


- alias: Notify when Hue bridge is ready to update
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    from: 'noupdates'
    to: 'readytoinstall'
  action:
  - service: persistent_notification.create
    data:
      title: "Hue bridge update available"
      message: "Please see Hue app for details."


- alias: Notify if space heater turned on when away
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.space_heater
    to: 'on'
  condition:
  - condition: state
    entity_id: input_text.abode
    state: 'armed_away'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - climate.space_heater
    - switch.space_heater
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Space heater warning"
      message: "Space heater has been turned on."
      data:
        ttl: 0
        priority: high