- alias: Notify when device unavailable
  initial_state: true
  mode: parallel
  max: 100
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    to: 'unavailable'
    for: '00:00:45'
  - platform: state
    entity_id:
    - binary_sensor.front_closet_door
    - binary_sensor.game_room_closet_door
    - binary_sensor.game_room_closet_motion
    - binary_sensor.game_room_window_left
    - binary_sensor.hall_bath_sink_leak
    - binary_sensor.hall_bath_toilet_leak
    - binary_sensor.hvac_closet
    - binary_sensor.kitchen_leak
    - binary_sensor.kitchen_motion
    - binary_sensor.laundry_room_door
    - binary_sensor.laundry_room_leak
    - binary_sensor.master_bath_sink_leak
    - binary_sensor.master_bath_toilet_leak
    - binary_sensor.master_bedroom_closet_motion
    - binary_sensor.master_bedroom_curtains
    - binary_sensor.master_bedroom_motion
    - binary_sensor.master_bedroom_window_left_contact
    - binary_sensor.storm_door
    - sensor.balcony_light_level
    - sensor.kitchen_light_level
    - sensor.master_bedroom_temp
    - sensor.game_room_temp
    - switch.air_freshener
    - switch.master_bedroom_fan_plug
    - light.kitchen_cabinets
    - switch.game_room_bias_lighting
    - light.front_closet
    to: 'unavailable'
    for: '00:00:10'
  - platform: state
    entity_id: 
    - light.porch
    - light.entrance
    - binary_sensor.coffeemaker_status
    - light.dining_room
    - light.game_room_closet
    to: 'unavailable'
    for: '00:10:00'
  - platform: numeric_state
    entity_id: !secret cell_modem
    above: -1
  action:
  - service: notify.mobile_app_matt_phone
    data_template:
      title: "Device unavailable"
      message: "{{ trigger.to_state.name }} is unavailable"
      data:
        ttl: 0
        priority: high


- alias: Notify when Hue light unreachable
  initial_state: true
  mode: parallel
  max: 100
  trigger:
  - platform: state
    entity_id:
    - light.andy
    - light.buffet
    - light.dresser
    - light.front_closet
    - light.laundry_room
    - light.left_lamp
    - light.left_sconce
    - light.matt
    - light.matt_desk
    - light.right_lamp
    - light.right_sconce
    - light.stand_lamp
    to: 'unavailable'
    for: '00:10:00'
  condition:
  - condition: template
    value_template: "{{ not is_state('sensor.hue_bridge', 'unavailable') }}"
  action:
  - service: notify.mobile_app_matt_phone
    data_template:
      title: "Light unreachable"
      message: "{{ trigger.to_state.name }} is unreachable"
      data:
        ttl: 0
        priority: high


- alias: Notify when sensor battery low
  initial_state: true
  mode: parallel
  max: 100
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.balcony_light_battery
    - sensor.button_andy_battery
    - sensor.button_andy_desk_battery
    - sensor.button_matt_battery
    - sensor.dining_room_remote_battery_level
    - sensor.entrance_motion_battery_level
    - sensor.game_room_desk_remote_battery
    - sensor.game_room_remote_battery_level
    - sensor.game_room_table_remote_battery
    - sensor.game_room_temp_sensor_battery
    - sensor.hall_bath_sink_leak_battery
    - sensor.hall_bath_toilet_leak_battery
    - sensor.kitchen_leak_sensor_battery
    - sensor.kitchen_light_level_battery
    - sensor.kitchen_motion_sensor_battery
    - sensor.laundry_room_leak_battery
    - sensor.living_room_remote_battery_level
    - sensor.master_bath_sink_leak_battery
    - sensor.master_bath_toilet_leak_battery
    - sensor.master_bedroom_closet_motion_battery
    - sensor.master_bedroom_motion_battery
    - sensor.master_bedroom_remote_battery_level
    - sensor.master_bedroom_temp_battery
    - sensor.porch_light_remote_battery
    - sensor.smoke_alarm_battery_level
    - sensor.game_room_fan_button_battery
    - sensor.living_room_lamp_button_battery
    - sensor.sunset_lights_button_battery
    below: 21
    for: '08:00:00'
  - platform: state
    entity_id:
    - binary_sensor.front_closet_door_battery_low
    - binary_sensor.front_door_battery_low
    - binary_sensor.game_room_closet_door_battery_low
    - binary_sensor.game_room_closet_motion_battery_low
    - binary_sensor.game_room_window_left_battery_low
    - binary_sensor.hall_bath_sink_leak_sensor_battery_low
    - binary_sensor.hall_bath_toilet_leak_sensor_battery_low
    - binary_sensor.hvac_closet_battery_low
    - binary_sensor.kitchen_leak_sensor_battery_low
    - binary_sensor.kitchen_motion_battery_low
    - binary_sensor.laundry_room_door_battery_low
    - binary_sensor.laundry_room_leak_sensor_battery_low
    - binary_sensor.master_bath_sink_leak_sensor_battery_low
    - binary_sensor.master_bath_toilet_leak_sensor_battery_low
    - binary_sensor.master_bedroom_curtains_battery_low
    - binary_sensor.master_bedroom_motion_battery_low
    - binary_sensor.master_bedroom_window_left_battery_low
    - binary_sensor.storm_door_battery_low
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != '' }}"
  action:
  - service: notify.mobile_app_matt_phone
    data_template:
      title: &batt_low_title Device battery low
      message: &batt_low_msg "{{ trigger.to_state.name }} battery is low."
      data:
        ttl: 0
        priority: high
  - service: persistent_notification.create
    data:
      title: *batt_low_title
      message: *batt_low_msg


- alias: Notify when fridge temp too high
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.fridge_temp
    above: 45
    for: '00:30:00'
  action:
  - service: notify.mobile_app_matt_phone
    data:
      title: &fridge_title Fridge temp too high
      message: &fridge_msg "Fridge temperature is currently {{ states('sensor.fridge_temp') }}"
      data:
        ttl: 0
        priority: high
  - service: notify.gotify_high
    data:
      title: *fridge_title
      message: *fridge_msg


- alias: Notify when fridge temp sensor battery low
  initial_state: true
  mode: parallel
  max: 10
  trigger:
  - platform: template
    value_template: "{{ is_state_attr('sensor.freezer_temp', 'battery_ok', 0) }}"
  - platform: template
    value_template: "{{ is_state_attr('sensor.fridge_temp', 'battery_ok', 0) }}"
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ is_state_attr('sensor.freezer_temp', 'battery_ok', 0) }}"
      sequence:
      - service: notify.mobile_app_matt_phone
        data:
          title: &freezer_batt_title Freezer temp sensor battery low
          message: &freezer_batt_msg Change the freezer temp sensor battery now.
          data:
            ttl: 0
            priority: high
      - service: notify.gotify_high
        data:
          title: *freezer_batt_title
          message: *freezer_batt_msg
    default:
      - service: notify.mobile_app_matt_phone
        data:
          title: &fridge_batt_title Fridge temp sensor battery low
          message: &fridge_batt_msg Change the fridge temp sensor battery now.
          data:
            ttl: 0
            priority: high
      - service: notify.gotify_high
        data:
          title: *fridge_batt_title
          message: *fridge_batt_msg


- alias: Notify when Hue bridge is ready to update
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    from: 'noupdates'
    to: 'readytoinstall'
  action:
  - service: persistent_notification.create
    data:
      title: "Hue bridge update available"
      message: "Please see Hue app for details."


- alias: Notify if space heater turned on when away
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.space_heater
    to: 'on'
  condition:
  - condition: state
    entity_id: input_text.alarm
    state: 'armed_away'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - climate.space_heater
    - switch.space_heater
  - service: notify.mobile_app_matt_phone
    data:
      title: "Space heater warning"
      message: "Space heater has been turned on."
      data:
        ttl: 0
        priority: high