- alias: Notify when device unavailable
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.button_1
    - binary_sensor.button_2
    - binary_sensor.water_sensor_1
    - binary_sensor.water_sensor_2
    - binary_sensor.water_sensor_3
    - binary_sensor.water_sensor_4
    - binary_sensor.lumi_motion_1
    - sensor.lumi_temp_1
    - sensor.lumi_temp_2
    - light.front_closet
    to: 'unavailable'
  - platform: state
    entity_id:
    - switch.washer_plug
    - switch.tuya_plug_2
    - switch.plug_1
    - switch.plug_2
    - switch.plug_3
    - switch.plug_4
    - switch.light_switch_1
    - light.porch_light
    to: 'unavailable'
    for: '00:01:00'
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Device unavailable"
      message: "{{ trigger.to_state.name }} is unavailable"
      data:
        ttl: 0
        priority: high


- alias: Notify when sensor battery low
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.button_1_battery
    - sensor.button_2_battery
    - sensor.lumi_weather_1_battery
    - sensor.lumi_weather_2_battery
    - sensor.lumi_motion_1_battery
    - sensor.water_sensor_1_battery
    - sensor.water_sensor_2_battery
    - sensor.water_sensor_3_battery
    - sensor.water_sensor_4_battery
    - sensor.zcombo_1_battery_level
    - sensor.dining_room_remote_battery
    - sensor.game_room_remote_battery
    - sensor.living_room_remote_battery
    - sensor.master_bedroom_remote_battery
    - sensor.motion_sensor_motion_battery_level
    - sensor.wyze_motion_1_battery_level
    - sensor.front_closet_battery_level
    - sensor.storm_door_battery_level
    below: 21
    for: '01:00:00'
  - platform: state
    entity_id:
    - sensor.drawer_battery_low
    - sensor.keypad_battery_low
    - sensor.front_door_battery_low
    - sensor.balcony_door_battery_low
    - sensor.motion_camera_battery_low
    to: 'True'
    for: '01:00:00'
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Device battery low"
      message: "{{ trigger.to_state.name }} battery is low."
      data:
        ttl: 0
        priority: high


- alias: Notify when printer ink is low
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: 
    - sensor.printer_ink_black
    - sensor.printer_ink_color
    below: 25
  action:
  - service: persistent_notification.create
    data_template:
      title: "{{ trigger.to_state.name }} low"
      message: "{{ trigger.to_state.name }} is at {{ states(trigger.entity_id) }}%."


- alias: Notify when Hue bridge is ready to update
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    from: 'noupdates'
    to: 'readytoinstall'
  action:
  - service: persistent_notification.create
    data:
      title: "Hue bridge update available"
      message: "Please see Hue app for details."


- alias: Notify if space heater turned on when away
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.plug_4
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
  - service: homeassistant.turn_off
    entity_id:
    - climate.space_heater
    - switch.plug_4
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Space heater warning"
      message: "Space heater has been turned on."
      data:
        ttl: 0
        priority: high