- alias: Notify when device unavailable
  initial_state: true
  mode: parallel
  max: 100
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    to: 'unavailable'
    for: '00:00:45'
  - platform: state
    entity_id:
    - binary_sensor.front_closet_door
    - binary_sensor.game_room_closet_door
    - binary_sensor.game_room_closet_motion
    - binary_sensor.game_room_window_left
    - binary_sensor.hall_bath_sink_leak
    - binary_sensor.hall_bath_toilet_leak
    - binary_sensor.hvac_closet
    - binary_sensor.kitchen_leak
    - binary_sensor.kitchen_motion
    - binary_sensor.laundry_room_door
    - binary_sensor.laundry_room_leak
    - binary_sensor.master_bath_sink_leak
    - binary_sensor.master_bath_toilet_leak
    - binary_sensor.master_bedroom_closet_motion
    - binary_sensor.master_bedroom_curtains
    - binary_sensor.master_bedroom_motion
    - binary_sensor.master_bedroom_window_left_contact
    - binary_sensor.storm_door
    - sensor.outdoor_light_level
    - sensor.kitchen_light_level
    - sensor.master_bedroom_temp
    - sensor.game_room_temp
    - light.kitchen_cabinets
    - light.front_closet
    to: 'unavailable'
    for: '00:00:10'
  - platform: state
    entity_id: 
    - light.porch
    - light.entrance
    - binary_sensor.coffeemaker_status
    - light.dining_room
    - light.game_room_closet
    to: 'unavailable'
    for: '00:10:00'
  - platform: numeric_state
    entity_id: !secret cell_modem
    above: -1
  action:
  - service: notify.mobile_app_matt_phone
    data_template:
      title: "Device unavailable"
      message: "{{ trigger.to_state.name }} is unavailable"
      data:
        ttl: 0
        priority: high


- alias: Notify when Zigbee router unavailable for 5 minutes
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - switch.air_freshener
    - switch.basement_fridge_plug
    - switch.bathroom_ejector_closet
    - switch.garage_lights
    - switch.guest_bedroom_plug
    - switch.master_bedroom_plug
    - sensor.siren_battery
    to: 'unavailable'
    for: '00:05:00'
  action:
  - service: notify.gotify_high
    data:
      title: &router_title Zigbee router warning
      message: &router_message "{{ trigger.to_state.name }} has been unavailable for 5 minutes."
  - service: persistent_notification.create
    data:
      title: *router_title
      message: *router_message


- alias: Notify when Hue light unreachable
  initial_state: true
  mode: parallel
  max: 100
  trigger:
  - platform: state
    entity_id:
    - light.andy
    - light.buffet
    - light.dresser
    - light.front_closet
    - light.laundry_room
    - light.left_lamp
    - light.left_sconce
    - light.matt
    - light.matt_desk
    - light.right_lamp
    - light.right_sconce
    - light.stand_lamp
    to: 'unavailable'
    for: '00:10:00'
  condition:
  - condition: template
    value_template: "{{ not is_state('sensor.hue_bridge', 'unavailable') }}"
  action:
  - service: notify.mobile_app_matt_phone
    data_template:
      title: "Light unreachable"
      message: "{{ trigger.to_state.name }} is unreachable"
      data:
        ttl: 0
        priority: high


- alias: Notify when sensor battery low
  initial_state: true
  mode: parallel
  max: 100
  trigger:

# {% for state in states.sensor if 'battery' in state.entity_id and 'phone' not in state.entity_id and 'low' not in state.entity_id and 'ups' not in state.entity_id and 'hk' not in state.entity_id %}
# - {{ state.entity_id -}}
# {% endfor %}
  - platform: numeric_state
    entity_id:
    - sensor.andy_s_button_battery
    - sensor.basement_door_battery
    - sensor.basement_remote_battery_level
    - sensor.basement_temp_sensor_battery
    - sensor.craft_room_desk_button_battery
    - sensor.craft_room_desk_remote_battery
    - sensor.fridge_leak_sensor_battery
    - sensor.front_door_battery
    - sensor.front_door_keypad_battery
    - sensor.front_porch_door_battery
    - sensor.game_room_remote_battery_level
    - sensor.game_room_temp_battery
    - sensor.garage_door_battery_level
    - sensor.garage_service_door_battery
    - sensor.hall_bath_toilet_leak_sensor_battery
    - sensor.laundry_room_door_front_battery
    - sensor.laundry_room_lights_button_battery
    - sensor.laundry_room_temp_sensor_battery
    - sensor.living_room_lamp_button_battery
    - sensor.living_room_remote_battery_level
    - sensor.master_bath_toilet_leak_sensor_battery
    - sensor.master_bedroom_remote_battery_level
    - sensor.master_bedroom_temp_battery
    - sensor.matt_s_button_battery
    - sensor.mi_flora_battery
    - sensor.mouse_battery
    - sensor.office_desk_button_battery
    - sensor.office_desk_remote_battery
    - sensor.office_temp_battery
    - sensor.outdoor_light_sensor_battery
    - sensor.server_battery
    - sensor.side_door_battery
    - sensor.side_door_keypad_battery
    - sensor.side_entrance_doorbell_battery
    - sensor.siren_battery
    - sensor.smoke_co_alarm_battery_level
    - sensor.soldering_station_remote_battery
    below: 21
    for: '08:00:00'

# {% for state in states.binary_sensor if 'battery' in state.entity_id %}
# - {{ state.entity_id -}}
# {% endfor %}
  - platform: state
    entity_id:
    - binary_sensor.back_door_battery_low
    - binary_sensor.basement_bathroom_leak_sensor_battery_low
    - binary_sensor.basement_door_battery_low
    - binary_sensor.basement_fridge_door_battery_low
    - binary_sensor.bathroom_ejector_closet_door_battery_low
    - binary_sensor.bathroom_ejector_leak_sensor_battery_low
    - binary_sensor.craft_room_desk_button_battery_low
    - binary_sensor.deck_motion_sensor_battery_low
    - binary_sensor.dining_room_motion_sensor_battery_low
    - binary_sensor.dishwasher_leak_sensor_battery_low
    - binary_sensor.fridge_leak_sensor_battery_low
    - binary_sensor.front_door_battery_low
    - binary_sensor.front_door_keypad_battery_low
    - binary_sensor.front_porch_door_battery_low
    - binary_sensor.garage_door_battery_low
    - binary_sensor.garage_service_door_battery_low
    - binary_sensor.hall_bath_toilet_leak_sensor_battery_low
    - binary_sensor.hallway_motion_sensor_battery_low
    - binary_sensor.hvac_leak_sensor_battery_low
    - binary_sensor.kitchen_sink_leak_sensor_battery_low
    - binary_sensor.laundry_room_door_back_battery_low
    - binary_sensor.laundry_room_door_front_battery_low
    - binary_sensor.laundry_room_lights_button_battery_low
    - binary_sensor.laundry_room_motion_back_battery_low
    - binary_sensor.laundry_room_motion_front_battery_low
    - binary_sensor.living_room_lamp_button_battery_low
    - binary_sensor.living_room_motion_battery_low
    - binary_sensor.master_bath_sink_leak_sensor_battery_low
    - binary_sensor.master_bath_toilet_leak_sensor_battery_low
    - binary_sensor.office_desk_button_battery_low
    - binary_sensor.office_window_battery_low
    - binary_sensor.side_door_battery_low
    - binary_sensor.side_door_keypad_battery_low
    - binary_sensor.side_entrance_doorbell_battery_low
    - binary_sensor.smoke_co_alarm_battery_islow
    - binary_sensor.sump_pump_leak_sensor_battery_low
    - binary_sensor.washer_sink_leak_sensor_battery_low
    to: 'on'
  # condition:
  # - condition: template
  #   value_template: "{{ trigger.to_state.state != '' }}"
  action:
  - service: notify.gotify_high
    data_template:
      title: &batt_low_title Device battery low
      message: &batt_low_msg "{{ trigger.to_state.name.replace('battery low', '').replace('battery', '') }} battery is low."
      data:
        ttl: 0
        priority: high
  - service: persistent_notification.create
    data:
      title: *batt_low_title
      message: *batt_low_msg


- alias: Notify when fridge temp too high
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: 
    - sensor.main_fridge_temp
    - sensor.basement_fridge_temp
    above: 45
    for: '02:00:00'
  action:
  - service: notify.mobile_app_matt_phone
    data:
      title: &fridge_title "{{ trigger.to_state.name }} is too high"
      message: &fridge_msg Fridge has been above 45° for more than two hours.
      data:
        ttl: 0
        priority: high
  - service: notify.gotify_high
    data:
      title: *fridge_title
      message: *fridge_msg


- alias: Notify when 433MHz temp sensor battery low
  initial_state: true
  mode: parallel
  max: 10
  trigger:
  - platform: template
    value_template: "{{ is_state_attr('sensor.main_fridge_temp', 'battery_ok', 0) }}"
  - platform: template
    value_template: "{{ is_state_attr('sensor.basement_fridge_temp', 'battery_ok', 0) }}"
  - platform: template
    value_template: "{{ is_state_attr('sensor.attic_temp', 'battery_ok', 0) }}"
  action:
  - service: notify.mobile_app_matt_phone
    data:
      title: &fridge_batt_title "{{ trigger.to_state.name }} sensor battery low"
      message: &fridge_batt_msg Change the temp sensor battery now.
      data:
        ttl: 0
        priority: high
  - service: notify.gotify_high
    data:
      title: *fridge_batt_title
      message: *fridge_batt_msg


- alias: Notify when basement fridge open more than 5 minutes
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_fridge
    to: 'on'
    for: '00:05:00'
  action:
  - service: notify.gotify_high
    data:
      title: "Basement fridge door has been open for 5 minutes"
      message: "Did you forget to close it?"


- alias: Notify when Hue bridge is ready to update
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hue_bridge
    from: 'noupdates'
    to: 'readytoinstall'
  action:
  - service: persistent_notification.create
    data:
      title: "Hue bridge update available"
      message: "Please see Hue app for details."