- alias: Notify lights on when away
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - light.buffet
    - light.dining_room
    - light.game_room_closet
    - light.living_room
    - light.master_bedroom_lamps
    - light.game_room
    - light.laundry_room
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: light.entrance
    from: 'off'
    to: 'on'
    for: '00:00:45'
  condition:
  - condition: state
    entity_id: input_text.alarm
    state: armed_away
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: notify.mobile_app_matt_phone
    data_template:
      title: Lights have been turned on
      message: >
        {% set entity = trigger.to_state.entity_id %}
        {% set name = trigger.to_state.name %}
        {% if entity == 'light.entrance' %}
          {{ name }} has been turned on.
        {% else %}
          {{ name }} lights have been turned on.
        {% endif %}
      data:
        ttl: 0
        priority: high
        actions:
        - action: lights_off
          title: Turn off


- alias: Notify lights off when away
  initial_state: true
  trigger:
    platform: state
    entity_id: group.lights_interior
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_text.alarm
    state: armed_away
    for: '00:01:00'
  action:
    service: notify.mobile_app_matt_phone
    data:
      message: "Lights have been turned off."
      data:
        ttl: 0
        priority: high


- alias: Notify when motion detected on deck
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.deck_motion
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: alarm_control_panel.home
      state:
      - 'armed_home'
      - 'armed_night'
    - condition: state
      entity_id:
      - light.basement_main
      - light.office
      state: 'on'
  action:
  - service: notify.gotify_high
    data:
      title: Motion detected
      message: Motion detected on deck.


# - alias: Notify door opened when away
#   initial_state: true
#   trigger:
#   - platform: state
#     entity_id:
#     - binary_sensor.front_door
#     - binary_sensor.balcony_door
#     - binary_sensor.storm_door
#     to: 'on'
#   condition:
#   - condition: state
#     entity_id: input_text.alarm
#     state: armed_away
#     for: '00:00:30'
#   - condition: template
#     value_template: "{{ not is_state('device_tracker.pixel_xl_unifi', 'home') }}"
#   action:
#   - service: notify.mobile_app_matt_phone
#     data_template:
#       title: "{{ trigger.to_state.name }} opened"
#       message: >
#         {% set time = as_timestamp(now()) | timestamp_custom('%-I:%M %p') %}
#         {{ trigger.to_state.name }} was opened at {{ time.lower().lstrip('0') }}.
#       data:
#         ttl: 0
#         priority: high