### Notify when lights on/off when away
- alias: Notify lights on when away
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - light.buffet
    - light.dining_room
    - light.game_room_closet
    - light.living_room
    - light.master_bedroom
    - light.game_room
    - light.laundry_room
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: light.entrance
    from: 'off'
    to: 'on'
    for: '00:00:45'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: Lights have been turned on
      message: >
        {% set entity = trigger.to_state.entity_id %}
        {% set name = trigger.to_state.name %}
        {% if entity == 'light.entrance' %}
          {{ name }} has been turned on.
        {% else %}
          {{ name }} lights have been turned on.
        {% endif %}
      data:
        ttl: 0
        priority: high
        actions:
        - action: lights_off
          title: Turn off


- alias: Notify lights off when away
  initial_state: true
  trigger:
    platform: state
    entity_id: group.lights_interior
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
    for: '00:01:00'
  action:
    service: notify.mobile_app_pixel_xl
    data:
      message: "Lights have been turned off."
      data:
        ttl: 0
        priority: high


### Other
- alias: Notify if disarmed signal not received
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.sensor_tripped
    to: 'on'
    for: '00:00:45'
  action:
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Possible crash and smash attempt!"
      message: "Disarmed signal not received within 45 seconds of entry!"
      data:
        ttl: 0
        priority: high
  - service: notify.sms_matt
    data:
      title: "Possible crash and smash attempt!"
      message: "Disarmed signal not received within 45 seconds of entry!"


- alias: Notify if alarm not armed when away  # throttled - 8 hours
  initial_state: true
  trigger:
  - platform: state
    entity_id: device_tracker.pixel_xl_unifi
    from: 'home'
    to: 'not_home'
    for: '00:05:00'
  condition:
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.notify_if_alarm_not_armed_when_away', 'last_triggered'))) / 3600 > 8 }}"
  - condition: state
    entity_id: alarm_control_panel.abode
    state: 'disarmed'
  - condition: template
    value_template: "{{ not is_state('device_tracker.pixel_xl_unifi', 'home') }}"
  action:
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Alarm not armed"
      message: "You're away and the alarm is disarmed. Arm in away mode?"
      data:
        ttl: 0
        priority: high
        actions:
        - action: alarm_arm_away
          title: Arm alarm


- alias: Notify door opened when away
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door
    - binary_sensor.balcony_door
    - binary_sensor.storm_door
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  - condition: template
    value_template: "{{ not is_state('device_tracker.pixel_xl_unifi', 'home') }}"
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "{{ trigger.to_state.name }} opened"
      message: >
        {% set time = as_timestamp(now()) | timestamp_custom('%-I:%M %p') %}
        {{ trigger.to_state.name }} was opened at {{ time.lower().lstrip('0') }}.
      data:
        ttl: 0
        priority: high