- alias: Notify lights on when away
  id: 'Ienaesook9keeshet0unie'
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - light.buffet
    - light.dining_room
    - light.game_room_closet
    - light.living_room_lamps
    - light.master_bedroom_lamps
    - light.game_room
    - light.laundry_room
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: light.entrance
    from: 'off'
    to: 'on'
    for: '00:00:45'
  condition:
  - condition: state
    entity_id: input_text.alarm
    state: armed_away
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - service: notify.mobile_app_matt_phone
    data:
      title: Lights have been turned on
      message: >
        {% set entity = trigger.to_state.entity_id %}
        {% set name = trigger.to_state.name %}
        {% if entity == 'light.entrance' %}
          {{ name }} has been turned on.
        {% else %}
          {{ name }} lights have been turned on.
        {% endif %}
      data:
        ttl: 0
        priority: high
        actions:
        - action: lights_off
          title: Turn off


- alias: Notify lights off when away
  id: 'OhwaiNgaKai9Uvei4Ohg6l'
  initial_state: true
  trigger:
    platform: state
    entity_id: group.lights_interior
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_text.alarm
    state: armed_away
    for: '00:01:00'
  action:
    service: notify.mobile_app_matt_phone
    data:
      message: "Lights have been turned off."
      data:
        ttl: 0
        priority: high