- alias: Notify actions
  initial_state: true
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
  action:
    service_template: >
      {% set action = trigger.event.data.action %}
      {% if action in ['heat_reenable'] %}
        homeassistant.turn_on
      {% elif action in ['lights_off'] %}
        homeassistant.turn_off
      {% elif action == 'alarm_arm_away' %}
        script.turn_on
      {% else %}
        switch.turn_off
      {% endif %}
    data_template:
      target: >
        {% set action = trigger.event.data.action %}
        {% if action == 'alarm_arm_away' %}
          script.alarm_arm_away
        {% elif action == 'heat_reenable' %}
          script.tstat_heat_sleep
        {% elif action == 'lights_off' %}
          group.lights_interior
        {% else %}
          none
        {% endif %}