- platform: tod
  name: Quiet hours
  after: '23:00'
  before: '08:00'

- platform: wyzesense
  device: auto

- platform: huesensor

- platform: apcupsd

- platform: template
  sensors:
    all_speakers:
      friendly_name: All speakers
      value_template: >
        {% set bedroom = states('media_player.bedroom_speaker') %}
        {% set living = states('media_player.living_room_speaker') %}
        {% set kitchen = states('media_player.kitchen_speaker') %}
        {% set hub = states('media_player.hub') %}
        {{ (bedroom in ['playing', 'paused'] and living in ['playing', 'paused'] and kitchen in ['playing', 'paused'] and hub in ['playing', 'paused']) }}

    front_speakers:
      friendly_name: Front speakers
      value_template: >
        {% set kitchen = states('media_player.kitchen_speaker') %}
        {% set hub = states('media_player.hub') %}
        {{ kitchen in ['playing', 'paused'] and hub in ['playing', 'paused'] }}

    any_media_player:
      friendly_name: Any media player
      value_template: >
        {% set bedroom = states('media_player.bedroom_speaker') %}
        {% set living = states('media_player.living_room_speaker') %}
        {% set kitchen = states('media_player.kitchen_speaker') %}
        {% set hub = states('media_player.hub') %}
        {% set portable = states('media_player.portable_speaker') %}
        {% set bedroom_tv = states('media_player.bedroom_vizio') %}
        {% set living_tv = states('media_player.living_room_vizio') %}
        {{ bedroom != 'off' and living != 'off' and kitchen != 'off' and hub != 'off' and portable != 'off' and bedroom_tv != 'off' and living_tv != 'off' }}

    xbox:
      friendly_name: Xbox
      value_template: "{{ is_state('sensor.xbox_status', 'Available') }}"

    dark_inside:
      friendly_name: Dark inside
      value_template: "{{ state_attr('sun.sun', 'elevation') | float < states('input_number.dark_inside') | float }}"