- platform: tod
  name: Dark inside
  after: sunset
  after_offset: '-00:20'
  before: sunrise
  before_offset: '+00:20'

- platform: tod
  name: Quiet hours
  after: '23:00'
  before: '08:00'

- platform: workday
  name: Workday
  country: US

- platform: wyzesense
  device: auto

- platform: huesensor

- platform: apcupsd

- platform: template
  sensors:
    all_speakers:
      friendly_name: All speakers
      value_template: >
        {% set bedroom = states('media_player.bedroom_speaker') %}
        {% set living = states('media_player.living_room_speaker') %}
        {% set kitchen = states('media_player.kitchen_speaker') %}
        {% set hub = states('media_player.hub') %}
        {{ (bedroom == 'playing' and living == 'playing' and kitchen == 'playing' and hub == 'playing') or (bedroom == 'paused' and living == 'paused' and kitchen == 'paused' and hub == 'paused') }}
    xbox:
      friendly_name: Xbox
      value_template: "{{ is_state('sensor.xbox_status', 'Available') }}"
    bedroom_tv:
      friendly_name: Bedroom TV
      value_template: "{{ is_state('sensor.file_bedroom_tv', 'INFO:pyvizio.cli:Device is on') }}"