  lights_interior:
    name: Interior lights
    entities:
    - light.master_bedroom
    - light.living_room
    - light.dining_room
    - light.game_room
    - switch.light_switch1
    - light.laundry_room

  plugs:
    name: Smart plugs
    # do not include the living room fan since the on and off commands are the same! also don't include the washer plug (always on)
    entities:
    - switch.plug1
    - switch.plug2
    - switch.plug3
    - switch.plug4
    - switch.tuya_plug2