  lights_interior:
    name: Interior lights
    entities:
    - switch.light_switch1
    - light.master_bedroom
    - light.living_room
    - light.dining_room
    - light.game_room
    - light.laundry_room

  lights_all:
    name: All lights
    entities:
    - switch.light_switch1
    - light.porch_light
    - light.master_bedroom
    - light.living_room
    - light.dining_room
    - light.game_room
    - light.laundry_room

  plugs:
    name: Smart plugs
    entities:
    - switch.plug1
    - switch.plug2
    - switch.plug3
    - switch.plug4
    - switch.tuya_plug2