weather_1_offset:
  name: Lumi weather 1
  min: -3
  max: 3
  step: 0.5
  unit_of_measurement: '°F'
  mode: slider

weather_2_offset:
  name: Lumi weather 2
  min: -3
  max: 3
  step: 0.5
  unit_of_measurement: '°F'
  mode: slider

low_battery:
  name: Low battery
  min: 0
  max: 40
  step: 5
  unit_of_measurement: '%'
  mode: slider

dark_inside:
  name: Sun elevation when dark inside
  min: 0
  max: 2.5
  step: 0.1
  mode: slider