automation:
- alias: Turn entrance light on upon entrance
  initial_state: true
  trigger:
  - entity_id: 
    - binary_sensor.front_door
    - binary_sensor.side_door
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.dark_inside
      state: 'on'
  - condition: state
    entity_id: input_text.alarm
    state: 'armed_away'
    for: '00:00:30'
  action:
  - service: light.turn_on
    data:
      entity_id: "light.{{ 'entrance' if trigger.to_state.object_id == 'front_door' else 'side_entrance' }}"
      brightness_pct: "{{ 100 if 6 < now().hour < 22 else 66 }}"
      kelvin: 2700


- alias: Alarm disarmed from away
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
  action:
  - service: homeassistant.turn_on
    entity_id:
    - script.entrance_light_on
    - script.tstat_smart_resume_cool
    - script.arrival_night
    - input_boolean.arrival


- alias: Activate away mode when armed away
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    to: 'armed_away'
    for: '00:00:05'
  action:
  - service: script.turn_on
    entity_id: script.away_mode
  - delay: '00:00:05'
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.tstat_profile
      state: 
      - 'Away'
      - 'Hold'
    - condition: state
      entity_id: climate.thermostat
      state: 'off'
  - condition: state
    entity_id: group.lights_interior
    state: 'off'
  - service: script.notify_away
    data_template:
      title: Away mode activated


- alias: Away mode backup attempt
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    to: 'armed_away'
    for: '00:00:35'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.lights_interior
      state: 'on'
    - condition: state
      entity_id: binary_sensor.any_speaker
      state: 'on'
    - condition: state
      entity_id: binary_sensor.any_tv
      state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.away_mode
  - delay: '00:00:05'
  - condition: state
    entity_id: group.lights_interior
    state: 'off'
  - condition: state
    entity_id: binary_sensor.any_speaker
    state: 'off'
  - condition: state
    entity_id: binary_sensor.any_tv
    state: 'off'
  - service: script.notify_away
    data_template:
      title: Away mode activated (second attempt)


- alias: Master bedroom lights night arrival
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: 
    - input_boolean.arrival
    - input_boolean.dark_inside
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.master_bedroom_lamps
    data:
      brightness_pct: 100


- alias: Turn off arrival boolean
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
    for: '00:03:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.arrival


script:
  away_mode:
    sequence:
    - service: homeassistant.turn_off
      entity_id:
      - group.lights_interior
      - group.plugs
    - service: media_player.turn_off
      entity_id: all
    - service: script.turn_on
      entity_id: script.christmas_lights_off


  notify_away:
    sequence:
    - service: notify.mobile_app_matt_phone
      data_template:
        title: "{{ title }}"
        message: >
          {% set profile = states('sensor.tstat_profile') %}
          {% set tstat = states('climate.thermostat') %}
          {% if tstat == 'off' %}
            Lights are off, thermostat is off.
          {% elif profile in ['Away', 'Hold'] %}
            Lights are off, thermostat is set to {{ profile.lower() }}.
          {% else %}
            Uhh... this shouldn't be possible.
          {% endif %}
        data:
          ttl: 0
          priority: high
  
  
  entrance_light_on:
    sequence:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.dark_inside
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    - service: light.turn_on
      entity_id: 
      - light.entrance
      - switch.side_entrance_light
    - delay: '00:01:00'
    - service: light.turn_off
      entity_id: switch.side_entrance_light

  
  arrival_night:
    sequence:
    - condition: state
      entity_id: input_boolean.dark_inside
      state: 'on'
    - service: script.turn_on
      data:
        entity_id: "script.lights_{{ 'christmas' if is_state('input_boolean.christmas', 'on') else 'normal' }}"
    - service: timer.start
      entity_id: timer.master_bedroom_enter
      data:
        duration: 180
    - condition: template
      value_template: "{{ now().month in [11, 12] }}"
    - service: light.turn_on
      entity_id: light.christmas_lights
  

  lights_normal:
    sequence:
    - service: light.turn_on
      entity_id: 
      - light.buffet
      - light.kitchen_cabinets
      - light.hall_bath_night_light
      - light.hallway
      data:
        transition: 1
        brightness_pct: 100
        kelvin: 3000
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Read lamps


  lights_christmas:
    sequence:
    - service: homeassistant.turn_on
      entity_id: 
      - light.christmas_tree
      - light.mini_christmas_tree
      - light.portable_mini_christmas_tree
      - light.christmas_lights
      - light.star_lights
    - service: light.turn_on
      entity_id:
      - light.buffet
      - light.kitchen_cabinets
      data:
        transition: 1
        brightness_pct: 100
        kelvin: 3000
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Christmas
    - service: input_boolean.turn_on
      entity_id: input_boolean.christmas_porch_light_loop
    - service: light.turn_on
      entity_id: light.porch
      data:
        brightness_pct: 100
        rgb_color: [0,255,0]
    - delay: '00:01:00'
    - service: light.turn_on
      entity_id: light.living_room_lamps
      data:
        brightness_pct: 100
        kelvin: 3000
        transition: 10
    - service: light.turn_off
      entity_id: light.living_room_sconces
      data:
        transition: 10

  window_notify:
    sequence:
    - condition: state
      entity_id: group.windows
      state: 'on'
    - service: notify.mobile_app_matt_phone
      data:
        title: The following windows are open
        message: >
          {% for window in expand('group.windows') if window.state == 'off' -%}
          {{ window.name }}{% if not loop.last %}, {% endif %}
          {%- endfor %}
        data:
          ttl: 0
          priority: high

input_boolean:
  arrival:

timer:
  master_bedroom_enter: