automation:
- alias: Turn entrance light on upon entrance
  initial_state: true
  trigger:
  - entity_id: 
    - binary_sensor.front_door
    - binary_sensor.front_storm_door
    - binary_sensor.side_door
    - binary_sensor.side_storm_door
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.dark_inside
      state: 'on'
  - condition: state
    entity_id: input_text.alarm
    state: 'armed_away'
    for: '00:00:30'
  action:
  - choose:
    - conditions:
      - "{{ 'front' in trigger.to_state.object_id }}"
      - condition: state
        entity_id: light.entrance
        state: 'off'
      sequence:
      - service: light.turn_on
        entity_id: light.entrance
        data:
          brightness_pct: "{{ 100 if 6 < now().hour < 22 else 66 }}"
    default:
    - condition: state
      entity_id: switch.side_entrance_light
      state: 'off'
    - service: switch.turn_on
      entity_id: switch.side_entrance_light


- alias: Alarm disarmed from away
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
  action:
  - service: homeassistant.turn_on
    entity_id:
    - script.entrance_light_on
    - script.tstat_smart_resume_cool
    - script.arrival_night
    - input_boolean.arrival


- alias: Activate away mode when armed away
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    to: 'armed_away'
    for: '00:00:05'
  action:
  - service: script.turn_on
    entity_id: script.away_mode
  - delay: '00:00:05'
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.tstat_profile
      state: 
      - 'Away'
      - 'Hold'
      - 'PTS'
      - 'Smart'
    - condition: state
      entity_id: climate.thermostat
      state: 'off'
  - condition: state
    entity_id: group.lights_all
    state: 'off'
  - service: script.notify_away
    data:
      title: Away mode activated


- alias: Away mode backup attempt
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.alarm
    to: 'armed_away'
    for: '00:00:35'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.lights_interior
      state: 'on'
    - condition: state
      entity_id: binary_sensor.any_speaker
      state: 'on'
    - condition: state
      entity_id: binary_sensor.any_tv
      state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.away_mode
  - delay: '00:00:05'
  - condition: state
    entity_id: group.lights_interior
    state: 'off'
  - condition: state
    entity_id: binary_sensor.any_speaker
    state: 'off'
  - condition: state
    entity_id: binary_sensor.any_tv
    state: 'off'
  - service: script.notify_away
    data:
      title: Away mode activated (second attempt)


- alias: Master bedroom lights night arrival
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: 
    - input_boolean.arrival
    - input_boolean.dark_inside
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.master_bedroom_lamps
    data:
      brightness_pct: 100
      kelvin: 3000


- alias: Turn off arrival boolean
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
    for: '00:03:00'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.arrival


script:
  away_mode:
    sequence:
    - service: homeassistant.turn_off
      data:
        target: >
          {{ 'group.lights_interior' if is_state('input_boolean.dark_inside', 'off') else 'group.select_lights_interior' }}
    - service: homeassistant.turn_off
      entity_id: group.plugs
    - service: media_player.turn_off
      entity_id: all
    - service: script.turn_on
      entity_id: 
      - script.lr_fan_off
      - script.christmas_lights_off
    - service: script.turn_on
      data:
        entity_id: >
          {{ 'script.lights_kitty' if is_state('input_boolean.dark_inside', 'on') else none }}
    - condition: template
      value_template: "{{ not is_state('climate.thermostat', 'off') }}"
    - condition: state
      entity_id: climate.thermostat
      attribute: hvac_action
      state: 'idle'
    - condition: state
      entity_id:
      - input_boolean.tstat_hold
      - input_boolean.tstat_away
      state: 'off'
    - service: script.turn_on
      entity_id: script.tstat_away


  notify_away:
    sequence:
    - service: notify.mobile_app_matt_phone
      data_template:
        title: "{{ title }}"
        message: >
          {% set tstat = states('sensor.tstat_profile') %}
          {% set action = states('sensor.hvac_action') %}
          {% if tstat in ['Off', 'Away'] %}
            Lights are off, thermostat is {{ 'off' if tstat == 'off' else 'set to away' }}.
          {% elif action != 'idle' %}
            Lights are off.
          {% else %}
            Uhh... this shouldn't be possible.
          {% endif %}
        data:
          ttl: 0
          priority: high
  
  
  entrance_light_on:
    sequence:
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.dark_inside
        state: 'on'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    - service: switch.turn_on
      entity_id: switch.side_entrance_light
    - service: light.turn_on
      entity_id:
      - light.entrance
      - light.kitchen_cabinets
      - light.buffet
      - light.hallway
      data:
        brightness_pct: "{{ 100 if now().hour in range(7,21) else 66 }}"
    - delay: '00:01:00'
    - service: switch.turn_off
      entity_id: switch.side_entrance_light

  
  arrival_night:
    sequence:
    - condition: state
      entity_id: input_boolean.dark_inside
      state: 'on'
    - service: script.turn_on
      data:
        entity_id: "script.lights_{{ 'christmas' if is_state('input_boolean.christmas', 'on') else 'normal' }}"
    - service: timer.start
      entity_id: timer.master_bedroom_enter
      data:
        duration: 180
    - condition: template
      value_template: "{{ now().month in [11, 12] }}"
    - service: light.turn_on
      entity_id: light.christmas_lights
  

  lights_normal:
    sequence:
    - service: light.turn_on
      entity_id:
      - light.entrance
      - light.buffet
      - light.other_buffet
      - light.hallway
      data:
        transition: 1
        brightness_pct: "{{ 100 if now().hour > 6 or now().hour < 21 else 66 }}"
        kelvin: 3000
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
        brightness_pct: "{{ 100 if now().hour > 6 or now().hour < 21 else 75 }}"
    - service: light.turn_on
      entity_id: light.hall_bath_night_light
      data:
        transition: 1
        brightness_pct: 100
        kelvin: 3000
    - service: hue.hue_activate_scene
      data:
        group_name: Living room lamps
        scene_name: Read lamps


  lights_christmas:
    sequence:
    - service: homeassistant.turn_on
      entity_id: 
      - light.christmas_tree
      - light.mini_christmas_tree
      - light.portable_mini_christmas_tree
      - light.christmas_lights
      - light.star_lights
    - service: light.turn_on
      entity_id:
      - light.entrance
      - light.buffet
      - light.other_buffet
      - light.hallway
      data:
        transition: 1
        brightness_pct: "{{ 100 if now().hour > 6 or now().hour < 21 else 66 }}"
        kelvin: 3000
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
        brightness_pct: "{{ 100 if now().hour > 6 or now().hour < 21 else 50 }}"


  lights_kitty:
    sequence:
    - service: light.turn_on
      entity_id:
      - light.buffet
      - light.hallway
      - light.living_room
      data:
        brightness_pct: 20
        kelvin: 3000


  window_notify:
    sequence:
    - condition: state
      entity_id: group.windows
      state: 'on'
    - service: notify.mobile_app_matt_phone
      data:
        title: The following windows are open
        message: >
          {% for window in expand('group.windows') if window.state == 'off' -%}
          {{ window.name }}{% if not loop.last %}, {% endif %}
          {%- endfor %}
        data:
          ttl: 0
          priority: high


  lr_fan_off:
    sequence:
    - condition: state
      entity_id: &lr_fan switch.living_room_fan
      state: 'on'
    - service: switch.turn_off
      entity_id: *lr_fan


input_boolean:
  arrival:

timer:
  master_bedroom_enter: