automation:
- alias: Turn entrance light on upon entrance
  initial_state: true
  trigger:
  - entity_id: 
    - binary_sensor.front_door
    - binary_sensor.front_door_cloud
    - binary_sensor.entrance_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.turn_entrance_light_on_upon_entrance', 'last_triggered'))) > 60 }}"
  - condition: state
    entity_id: input_text.abode
    state: 'armed_away'
    for: '00:00:30'
  action:
  - service: light.turn_on
    entity_id: light.entrance


- alias: Alarm disarmed from away
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.abode
    from: 'armed_away'
    to: 'disarmed'
  action:
  - service: homeassistant.turn_on
    entity_id:
    - script.entrance_light_on
    - script.tstat_smart_resume_cool
    - script.arrival_night
    - input_boolean.arrival


- alias: Activate away mode when armed away
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.abode
    to: 'armed_away'
    for: '00:00:35'
  action:
  - service: script.turn_on
    entity_id: script.away_mode
  - delay: '00:00:05'
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.tstat_profile
      state: 
      - 'Away'
      - 'Hold'
    - condition: state
      entity_id: climate.thermostat
      state: 'off'
  - condition: state
    entity_id: group.lights_all
    state: 'off'
  - service: script.notify_away
    data_template:
      title: Away mode activated


- alias: Away mode backup attempt
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_text.abode
    to: 'armed_away'
    for: '00:01:00'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.lights_all
      state: 'on'
    - condition: state
      entity_id: binary_sensor.any_speaker
      state: 'on'
    - condition: state
      entity_id: binary_sensor.any_tv
      state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.away_mode
  - delay: '00:00:05'
  - condition: state
    entity_id: group.lights_all
    state: 'off'
  - condition: state
    entity_id: binary_sensor.any_speaker
    state: 'off'
  - condition: state
    entity_id: binary_sensor.any_tv
    state: 'off'
  - service: script.notify_away
    data_template:
      title: Away mode activated (second attempt)


- alias: Master bedroom lights night arrival
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.master_bedroom_motion
    from: 'off'
    to: 'on'
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.master_bedroom_enter
  condition:
  - condition: state
    entity_id: input_boolean.arrival
    state: 'on'
  action:
  - service_template: "{{ 'timer.cancel' if trigger.platform == 'state' else 'light.turn_off' }}"
    data_template:
      entity_id: "{{ 'timer.master_bedroom_enter' if trigger.platform == 'state' else 'light.master_bedroom' }}"


- alias: Turn off arrival boolean
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.master_bedroom_enter
  - platform: state
    entity_id: binary_sensor.master_bedroom_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.arrival
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.arrival


script:
  away_mode:
    sequence:
    - service: homeassistant.turn_off
      entity_id:
      - input_boolean.christmas_porch_light_loop
      - group.plugs
      - group.lights_all
      - climate.space_heater
    - service: media_player.turn_off
      entity_id: all
    - service: script.turn_on
      entity_id:
      - script.window_notify
      - script.christmas_lights_off


  notify_away:
    sequence:
    - service: notify.mobile_app_pixel_xl
      data_template:
        title: "{{ title }}"
        message: >
          {% set profile = states('sensor.tstat_profile') %}
          {% set tstat = states('climate.thermostat') %}
          {% if tstat == 'off' %}
            Lights are off, thermostat is off.
          {% elif profile in ['Away', 'Hold'] %}
            Lights are off, thermostat is set to {{ profile.lower() }}.
          {% else %}
            Uhh... this shouldn't be possible.
          {% endif %}
        data:
          ttl: 0
          priority: high
  
  
  entrance_light_on:
    sequence:
    - service: light.turn_on
      entity_id: light.entrance
    - delay: '00:01:00'
    - service: light.turn_off
      entity_id: light.entrance

  
  arrival_night:
    sequence:
    - condition: state
      entity_id: input_boolean.dark_inside
      state: 'on'
    - service: script.turn_on
      data:
        entity_id: "script.lights_{{ 'christmas' if is_state('input_boolean.christmas', 'on') else 'normal' }}"
    - service: timer.start
      entity_id: timer.master_bedroom_enter
      data:
        duration: 180
    - condition: template
      value_template: "{{ now().month in [11, 12] }}"
    - service: switch.turn_on
      entity_id: switch.christmas_lights_plug_1
  

  lights_normal:
    sequence:
    - service: light.turn_on
      entity_id: light.buffet
      data:
        brightness_pct: 100
        kelvin: 3000
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Read lamps
    - service: hue.hue_activate_scene
      data:
        group_name: Master bedroom
        scene_name: Read
    - service: light.turn_on
      entity_id:
      - light.kitchen_cabinets
      - light.hall_bath_night_light
      - light.master_bedroom_night_light
      data:
        brightness_pct: 100


  lights_christmas:
    sequence:
    - service: homeassistant.turn_on
      entity_id: 
      - light.christmas_tree
      - light.mini_christmas_tree
      - light.portable_mini_christmas_tree
      - switch.christmas_lights_plug_1
      - light.star_lights
    - service: light.turn_on
      entity_id:
      - light.buffet
      - light.kitchen_cabinets
      - light.master_bedroom_night_light
      data:
        brightness_pct: 100
        kelvin: 3000
    - service: hue.hue_activate_scene
      data:
        group_name: Master bedroom
        scene_name: Read
    - service: hue.hue_activate_scene
      data:
        group_name: Living room
        scene_name: Christmas
    - service: light.turn_on
      entity_id: light.porch
      data:
        brightness_pct: 100
        rgb_color: [0,255,0]
    - service: automation.turn_on
      entity_id: automation.christmas_porch_light_loop
    - delay: '00:01:00'
    - service: light.turn_on
      entity_id: light.living_room_lamps
      data:
        brightness_pct: 100
        kelvin: 3000
        transition: 10
    - service: light.turn_off
      entity_id: light.living_room_sconces
      data:
        transition: 10

  window_notify:
    sequence:
    - condition: state
      entity_id: group.windows
      state: 'on'
    - service: notify.mobile_app_pixel_xl
      data:
        title: The following windows are open
        message: >
          {% for window in expand('group.windows') if window.state == 'off' -%}
          {{ window.name }}{% if not loop.last %}, {% endif %}
          {%- endfor %}
        data:
          ttl: 0
          priority: high

input_boolean:
  arrival:

timer:
  master_bedroom_enter: