automation:
- alias: Record highest attic/outside temp
  initial_state: true
  mode: parallel
  trigger:
  - platform: template
    value_template: "{{ states('sensor.attic_temp') | float > states('input_number.attic_temp_max') | float }}"
  - platform: template
    value_template: "{{ states('sensor.outside_temp') | float > states('input_number.outside_temp_max') | float }}"
  - platform: template
    value_template: "{{ states('sensor.attic_temp_delta') | float > states('input_number.attic_temp_delta_max') | float }}"
  action:
  - service: input_number.set_value
    data:
      entity_id: input_number.attic_temp_max
      value: "{{ states('sensor.attic_temp') | float if states('sensor.attic_temp') | float > states('input_number.attic_temp_max') | float else states('input_number.attic_temp_max') | float }}"
  - service: input_number.set_value
    data:
      entity_id: input_number.outside_temp_max
      value: "{{ states('sensor.outside_temp') | float if states('sensor.outside_temp') | float > states('input_number.outside_temp_max') | float else states('input_number.outside_temp_max') | float }}"
  - service: input_number.set_value
    data:
      entity_id: input_number.attic_temp_delta_max
      value: "{{ states('sensor.attic_temp_delta') | float if states('sensor.attic_temp_delta') | float > states('input_number.attic_temp_delta_max') | float else states('input_number.attic_temp_delta_max') | float }}"


- alias: Reset highest attic/outside temp
  initial_state: true
  trigger:
  - platform: time
    at: '03:00:00'
  action:
  - service: input_number.set_value
    data:
      entity_id:
      - input_number.attic_temp_max
      - input_number.outside_temp_max
      - input_number.attic_temp_delta_max
      value: 0
  

input_number:
  attic_temp_max:
    name: Max attic temp
    min: -100
    max: 200
    step: 0.1
    mode: box
    unit_of_measurement: '°F'

  outside_temp_max:
    name: Max outside temp
    min: -100
    max: 200
    step: 0.1
    mode: box
    unit_of_measurement: '°F'

  attic_temp_delta_max:
    name: Max attic temp delta
    min: -100
    max: 200
    step: 0.1
    mode: box
    unit_of_measurement: '°F'


sensor:
- platform: template
  sensors:
    attic_temp_max:
      friendly_name: Max attic temp
      value_template: "{{ states('input_number.attic_temp_max') | float | round(1) }}"
      unit_of_measurement: '°F'

    outside_temp_max:
      friendly_name: Max outside temp
      value_template: "{{ states('input_number.outside_temp_max') | float | round(1) }}"
      unit_of_measurement: '°F'

    attic_temp_delta_max:
      friendly_name: Max attic temp delta
      value_template: "{{ states('input_number.attic_temp_delta_max') | float | round(1) }}"
      unit_of_measurement: '°F'