automation:
- alias: Record when on balcony
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.balcony_door
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: input_boolean.on_balcony
    state: 'off'
  action:
  - wait_template: "{{ is_state('binary_sensor.balcony_motion', 'on') }}"
    timeout: '00:00:30'
    continue_on_timeout: false
  - service: input_boolean.turn_on
    entity_id: input_boolean.on_balcony


- alias: Clear when on balcony
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.balcony_door
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.on_balcony
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.on_balcony


input_boolean:
  on_balcony: