automation:
- alias: Record coffeemaker on/off
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.coffeemaker_power
    above: 1000
  - platform: numeric_state
    entity_id: sensor.coffeemaker_power
    below: 10
    for: '00:00:10'
  condition:
  - condition: state
    entity_id: input_boolean.coffee_notify
    state: 'off'
  action:
  - service_template: "input_boolean.turn_{{ 'on' if trigger.to_state.state | float(0) > 500 else 'off' }}"
    entity_id: input_boolean.coffeemaker


- alias: Notify when coffee done
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.coffeemaker
    from: 'on'
    to: 'off'
  action:
  - service: notify.gotify
    data:
      title: "Coffee is ready"
      message: "Enjoy!"
  - service: input_boolean.turn_on
    entity_id: input_boolean.coffee_notify


- alias: Reset coffee notification
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.coffeemaker_power
    to: '0'
    for: '00:01:00'
  condition:
  - condition: state
    entity_id: input_boolean.coffee_notify
    state: 'on'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.coffee_notify
  

input_boolean:
  coffeemaker:
  coffee_notify: