automation:
- alias: Toggle update boolean
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.hass_update
  action:
  - service_template: "input_boolean.turn_{{ 'off' if is_state('sensor.hass_update', 'Newest') else 'on' }}"
    entity_id: input_boolean.hass_update


- alias: Notify when beta available
  initial_state: true
  trigger:
  - platform: template
    value_template: "{{ states('sensor.latest_version').find('b') != -1 }}"
  condition:
  - condition: state
    entity_id: input_boolean.notify_all_updates
    state: 'off'
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unknown' }}"
  - condition: template
    value_template: "{{ trigger.from_state.state.find('b') == -1 }}"
  action:
  - service: notify.gotify
    data_template:
      title: "Home Assistant beta is available!"
      message: "{{ states('sensor.latest_version') }} is now available."


- alias: Notify for all updates
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.latest_version
  condition:
  - condition: state
    entity_id: input_boolean.notify_all_updates
    state: 'on'
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unknown' }}"
  action:
  - service: notify.gotify
    data_template:
      title: "Home Assistant update available!"
      message: "{{ states('sensor.latest_version') }} is now available."


sensor:
- platform: version
  name: Latest version
  beta: true
  image: raspberrypi3
  source: docker

- platform: version
  name: Current version
  source: local

- platform: template
  sensors:
    hass_update:
      friendly_name: "Update notification"
      value_template: >
        {% set current = states('sensor.current_version') %}
        {% set latest = states('sensor.latest_version') %}
        {% if current.find('b') != -1 and latest.find('b') != -1 %}
          {% if latest[latest.find('b') + 1] | float > current[current.find('b') + 1] | float %}
            {{ latest }} is available, and you are running {{ current }}.
          {% else %}
            Newest
          {% endif %}
        {% elif current.find('b') == -1 and latest.find('b') != -1 %}
          {% if latest[2:7] | float > current[2:] | float %}
            {{ latest }} is available, and you are running {{ current }}.
          {% else %}
            Newest
          {% endif %}
        {% else %}
          {% if latest[2:] | float > current[2:] | float %}
            {{ latest }} is available, and you are running {{ current }}.
          {% else %}
            Newest
          {% endif %}
        {% endif %}


input_boolean:
  hass_update:
  notify_all_updates: