automation:
- alias: Toggle holiday modes
  id: 'phoofaad8chil5Ahngahzi'
  initial_state: true
  trigger:
  - platform: time
    at: '00:00:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: >
        {% set month = now().month %}
        {% set day = now().day %}
        {{ (month == 2 and day in [14, 15]) 
          or (month in [4, 10] and day == 1) 
          or month == 11
          or (month == 1 and day == 7)
          or (month == 5 and day in [1, 4, 5]) 
          or (month == 7 and day in [4, 5]) }}
    - condition: template
      value_template: >
        {% set month = now().month %}
        {% set day = now().day %}
        {% set weekday = now().weekday() %}
        {{ month == 11 and day > 21 and weekday == 3 }}
  action:
    service_template: >
      {% set month = now().month %}
      {% set day = now().day %}
        input_boolean.turn_{{ 'on' if day in [4, 14] or month in [4, 10, 12] else 'off' }}
    data_template:
      entity_id: >
        {% set month = now().month %}
        {% set day = now().day %}
        {% if month == 2 %}
          input_boolean.valentines_day
        {% elif month == 5 and day in [4, 5] %}
          input_boolean.andy_birthday
        {% elif month in [4, 5] %}
          input_boolean.autism_awareness
        {% elif month == 7 %}
          input_boolean.independence_day
        {% elif month == 10 or (month == 11 and day == 1) %}
          input_boolean.halloween
        {% else %}
          input_boolean.christmas
        {% endif %}


# - alias: Turn on holiday porch light
#   initial_state: true
#   trigger:
#   - platform: state
#     entity_id: sun.sun
#     to: 'below_horizon'
#     for: '00:10:00'
#   - platform: homeassistant
#     event: start
#   condition:
#   - condition: template
#     value_template: "{{ states('input_text.alarm') in ['armed_home', 'disarmed'] }}"
#   - condition: template
#     value_template: >
#       {{ 
#         is_state('input_boolean.valentines_day', 'on') or
#         is_state('input_boolean.autism_awareness', 'on') or
#         is_state('input_boolean.halloween', 'on') or
#         is_state('input_boolean.andy_birthday', 'on') or
#         is_state('input_boolean.independence_day', 'on') or
#         (is_state('input_boolean.christmas', 'on') and now().month == 12)
#       }}
#   action:
#   - choose:
#     - conditions:
#       - condition: state
#         entity_id: input_boolean.christmas
#         state: 'on'
#       sequence:
#       - service: input_boolean.turn_on 
#         entity_id: input_boolean.christmas_porch_light_loop
#       - service: light.turn_on
#         entity_id: light.porch
#         data:
#           brightness_pct: 100
#           transition: 0.4
#           rgb_color: [0,255,0]
#     default:
#     - service: script.holiday_porch_light


- alias: Turn on balcony Christmas lights
  id: 'Sheb6MiejahYaeX0eingee'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sun.sun
    to: 'below_horizon'
    for: '00:10:00'
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: template
    value_template: "{{ now().month in [11, 12] }}"
  action:
  - service: light.turn_on
    entity_id: light.christmas_lights


# - alias: Christmas porch light loop
#   initial_state: true
#   trigger:
#   - platform: homeassistant
#     event: start
#   - platform: state
#     entity_id: input_boolean.christmas_porch_light_loop
#     to: 'on'
#   - platform: template
#     value_template: "{{ state_attr('light.porch', 'rgb_color')[0] == 255 }}"
#     for: '00:30:00'
#   - platform: template
#     value_template: "{{ state_attr('light.porch', 'rgb_color')[1] == 255 }}"
#     for: '00:30:00'
#   condition:
#   - condition: state
#     entity_id: input_boolean.christmas_porch_light_loop
#     state: 'on'
#   action:
#   - service: mqtt.publish
#     data:
#       topic: "cmnd/porch_light/backlog"
#       payload: "speed 5; {{ 'color1 1' if state_attr('light.porch', 'rgb_color')[1] == 255 else 'color1 2' }}; speed 1"


script:
  holiday_porch_light:
    sequence:
    - service: light.turn_on
      entity_id: light.porch
      data_template:
        brightness_pct: 100
        transition: 0.4
        color_name: >
          {% if is_state('input_boolean.valentines_day', 'on') %}
            pink
          {% elif is_state('input_boolean.autism_awareness', 'on') %}
            blue
          {% elif is_state('input_boolean.halloween', 'on') %}
            orange
          {% elif is_state('input_boolean.andy_birthday', 'on') or is_state('input_boolean.independence_day', 'on') %}
            red
          {% else %}
            green
          {% endif %}


input_boolean:
  valentines_day:
  andy_birthday:
  independence_day:
  autism_awareness:
  halloween:
  christmas:
  christmas_porch_light_loop: