automation:
- alias: Record coffeemaker on/off
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: &coffeemaker sensor.coffeemaker_power
    above: 1000
  - platform: numeric_state
    entity_id: *coffeemaker
    below: 10
    for: '00:00:10'
  action:
  - service_template: "input_boolean.turn_{{ 'on' if trigger.to_state.state | float(0) > 500 else 'off' }}"
    data:
      entity_id: "input_boolean.{{ 'basement_' if 'basement' in trigger.to_state.entity_id else '' }}coffeemaker"


- alias: Notify when coffee done
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.coffeemaker
    from: 'on'
    to: 'off'
  action:
  - service: notify.gotify
    data:
      title: "Coffee is ready {{ 'in the basement' if 'basement' in trigger.to_state.entity_id else 'in the kitchen' }}"
      message: "Enjoy!"
  

input_boolean:
  coffeemaker: