automation:
- alias: Notify when washer/dryer done
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.washer
    - input_boolean.dryer
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - input_boolean.washer_reminder
    - input_boolean.dryer_reminder
    to: 'on'
    for: '00:30:00'
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] or is_state('device_tracker.pixel_xl_unifi', 'home') }}"
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service: notify.gotify
    data_template:
      title: "{{ trigger.to_state.name }} done {{ 'reminder' if 'reminder' in trigger.to_state.entity_id else '' }}"
      message: "{{ 'Move clothes to the dryer.' if trigger.to_state.name == 'Washer' else 'Put your clothes away.' }}"
  - service_template: "input_boolean.turn_{{ 'on' if 'reminder' not in trigger.to_state.entity_id else 'off' }}"
    data_template:
      entity_id: "{{ trigger.to_state.entity_id }}{{ '_reminder' if 'reminder' not in trigger.to_state.entity_id else '' }}"
  - condition: state
    entity_id: media_player.living_room_vizio
    state: 'on'
  - service: script.laundry_light_strip_notify


- alias: Record washer/dryer on/off
  initial_state: true
  mode: parallel
  trigger:
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_1_power
    above: 550
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_1_power
    below: 1.5
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_2_power
    above: 250
    for: '00:05:00'
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_2_power
    below: 50
  action:
  - service_template: "input_boolean.turn_{{ 'on' if trigger.to_state.state | float > 250 else 'off' }}"
    data_template:
      entity_id: "input_boolean.{{ 'washer' if '1' in trigger.to_state.entity_id else 'dryer' }}"


- alias: Reset laundry reminder booleans
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - binary_sensor.laundry_room_door
    - input_boolean.sleep_mode
    to: 'on'
  - platform: state
    entity_id: alarm_control_panel.abode
    to: 'armed_away'
  action:
  - service: input_boolean.turn_off
    entity_id:
    - input_boolean.washer_reminder
    - input_boolean.dryer_reminder


script:
  laundry_light_strip_notify:
    sequence:
    - service: light.turn_on  
      entity_id: light.strip_1
    - service: light.turn_on  
      entity_id: light.strip_1
      data:
        rgb_color: [255,0,0]
        brightness_pct: 100
        transition: 1
    - delay: '00:00:01'
    - service: light.turn_on  
      entity_id: light.strip_1
      data:
        rgb_color: [0,0,255]
        transition: 1
    - service: light.turn_off
      entity_id: light.strip_1


input_boolean:
  washer:
    name: Washer
  dryer:
    name: Dryer
  washer_reminder:
    name: Washer
  dryer_reminder:
    name: Dryer