automation:
- alias: Notify when shutting down
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.server_ups_battery
    below: 30
  condition:
  - condition: state
    entity_id: sensor.server_ups_status
    state: 'ONBATT'
  action:
  - service: notify.gotify_high
    data:
      title: "Server shutting down"
      message: "Power critical, shutdown imminent. See you later :("


- alias: Notify when power lost or restored
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: sensor.server_ups_status
    from:
    - 'ONLINE'
    - 'ONBATT'
    to:
    - 'ONBATT'
    - 'ONLINE'
  action:
  - service: input_text.set_value
    data_template:
      entity_id: "{{ 'input_text.time_power_lost' if trigger.to_state.state == 'ONBATT' else 'input_text.time_power_restored' }}"
      value: "{{ as_timestamp(now()) }}"
  - service: notify.mobile_app_matt_phone
    data_template:
      title: "{{ 'Power lost' if trigger.to_state.state == 'ONBATT' else 'Power restored' }}"
      message: >
        {% if trigger.to_state.state == 'ONBATT' %}
          Running on battery.
        {% else %}
          System was on battery for {{ states('sensor.power_outage_length') }}
        {% endif %}
      data:
        ttl: 0
        priority: high


sensor:
- platform: template
  sensors:
    power_status:
      friendly_name: Power status
      value_template: >
        {% set ups = states('sensor.server_ups_status') %}
        {% if ups == 'ONLINE' %}
          AC power
        {% elif ups == 'ONBATT' %}
          On battery: {{ states('sensor.server_ups_battery') | float }}% ({{ states('sensor.server_ups_time_left') | float | round(0) }} min)
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% set ups = states('sensor.server_ups_status') %}
        {% if ups == 'ONLINE' %}
          mdi:power-plug
        {% elif ups == 'ONBATT' %}
          mdi:power-plug-off
        {% else %}
          mdi:battery-unknown
        {% endif %}
    
    power_outage_length:
      friendly_name: Power outage length
      value_template: >
        {% set diff = ((states('input_text.time_power_restored') | float - states('input_text.time_power_lost') | float) / 60) | round(0) %}
        {% if diff < 1 %}
          less than a minute.
        {% elif diff == 1 %}
          1 minute.
        {% else %}
          {{ diff }} minutes.
        {% endif %}


input_text:
  time_power_lost:
  time_power_restored: