automation:
- alias: Notify when shutting down
  id: 'oojoodooH7urahron1teit'
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.server_ups_battery
    below: 30
  condition:
  - condition: state
    entity_id: binary_sensor.ups_online_status
    state: 'off'
  action:
  - service: notify.gotify_high
    data:
      title: "Server shutting down"
      message: "Power critical, shutdown imminent. See you later :("


- alias: Notify when power lost or restored
  id: 'sahf7phuQu0phaiZ8Jee9f'
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: binary_sensor.ups_online_status
    to:
    - 'on'
    - 'off'
  action:
  - service: input_text.set_value
    data_template:
      entity_id: "{{ 'input_text.time_power_lost' if trigger.to_state.state == 'off' else 'input_text.time_power_restored' }}"
      value: "{{ as_timestamp(now()) }}"
  - service: notify.gotify_high
    data_template:
      title: "{{ 'Power lost' if trigger.to_state.state == 'off' else 'Power restored' }}"
      message: >
        {% if trigger.to_state.state == 'off' %}
          Running on battery.
        {% else %}
          System was on battery for {{ states('sensor.power_outage_length') }}
        {% endif %}


sensor:
- platform: template
  sensors:
    power_status:
      friendly_name: Power status
      value_template: >
        {% set ups = states('binary_sensor.ups_online_status') %}
        {% if ups == 'on' %}
          AC power
        {% elif ups == 'off' %}
          On battery: {{ states('sensor.server_ups_battery') | float(0) }}% ({{ states('sensor.server_ups_time_left') | float(0) | round(0) }} min)
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% set ups = states('binary_sensor.ups_online_status') %}
        {% if ups == 'on' %}
          mdi:power-plug
        {% elif ups == 'off' %}
          mdi:power-plug-off
        {% else %}
          mdi:battery-unknown
        {% endif %}
    
    power_outage_length:
      friendly_name: Power outage length
      value_template: >
        {% set diff = ((states('input_text.time_power_restored') | float(0) - states('input_text.time_power_lost') | float(0)) / 60) | round(0) %}
        {% if diff < 1 %}
          less than a minute.
        {% elif diff == 1 %}
          1 minute.
        {% else %}
          {{ diff }} minutes.
        {% endif %}


input_text:
  time_power_lost:
  time_power_restored: