automation:
- alias: Set speaker volume based on app
  id: 'rai2eifeijahvaeFeev7to'
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id:
    - sensor.craft_room_speaker_app_name
    - sensor.hub_app_name
    - sensor.laundry_room_speaker_app_name
    - sensor.living_room_speaker_app_name
    - sensor.master_bedroom_clock_app_name
    - sensor.office_speaker_app_name
  - platform: state
    entity_id: input_boolean.office_speaker
    to: 'off'
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state not in ['', 'unknown'] }}"
  - condition: template
    value_template: "{{ not ('bedroom' in trigger.to_state.object_id and is_state('input_boolean.white_noise', 'on')) }}"
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: "media_player.{{ trigger.to_state.name.lower().replace(' ','_') }}"
      volume_level: >
        {% set app = trigger.to_state.state if trigger.to_state.domain == 'sensor' else states(trigger.to_state.entity_id.replace('input_boolean','sensor') + '_app_name') %}
        {% set speaker = trigger.to_state.entity_id.replace('sensor.','').replace('input_boolean','').replace('_speaker','').replace('_app_name','').replace('_',' ') %}
        {% set album = state_attr(trigger.to_state.entity_id.replace('sensor.','media_player.').replace('input_boolean.','media_player.').replace('_app_name',''), 'media_album_name') %}
        {% if app in ['iHeartRadio', 'Audacy', 'Default Media Receiver'] %}
          {% if speaker in ['bedroom', 'laundry room', 'living room'] %}
            0.32
          {% elif speaker in ['office', 'craft room'] %}
            {{ 0.28 if album == '103.5 KISS FM' else 0.36 }}
          {% elif speaker in ['hub'] %}
            {{ 0.38 if album == '103.5 KISS FM' else 0.44 }}
          {% else %}
            0.36
          {% endif %}
        {% elif app in ['Google Play Music', 'Spotify', 'YouTube Music'] %}
          {% if speaker in ['bedroom', 'kitchen', 'living room'] %}
            0.36
          {% elif speaker in ['office', 'laundry room'] %}
            0.3
          {% elif speaker in ['hub'] %}
            0.4
          {% else %}
            0.36
          {% endif %}
        {% else %}
          0.3
        {% endif %}


- alias: Lower office speaker volume when receiving a call
  id: 'He3fohshif6dohkae1quee'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.matt_phone_phone_state
    from: 'idle'
    to: 'ringing'
  - platform: state
    entity_id: sensor.matt_phone_phone_state
    from: 
    - 'ringing'
    - 'offhook'
    to: 'idle'
  condition:
  - condition: state
    entity_id: &speakers media_player.office_speaker
    state: 'playing'
  - "{{ is_state_attr('media_player.office_speaker', 'is_volume_muted', false) }}"
  action:
  - service: "input_boolean.turn_{{ 'on' if trigger.to_state.state == 'ringing' else 'off' }}"
    entity_id: input_boolean.office_speaker
  - condition: template
    value_template: "{{ trigger.to_state.state == 'ringing' }}"
  - service: media_player.volume_set
    data:
      entity_id: *speakers
      volume_level: 0.2


- alias: Mute/unmute office speaker when in call
  id: 'aeS1bi4ohpho7Xah2ahWai'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.matt_phone_phone_state
    from: 
    - 'idle'
    - 'ringing'
    to: 'offhook'
  - platform: state
    entity_id: sensor.matt_phone_phone_state
    from: 'offhook'
    to: 'idle'
  condition:
  - condition: state
    entity_id: *speakers
    state: 'playing'
  action:
  - service: media_player.volume_mute
    data:
      entity_id: *speakers
      is_volume_muted: "{{ true if trigger.to_state.state == 'offhook' else false }}"


input_boolean:
  office_speaker:


sensor:
- platform: attributes
  attribute: app_name
  entities: &media_players
  - media_player.craft_room_speaker
  - media_player.laundry_room_speaker
  - media_player.living_room_speaker
  - media_player.master_bedroom_clock
  - media_player.office_speaker
  - media_player.living_room_vizio
  - media_player.living_room_cast

- platform: attributes
  attribute: media_title
  entities: *media_players