    power_status:
      friendly_name: Power status
      value_template: >
        {% set ups = states('sensor.ups_status') %}
        {% if ups == 'ONLINE' %}
          AC power
        {% elif ups == 'ONBATT' %}
          On battery: {{ states('sensor.ups_battery') | float }}% ({{ states('sensor.ups_time_left') | float | round(0) }} min)
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% set ups = states('sensor.ups_status') %}
        {% if ups == 'ONLINE' %}
          mdi:power-plug
        {% elif ups == 'ONBATT' %}
          mdi:power-plug-off
        {% else %}
          mdi:battery-unknown
        {% endif %}