    avg_cooling_week:
      friendly_name: "Average cooling runtime per day"
      value_template: "{{ ((states('sensor.cooling_time_last_7_days') | float) / 7) | round(1) }}"
      unit_of_measurement: 'h'

    cooling_runtime_today:
      friendly_name: "Cooling runtime today"
      value_template: "{{ (states('sensor.cooling_time_today') | float) | round(1) }}"
      unit_of_measurement: 'h'

    cooling_runtime_yesterday:
      friendly_name: "Cooling runtime yesterday"
      value_template: "{{ (states('sensor.cooling_time_yesterday') | float) | round(1) }}"
      unit_of_measurement: 'h'

    cooling_runtime_week:
      friendly_name: "Cooling runtime last 7 days"
      value_template: "{{ (states('sensor.cooling_time_last_7_days') | float) | round(1) }}"
      unit_of_measurement: 'h'

    avg_heating_week:
      friendly_name: "Average heating runtime per day"
      value_template: "{{ ((states('sensor.heating_time_last_7_days') | float) / 7) | round(1) }}"
      unit_of_measurement: 'h'

    heating_runtime_today:
      friendly_name: "Heating runtime today"
      value_template: "{{ (states('sensor.heating_time_today') | float) | round(1) }}"
      unit_of_measurement: 'h'

    heating_runtime_yesterday:
      friendly_name: "Heating runtime yesterday"
      value_template: "{{ (states('sensor.heating_time_yesterday') | float) | round(1) }}"
      unit_of_measurement: 'h'

    heating_runtime_week:
      friendly_name: "Heating runtime last 7 days"
      value_template: "{{ (states('sensor.heating_time_last_7_days') | float) | round(1) }}"
      unit_of_measurement: 'h'