- alias: Xbox turned on/off
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.xbox
  action:
  - service_template: "script.xbox_{{ trigger.to_state.state }}"


- alias: Turn game room lights on/off at sunset/sunrise
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: binary_sensor.dark_inside
  condition:
  - condition: state
    entity_id: binary_sensor.xbox
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service_template: "script.gr_lights_{{ trigger.to_state.state }}"


- alias: Turn space heater off if on for 2 hours
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.plug_4
    to: 'on'
    for: '02:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.xbox
    state: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id:
    - switch.plug_4
    - climate.space_heater