- alias: Dim lights when LR playing
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'playing'
  - platform: state
    entity_id:
    - media_player.vizio_smartcast
    - sensor.living_room_tv
    to: 'on'
    for: '00:00:01'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: and
      conditions:
      - condition: state
        entity_id: light.right_lamp
        state: 'on'
      - condition: state
        entity_id: light.left_lamp
        state: 'on'
  - condition: template
    value_template: "{{ state_attr('media_player.living_room_tv', 'app_name') == None or state_attr('media_player.living_room_tv', 'app_name')[:3] != 'BOD' }}"
  action:
  - service: script.pre_media


- alias: Restore lights when TV turned off
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - media_player.vizio_smartcast
    - sensor.living_room_tv
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'on'
  - condition: state
    entity_id: light.living_room
    state: 'off'
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service: script.post_media


- alias: Boost TV volume when furnace on - cool
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'cooling'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: media_player.vizio_smartcast
      state: 'on'
    - condition: state
      entity_id: sensor.living_room_tv
      state: 'on'
  action:
  - service: script.tv_vol_up


- alias: Boost TV volume when furnace on - heat
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'heating'
    for: '00:00:15'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: media_player.vizio_smartcast
      state: 'on'
    - condition: state
      entity_id: sensor.living_room_tv
      state: 'on'
  action:
  - service: script.tv_vol_up_heat


- alias: Lower TV volume when furnace off - cool
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'cooling'
    to:
    - 'idle'
    - 'off'
    for: '00:00:15'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: media_player.vizio_smartcast
      state: 'on'
    - condition: state
      entity_id: sensor.living_room_tv
      state: 'on'
  action:
  - service: script.tv_vol_dn


- alias: Lower TV volume when furnace off - heat
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'heating'
    to:
    - 'idle'
    - 'off'
    for: '00:01:30'
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: media_player.vizio_smartcast
      state: 'on'
    - condition: state
      entity_id: sensor.living_room_tv
      state: 'on'
  action:
  - service: script.tv_vol_dn_heat


- alias: Turn soundbar on/off with TV
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - media_player.vizio_smartcast
    - sensor.living_room_tv
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - media_player.vizio_smartcast
    - sensor.living_room_tv
    from: 'on'
    to: 'off'
  action:
  - service_template: >
      {% set trigger = trigger.to_state.state %}
      {% set cast = states('media_player.living_room_tv') %}
      {% if (trigger == 'on' and cast != 'off') or trigger == 'off' %}
        script.soundbar_power
      {% else %}
        script.none
      {% endif %}