automation:
- alias: Matt button
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: sensor.button_matt
    to:
    - 'single'
    - 'double'
    - 'hold'
  action:
  - service: script.turn_on
    data_template:
      entity_id: >
        {% set command = trigger.to_state.state %}
        {% if command == 'single' %}
          {% if is_state('input_boolean.sleep_mode', 'off') %}
            script.good_night{{ '_no_noise' if is_state('input_boolean.andy_sleep', 'on') else '' }}
          {% else %}
            script.{{ 'toggle_bedroom_fan' if is_state('media_player.bedroom_speaker', 'playing') else 'white_noise_bedroom' }}
          {% endif %}
        {% elif command == 'hold' %}
          script.toggle_bedroom_fan
        {% else %}
          script.early_departure
        {% endif %}


- alias: Andy button
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: sensor.button_andy
    to: 
    - 'single'
    - 'hold'
  action:
    service_template: >
      {% if trigger.to_state.state == 'single' %}
        {% if is_state('input_boolean.andy_sleep', 'off') %}
          script.good_night_andy
        {% else %}
          script.toggle_bedroom_fan
        {% endif %}
      {% else %}
        script.button_andy_test
      {% endif %}


script:
  toggle_bedroom_fan:
    sequence:
    - choose:
      - conditions:
        - condition: state
          entity_id: switch.master_bedroom_fan_plug
          state: 'on'
        sequence:
        - service: climate.turn_off
          entity_id: climate.master_bedroom_fan
      - conditions:
        - condition: state
          entity_id: switch.master_bedroom_fan_plug
          state: 'off'
        sequence:
        - service: climate.turn_off
          entity_id: climate.master_bedroom_fan
        - delay: 0.1
        - service: switch.turn_on
          entity_id: switch.master_bedroom_fan_plug
  
  early_departure:
    sequence:
    - service: script.turn_on
      entity_id: script.stop_white_noise
    - service: input_boolean.turn_off
      entity_id:
      - input_boolean.sleep_mode
      - input_boolean.andy_sleep
    - service: light.turn_on
      entity_id: 
      - light.master_bedroom
      - light.living_room_lamps
      - light.buffet
      data:
        transition: 30
        kelvin: 3000
        brightness_pct: 33
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
        brightness_pct: 66
        transition: 1
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home


  button_andy_test:
    sequence:
    - service: notify.gotify
      data:
        message: "Andy's button is working."