automation:
- alias: Matt button
  initial_state: true
  mode: parallel
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: button_single
      device_ieee: !secret button_matt_id
  - platform: event
    event_type: zha_event
    event_data:
      command: button_double
      device_ieee: !secret button_matt_id
  - platform: event
    event_type: zha_event
    event_data:
      command: button_hold
      device_ieee: !secret button_matt_id
  action:
    service_template: >
      {% set command = trigger.event.data.command %}
      {% if command == 'button_single' %}
        {% if is_state('input_boolean.sleep_mode', 'off') %}
          script.good_night{{ '_no_noise' if is_state('input_boolean.andy_sleep', 'on') else '' }}
        {% else %}
          script.{{ 'toggle_bedroom_fan' if is_state('media_player.bedroom_speaker', 'playing') else 'white_noise_bedroom' }}
        {% endif %}
      {% elif command == 'button_double' %}
        script.toggle_bedroom_fan
      {% else %}
        script.early_departure
      {% endif %}


- alias: Lights off backup attempt
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.sleep_mode
    to: 'on'
    for: '00:00:05'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: group.lights_interior
      state: 'on'
    - condition: state
      entity_id: switch.cabinet_lighting
      state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.good_night_no_noise


- alias: Repeat white noise in sleep mode
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.bedroom_speaker
    from: 'playing'
    to: 'idle'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.andy_sleep
      state: 'on'
  action:
  - service: media_player.play_media
    entity_id: media_player.bedroom_speaker
    data:
      media_content_id: !secret white_noise
      media_content_type: audio/mp3


- alias: Stop white noise
  initial_state: true
  trigger:
  - platform: time
    at: '06:20:00'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.andy_sleep
      state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.stop_white_noise


- alias: Reset volume after extra sleep
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.bedroom_speaker
    to:
    - 'idle'
    - 'off'
  - platform: state
    entity_id: media_player.bedroom_speaker
    to: 'paused'
    for: '00:00:15'
  condition:
  - condition: state
    entity_id: input_boolean.extra_sleep
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: 
    - input_boolean.extra_sleep
    - input_boolean.sleep_mode
    - media_player.bedroom_speaker
  - service: media_player.volume_mute
    entity_id: media_player.bedroom_speaker
    data:
      is_volume_muted: true
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom_speaker
      volume_level: 0.4
  - service: media_player.volume_mute
    entity_id: media_player.bedroom_speaker
    data:
      is_volume_muted: false


script:
  good_night:
    alias: Good night
    sequence:
    - service: input_boolean.turn_on
      data_template:
        entity_id: "input_boolean.{{ 'extra_sleep' if 6 <= now().hour < 18 else 'sleep_mode' }}"
    - service: script.turn_on
      entity_id: script.white_noise_bedroom
    - service: homeassistant.turn_off
      entity_id: 
      - light.master_bedroom_night_light
      - group.lights_interior
      - input_boolean.washer
      - input_boolean.dryer
    - service: script.turn_on
      entity_id: 
      - script.media_players_off
      - script.sleep_switches
      - script.porch_light_security
    - service: climate.turn_on
      entity_id: climate.bedroom_fan
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - service: script.alarm_arm_home

  good_night_no_noise:
    alias: Good night routine - no white noise
    sequence:
    - service: homeassistant.turn_off
      entity_id: 
      - group.lights_interior
      - switch.christmas_tree
      - media_player.living_room_vizio
    - service: script.turn_on
      entity_id: script.sleep_switches
    - service: climate.turn_on
      entity_id: climate.bedroom_fan
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.abode

  white_noise_bedroom:
    alias: Play white noise on bedroom speaker
    sequence:
    - service: input_boolean.turn_on
      entity_id: input_boolean.white_noise
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: true
    - service: media_player.turn_on
      entity_id: media_player.bedroom_speaker
    - service: media_player.play_media
      entity_id: media_player.bedroom_speaker
      data:
        media_content_id: 'http://10.0.0.2:8123/local/audio/silence.mp3'
        media_content_type: audio/mp3
    - delay: '00:00:02'
    - service: media_player.volume_set
      entity_id: media_player.bedroom_speaker
      data_template:
        volume_level: "{{ states('input_number.white_noise_vol') | int / 100 }}"
    - delay: '00:00:02'
    - service: media_player.play_media
      entity_id: media_player.bedroom_speaker
      data:
        media_content_id: !secret white_noise
        media_content_type: audio/mp3
    - wait_template: "{{ is_state('media_player.bedroom_speaker', 'playing') }}"
      timeout: '00:00:10'
      continue_on_timeout: true
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: false
    - service: input_boolean.turn_off
      entity_id: input_boolean.white_noise

  stop_white_noise:
    sequence:
    - service: script.turn_on
      entity_id: script.volume_transition_to_zero
    - wait_template: "{{ is_state('script.volume_transition_to_zero', 'off') }}"
      timeout: '00:01:00'
      continue_on_timeout: true
    - service: homeassistant.turn_off
      entity_id: 
      - media_player.bedroom_speaker
      - input_boolean.white_noise
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: true
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_speaker
        volume_level: 0.4
    - service: media_player.volume_mute
      entity_id: media_player.bedroom_speaker
      data:
        is_volume_muted: false

  volume_transition_to_zero:
    sequence:
      repeat:
        sequence:
        - service: media_player.volume_set
          entity_id: media_player.bedroom_speaker
          data_template:
            volume_level: "{{ state_attr('media_player.bedroom_speaker', 'volume_level') | float - 0.01 }}"
        - delay: '0.25'
        until:
        - condition: template
          value_template: "{{ state_attr('media_player.bedroom_speaker', 'volume_level') | float < 0.10 }}"

  media_players_off:
    sequence:
    - service: media_player.turn_off
      entity_id:
      - media_player.bedroom_vizio
      - media_player.living_room_vizio
      - media_player.living_room_speaker
      - media_player.portable_speaker
      - media_player.hub
      - media_player.kitchen_speaker

  sleep_switches:
    sequence:
    - service: homeassistant.turn_off
      entity_id: 
      - switch.cabinet_lighting
      - switch.space_heater
      - switch.air_freshener
      - light.hall_bath_night_light
      - climate.space_heater
    - condition: state
      entity_id: input_boolean.christmas_mode
      state: 'on'
    - service: light.turn_off
      entity_id: switch.christmas_tree

  toggle_bedroom_fan:
    sequence:
    - service_template: "climate.turn_{{ 'off' if not is_state('climate.bedroom_fan', 'off') else 'on' }}"
      entity_id: climate.bedroom_fan
  
  early_departure:
    sequence:
    - service: script.turn_on
      entity_id: script.stop_white_noise
    - service: input_boolean.turn_off
      entity_id:
      - input_boolean.sleep_mode
      - input_boolean.andy_sleep
    - service: light.turn_on
      entity_id: 
      - light.master_bedroom
      - light.living_room_lamps
      - light.buffet
      data:
        transition: 30
        kelvin: 3000
        brightness_pct: 33
    - service: switch.turn_on
      entity_id: switch.cabinet_lighting    


input_number:
  white_noise_vol:
    name: White noise volume
    min: 40
    max: 80
    step: 2
    unit_of_measurement: '%'
    mode: slider


input_boolean:
  sleep_mode:
  extra_sleep:
  white_noise: