automation:
- alias: Cross stitch button
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.living_room_lamp_button
    to:
    - 'on'
    - 'off'
  action:
  - service: light.turn_on
    entity_id: light.right_lamp
    data:
      brightness_pct: "{{ 0 if is_state('light.right_lamp', 'on') else 100 }}"
      kelvin: 3000


- alias: Side entrance doorbell
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.side_entrance_doorbell
    to:
    - 'on'
    - 'off'
  action:
  - service: switch.turn_on
    entity_id: 
    - switch.main_floor_chime_double_beep # cut off early so that it only beeps once
    - switch.basement_chime_double_beep