### See button 1 package for related scripts
automation:
- alias: Andy button
  initial_state: true
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      command: button_single
      device_ieee: !secret button_2_id
  action:
    service_template: >
      {% if is_state('input_boolean.andy_sleep', 'off') %}
        script.good_night{{ '_andy' if is_state('device_tracker.pixel_xl', 'home') else '' }}
      {% else %}
        script.toggle_bedroom_fan
      {% endif %}


script:
  good_night_andy:
    sequence:
    - service: homeassistant.turn_off
      entity_id:
      - light.master_bedroom
      - media_player.bedroom_vizio
    - service: script.white_noise_bedroom
    - service: input_boolean.turn_on
      entity_id: input_boolean.andy_sleep
    - condition: state
      entity_id: light.game_room
      state: 'on'
    - service: script.porch_light_security
    - service: light.turn_off
      entity_id: 
      - light.living_room
      - light.dining_room

input_boolean:
  andy_sleep: