automation:
- alias: Cross stitch button
  id: 'iehohd7Veiwi8yiegooth7'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.living_room_lamp_button
    to:
    - 'on'
    - 'off'
  action:
  - service: light.turn_on
    entity_id: light.right_lamp
    data:
      brightness_pct: "{{ 0 if is_state('light.right_lamp', 'on') else 100 }}"
      kelvin: 3000


- alias: Basement lamp button
  id: 'cahgha9pol7riaHu5sei6k'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.basement_lamp_button_action
    to:
    - 'on'
    - 'off'
  action:
  - service: light.toggle
    entity_id: light.basement_lamps
    data:
      brightness_pct: 100
      kelvin: 2200