# For living room fan

automation:
- alias: Living room fan remote
  initial_state: true
  trigger:
  # First button: Turn fan on
  - platform: event
    event_type: zha_event
    event_data:
      command: 'off'
      device_ieee: !secret eco_remote_3_id
  - platform: event
    event_type: zha_event
    event_data:
      command: 'on'
      device_ieee: !secret eco_remote_3_id
  # Third button: Change fan speed
  - platform: event
    event_type: zha_event
    event_data:
      command: 'move_to_color_temp'
      device_ieee: !secret eco_remote_3_id
  action:
  - service_template: >
      {% set command = trigger.event.data.command %}
      {% if command in ['on', 'off'] %}
        script.fan_power
      {% else %}
        script.fan_speed
      {% endif %}