# On game room desk
# Some related scripts in eco_remote_1 package

automation:
- alias: Game room desk remote
  initial_state: true
  trigger:
  # First button: Turn desktop on
  - platform: event
    event_type: zha_event
    event_data:
      command: 'off'
      device_ieee: !secret eco_remote_2_id
  - platform: event
    event_type: zha_event
    event_data:
      command: 'on'
      device_ieee: !secret eco_remote_2_id
  # Second button: Mute/unmute portable speaker
  - platform: event
    event_type: zha_event
    event_data:
      command: 'move_to_level'
      device_ieee: !secret eco_remote_2_id
  # Third button: Move music between all speakers and portable speaker
  - platform: event
    event_type: zha_event
    event_data:
      command: 'move_to_color_temp'
      device_ieee: !secret eco_remote_2_id
  action:
  - service_template: >
      {% set command = trigger.event.data.command %}
      {% if command in ['on', 'off'] %}
        script.wake_laptop
      {% elif command == 'move_to_color_temp' %}
        script.move_music_{{ 'all' if is_state('media_player.portable_speaker', 'playing') else 'portable' }}
      {% else %}
        script.toggle_mute_portable_speaker
      {% endif %}


script:
  toggle_mute_portable_speaker:
    sequence:
    - service: media_player.volume_mute
      entity_id: media_player.portable_speaker
      data_template:
        is_volume_muted: "{{ false if state_attr('media_player.portable_speaker', 'is_volume_muted') else true }}"