automation:
- alias: Game room fan remote
  initial_state: true
  mode: parallel
  trigger:
  # First button: Turn fan on
  - platform: event
    event_type: zha_event
    event_data:
      command: 'off'
      device_ieee: !secret eco_remote_3_id
  - platform: event
    event_type: zha_event
    event_data:
      command: 'on'
      device_ieee: !secret eco_remote_3_id
  # Third button: Change fan speed
  - platform: event
    event_type: zha_event
    event_data:
      command: 'move_to_color_temp'
      device_ieee: !secret eco_remote_3_id
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: "{{ trigger.event.data.command in ['on', 'off'] }}"
      sequence:
      - service_template: "{{ 'fan.turn_on' if is_state('climate.game_room_fan', 'off') else 'climate.turn_off' }}"
        data_template:
          entity_id: "{{ 'fan.game_room' if is_state('climate.game_room_fan', 'off') else 'climate.game_room_fan' }}"
    - conditions:
      - condition: template
        value_template: "{{ trigger.event.data.command == 'move_to_color_temp' }}"
      sequence:
      - service: remote.send_command
        entity_id: remote.game_room
        data:
          device: honeywell fan
          command: speed