script:
  controller_battery_changed:
    sequence:
    - service: input_text.set_value
      entity_id: input_text.controller_battery_changed
      data_template:
        value: "{{ now() }}"


sensor:
- platform: history_stats
  name: Play time
  entity_id: binary_sensor.xbox
  state: 'on'
  type: time
  start: "{{ as_timestamp(states('input_text.controller_battery_changed')) }}"
  end: "{{ now() }}"

- platform: template
  sensors:
    controller_battery:
      friendly_name: Play time
      value_template: "{{ states('sensor.play_time') | float | round(1) }}"
      unit_of_measurement: 'h'


input_text:
  controller_battery_changed: