- alias: Turn entrance light on before sound check
  initial_state: true
  trigger:
  - platform: time
    at: '06:55:00'
  condition:
  - condition: time
    weekday: sun
  - condition: template
    value_template: "{{ state_attr('calendar.church', 'message') != None and 'sound check' in state_attr('calendar.church', 'message').lower() }}"
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%-d') == as_timestamp(state_attr('calendar.church', 'start_time')) | timestamp_custom('%-d') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1


- alias: Turn entrance light on before work
  initial_state: true
  trigger:
    platform: time
    at: '07:25:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%-d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%-d') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1


- alias: Turn entrance light off
  initial_state: true
  trigger:
    platform: time
    at: '07:50:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%-d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%-d') }}"
  action:
  - service: switch.turn_off
    entity_id: switch.light_switch_1


- alias: Turn entrance light on before rehearsal
  initial_state: true
  trigger:
  - platform: template
    value_template: "{{ state_attr('calendar.church', 'message') != None and 'rehearsal' in state_attr('calendar.church', 'message').lower() and ((as_timestamp(state_attr('calendar.church', 'start_time')) - 1800) == as_timestamp(states('sensor.date_time_iso'))) }}"
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1


- alias: Turn front closet light on/off
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.front_closet
  action:
  - service_template: "script.front_closet_{{ trigger.to_state.state }}"