- alias: Turn entrance light on before sound check
  initial_state: true
  trigger:
  - platform: time
    at: '06:55:00'
  condition:
  - condition: time
    weekday: sun
  - condition: template
    value_template: "{{ state_attr('calendar.church', 'message') != None and 'sound check' in state_attr('calendar.church', 'message').lower() }}"
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%-d') == as_timestamp(state_attr('calendar.church', 'start_time')) | timestamp_custom('%-d') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1


- alias: Turn entrance light on/off before work
  initial_state: true
  trigger:
  - platform: time
    at: '07:25:00'
  - platform: time
    at: '07:45:00'
  condition:
  - condition: template
    value_template: "{{ is_state_attr('calendar.work', 'message', 'Work') and as_timestamp(now()) | timestamp_custom('%-d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%-d') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service_template: "switch.turn_{{ 'on' if as_timestamp(now()) | timestamp_custom('%M') == '25' else 'off' }}"
    entity_id: switch.light_switch_1


- alias: Turn entrance light on before rehearsal
  initial_state: true
  trigger:
  - platform: template
    value_template: "{{ state_attr('calendar.church', 'message') != None and 'rehearsal' in state_attr('calendar.church', 'message').lower() and ((as_timestamp(state_attr('calendar.church', 'start_time')) - 1800) == as_timestamp(states('sensor.date_time_iso'))) }}"
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: switch.turn_on
    entity_id: switch.light_switch_1


- alias: Turn front closet light on/off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.front_closet
  action:
  - service: light.turn_on
    entity_id: light.front_closet
    data_template:
      brightness_pct: >
        {% set hour = now().hour | int %}
        {% if trigger.to_state.state == 'on' %}
          {{ 75 if 7 >= hour >= 21 else 100 }}
        {% else %}
          0
        {% endif %}
      transition: 0.4


- alias: Turn off front closet light after power outage
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.front_closet
    to: 'on'
    for: '00:00:01'
  condition:
  - condition: state
    entity_id: binary_sensor.front_closet
    state: 'off'
  action:
  - service: light.turn_off
    entity_id: light.front_closet