- alias: Xbox turned on/off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.xbox
  action:
  - service_template: "script.xbox_{{ trigger.to_state.state }}"


- alias: Turn game room lights on/off at sunset/sunrise
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.dark_inside
  condition:
  - condition: state
    entity_id: binary_sensor.xbox
    state: 'on'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service_template: "script.gr_lights_{{ trigger.to_state.state }}"


- alias: Game room dimmer off press
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.game_room_remote
    to: 
    - 4_click
    - 4_click_up
  condition:
  - condition: state
    entity_id: binary_sensor.xbox
    state: 'on'
  action:
  - service: script.xbox_off


- alias: Change lights based on Internet connectivity
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.internet
  condition:
  - condition: state
    entity_id: light.game_room
    state: 'on'
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Game room
      scene_name: "{{ 'Legendary' if trigger.to_state.state == 'off' else 'Read' }}"