- alias: Turn off lights with TV
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - sensor.living_room_vizio_app_name
    - sensor.living_room_cast_app_name
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state not in ['', 'BOD Receiver PROD', 'SmartCast Home', 'unknown', '_UNKNOWN_APP'] }}"
  action:
  - service: script.pre_media


- alias: Restore lights when TV turned off
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.living_room_vizio
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: sensor.living_room_vizio_app_name
    to: 'SmartCast Home'
  - platform: state
    entity_id: media_player.living_room_cast
    from:
    - 'playing'
    - 'paused'
    - 'idle'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  - condition: state
    entity_id: light.living_room
    state: 'off'
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: script.post_media


- alias: Boost TV volume when furnace on
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'cooling'
  - platform: state
    entity_id: sensor.hvac_action
    to: 'heating'
    for: '00:01:00'
  condition:
  - condition: state
    entity_id: media_player.living_room_vizio
    state: 'on'
  - condition: template
    value_template: "{{ not is_state_attr('media_player.living_room_vizio', 'app_name', 'SmartCast Home') }}"
  action:
  - service_template: "script.tv_vol_up_{{ trigger.to_state.state[:4] }}"


- alias: Lower TV volume when furnace off
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'cooling'
    to:
    - 'idle'
    - 'off'
    for: '00:00:45'
  - platform: state
    entity_id: sensor.hvac_action
    from: 'heating'
    to:
    - 'idle'
    - 'off'
    for: '00:02:00'
  condition:
  - condition: state
    entity_id: media_player.living_room_vizio
    state: 'on'
  action:
  - service_template: "script.tv_vol_dn_{{ trigger.from_state.state[:4] }}"