- alias: Turn off lights with TV
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.living_room_vizio
    to: 'on'
    for: '00:00:01'
  condition:
  - condition: state
    entity_id: light.living_room_lamps
    state: 'on'
  - condition: template
    value_template: "{{ state_attr('media_player.living_room_tv', 'app_name') == None or state_attr('media_player.living_room_tv', 'app_name')[:3] != 'BOD' }}"
  action:
  - service: script.pre_media


- alias: Restore lights when TV turned off
  initial_state: true
  trigger:
  - platform: state
    entity_id: media_player.living_room_vizio
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.dark_inside
    state: 'on'
  - condition: state
    entity_id: light.living_room
    state: 'off'
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: script.post_media


- alias: Boost TV volume when furnace on
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'cooling'
  - platform: state
    entity_id: sensor.hvac_action
    to: 'heating'
    for: '00:00:55'
  condition:
  - condition: state
    entity_id: media_player.living_room_vizio
    state: 'on'
  action:
  - service_template: "script.tv_vol_up_{{ trigger.to_state.state[:4] }}"


- alias: Lower TV volume when furnace off
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'cooling'
    to:
    - 'idle'
    - 'off'
    for: '00:00:35'
  - platform: state
    entity_id: sensor.hvac_action
    from: 'heating'
    to:
    - 'idle'
    - 'off'
    for: '00:01:25'
  condition:
  - condition: state
    entity_id: media_player.living_room_vizio
    state: 'on'
  action:
  - service_template: "script.tv_vol_dn_{{ trigger.from_state.state[:4] }}"


- alias: Update living room TV status faster
  trigger:
  - platform: time_pattern
    seconds: '/5'
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  action:
  - service: homeassistant.update_entity
    entity_id: media_player.living_room_vizio