- alias: Good morning - workday
  initial_state: true
  trigger:
  - platform: time
    at: '06:50:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') == as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') }}"
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: script.good_morning
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  - service: script.lights_sunset


- alias: Turn fan off at 7:15am on day off
  initial_state: true
  trigger:
  - platform: time
    at: '07:15:00'
  condition:
  - condition: template
    value_template: "{{ as_timestamp(now()) | timestamp_custom('%d') != as_timestamp(state_attr('calendar.work', 'start_time')) | timestamp_custom('%d') }}"
  action:
  - service: homeassistant.turn_off
    entity_id:
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep
    - climate.bedroom_fan