- alias: Set speaker volume based on app
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - sensor.portable_speaker_app_name
    - sensor.bedroom_speaker_app_name
    - sensor.hub_app_name
    - sensor.kitchen_speaker_app_name
    - sensor.living_room_speaker_app_name
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state not in ['', 'Default Media Receiver'] }}"
  - condition: state
    entity_id: input_boolean.andy_sleep
    state: 'off'
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: "media_player.{{ trigger.to_state.name.lower().replace(' ','_') }}"
      volume_level: >
        {% set app = trigger.to_state.state %}
        {% set speaker = trigger.to_state.entity_id.replace('sensor.','').replace('_speaker','').replace('_app_name','').replace('_',' ') %}
        {% if app in ['iHeartRadio'] %}
          {% if speaker in ['portable', 'living room'] %}
            0.45
          {% elif speaker in ['bedroom', 'kitchen'] %}
            0.4
          {% elif speaker in ['hub'] %}
            0.5
          {% else %}
            0.4
          {% endif %}
        {% elif app in ['Google Play Music', 'Spotify'] %}
          {% if speaker in ['bedroom', 'kitchen', 'living room'] %}
            0.36
          {% elif speaker in ['portable'] %}
            0.3
          {% elif speaker in ['hub'] %}
            0.4
          {% else %}
            0.36
          {% endif %}
        {% else %}
          0.4
        {% endif %}


- alias: Boost speaker volume when furnace on
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    to: 'cooling'
  - platform: state
    entity_id: sensor.hvac_action
    to: 'heating'
    for: '00:00:43'
  - platform: state
    entity_id: media_player.living_room_speaker
    to: 'playing'
  condition:
  - condition: state
    entity_id: sensor.hvac_action
    state: 'cooling'
  - condition: state
    entity_id: sensor.hvac_action
    state: 'heating'
    for: '00:00:43'
  - condition: template
    value_template: "{{ is_state('media_player.living_room_speaker', 'playing') }}"
  - condition: state
    entity_id: binary_sensor.quiet_hours
    state: 'off'
  action:
  - service: media_player.volume_set
    entity_id: media_player.living_room_speaker
    data_template:
      volume_level: >
        {% set app = states('sensor.living_room_speaker_app_name') %}
        {% if app in ['iHeartRadio', 'Default Media Receiver'] %}
          0.5
        {% else %}
          0.42
        {% endif %}


- alias: Lower speaker volume when furnace off
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.hvac_action
    from: 'cooling'
    to:
    - 'idle'
    - 'off'
    for: '00:00:43'
  - platform: state
    entity_id: sensor.hvac_action
    from: 'heating'
    to:
    - 'idle'
    - 'off'
    for: '00:01:28'
  condition:
  - condition: state
    entity_id: binary_sensor.quiet_hours
    state: 'off'
  - condition: template
    value_template: "{{ states('media_player.living_room_speaker') in ['playing', 'paused'] }}"
  action:
    service: media_player.volume_set
    entity_id: media_player.living_room_speaker
    data_template:
      volume_level: >
        {% set app = states('sensor.living_room_speaker_app_name') %}
        {% if app == 'iHeartRadio' %}
          0.45
        {% else %}
          0.36
        {% endif %}