automation:
- alias: Toggle update boolean
  id: 'quei8ThaaCie7Oosh2eefe'
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.hass_update
  action:
  - service: "input_boolean.turn_{{ 'off' if is_state('sensor.hass_update', 'Newest') else 'on' }}"
    entity_id: input_boolean.hass_update


- alias: Notify when beta available
  id: 'eNoh0aumoo7Do0oGhu0leh'
  initial_state: true
  trigger:
  - platform: template
    value_template: "{{ states('sensor.latest_version').find('b') != -1 }}"
  condition:
  - condition: state
    entity_id: input_boolean.notify_all_updates
    state: 'off'
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unknown' }}"
  - condition: template
    value_template: "{{ trigger.to_state.state != 'unavailable' }}"
  - condition: template
    value_template: "{{ trigger.from_state.state.find('b') == -1 }}"
  action:
  - service: notify.gotify
    data:
      title: "Home Assistant beta is available!"
      message: "{{ states('sensor.latest_version') }} is now available."


- alias: Notify for all updates
  id: 'zoor0aXizookeeto0iohee'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.latest_version
  condition:
  - condition: state
    entity_id: input_boolean.notify_all_updates
    state: 'on'
  - condition: template
    value_template: "{{ trigger.from_state.state != 'unknown' }}"
  action:
  - service: notify.gotify
    data:
      title: "Home Assistant update available!"
      message: "{{ states('sensor.latest_version') }} is now available."


sensor:
- platform: template
  sensors:
    hass_update:
      friendly_name: "Update notification"
      value_template: >
        {% set current = states('sensor.current_version') %}
        {% set latest = states('sensor.latest_version') %}
        {% set current_int = current[:9].replace('.','') | int(0) %}
        {% set latest_int = latest[:9].replace('.','') | int(0) %}
        {% if current.find('b') != -1 and latest.find('b') != -1 %}
          {% if latest[latest.find('b') + 1] | float(0) > current[current.find('b') + 1] | float(0) %}
            {{ latest }} is available, and you are running {{ current }}.
          {% else %}
            Newest
          {% endif %}
        {% elif current.find('b') == -1 and latest.find('b') != -1 %}
          {% if latest_int | float(0) > current_int %}
            {{ latest }} is available, and you are running {{ current }}.
          {% else %}
            Newest
          {% endif %}
        {% elif current.find('b') != -1 and latest.find('b') == -1 %}
          {% if latest_int | float(0) > current_int %}
            {{ latest }} is available, and you are running {{ current }}.
          {% else %}
            Newest
          {% endif %}
        {% else %}
          {% if latest_int > current_int %}
            {{ latest }} is available, and you are running {{ current }}.
          {% else %}
            Newest
          {% endif %}
        {% endif %}


input_boolean:
  hass_update:
  notify_all_updates: