automation:
- alias: Process incoming SMS
  id: 'process-incoming-sms'
  initial_state: true
  mode: parallel
  trigger:
  - platform: event
    event_type: netgear_lte_sms
  action:
  - service: notify.gotify
    data:
      title: "SMS from {{ trigger.event.data.from }}"
      message: "{{ trigger.event.data.message }}"
  - service: netgear_lte.delete_sms
    data:
      host: "{{ trigger.event.data.host }}"
      sms_id: "{{ trigger.event.data.sms_id }}"