automation:
- alias: Record washer/dryer on/off
  id: 'ahCh5iehugh6laesheeWe8'
  initial_state: true
  mode: parallel
  trigger:
  - platform: numeric_state
    entity_id: sensor.washer_pwr
    above: 500
  - platform: numeric_state
    entity_id: sensor.washer_pwr
    below: 3
    for: '00:03:00'
  - platform: numeric_state
    entity_id: sensor.dryer_power
    above: 250
    for: '00:00:30'
  - platform: numeric_state
    entity_id: sensor.dryer_power
    below: 50
  action:
  - service: "input_boolean.turn_{{ 'on' if trigger.to_state.state | float(0) > 250 else 'off' }}"
    data:
      entity_id: "input_boolean.{{ trigger.to_state.object_id.replace('_power','').replace('_pwr','') }}"


- alias: Notify when washer/dryer done
  id: 'ieJ7eitheen4xithoe0ohd'
  initial_state: true
  mode: parallel
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.washer
    - input_boolean.dryer
    from: 'on'
    to: 'off'
  - platform: state
    entity_id:
    - input_boolean.washer_reminder
    - input_boolean.dryer_reminder
    to: 'on'
    for: '00:30:00'
  condition:
  - condition: template
    value_template: "{{ states('input_text.alarm') in ['armed_home', 'disarmed'] }}"
  - condition: state
    entity_id: 
    - input_boolean.sleep_mode
    - input_boolean.andy_sleep
    state: 'off'
  action:
  - service: notify.gotify
    data:
      title: "{{ trigger.to_state.name }} done {{ 'reminder' if 'reminder' in trigger.to_state.entity_id else '' }}"
      message: "{{ 'Move clothes to the dryer.' if trigger.to_state.name == 'Washer' else 'Put your clothes away.' }}"
  - service: notify.mobile_app_andys_iphone
    data:
      title: "{{ trigger.to_state.name }} done {{ 'reminder' if 'reminder' in trigger.to_state.entity_id else '' }}"
      message: "{{ 'Move clothes to the dryer.' if trigger.to_state.name == 'Washer' else 'Put your clothes away.' }}"
  - service: "input_boolean.turn_{{ 'on' if 'reminder' not in trigger.to_state.entity_id else 'off' }}"
    data:
      entity_id: "{{ trigger.to_state.entity_id }}{{ '_reminder' if 'reminder' not in trigger.to_state.entity_id else '' }}"


- alias: Reset laundry reminder booleans
  id: 'Ieguvaicood1xeeJu5eeM6'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - binary_sensor.laundry_room_door_front
    - binary_sensor.laundry_room_door_back
    - binary_sensor.laundry_room_motion
    - binary_sensor.laundry_room_motion_back
    - input_boolean.sleep_mode
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_text.alarm
    to: 'armed_away'
  action:
  - service: input_boolean.turn_off
    entity_id:
    - input_boolean.washer_reminder
    - input_boolean.dryer_reminder


mqtt:
  sensor:
  - name: Washer pwr
    state_topic: 'washer/power'
    availability_topic: 'tele/washer/LWT'
    payload_available: "Online"
    payload_not_available: "Offline"
    unit_of_measurement: 'W'


input_boolean:
  washer:
    name: Washer
  dryer:
    name: Dryer
  washer_reminder:
    name: Washer
  dryer_reminder:
    name: Dryer