automation:
- alias: Turn off lights and speakers when TV turned on
  id: 'turn_off_lights_speakers_tv_on'
  initial_state: true
  trigger:
  - platform: state
    entity_id: &lr_tv media_player.living_room_tv
    to: 'on'
  action:
  - service: script.turn_on
    entity_id: 
    - script.pre_media
    - script.ir_soundbar_vol_up


- alias: Restore lights when TV turned off
  id: 'wuudeaC1Ooyaiphe3uwaPh'
  initial_state: true
  trigger:
  - platform: state
    entity_id: *lr_tv
    from: 'on'
    to: 'off'
  condition:
  - condition: template
    value_template: "{{ states('input_text.alarm') in ['armed_home', 'armed_night', 'disarmed'] }}"
  action:
  - service: light.turn_off
    entity_id: light.living_room_bias_lighting
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  - condition: state
    entity_id: 
    - light.living_room_lamps
    - input_boolean.andy_sleep
    - input_boolean.sleep_mode
    state: 'off'
  - service: script.turn_on
    entity_id: script.post_media


# - alias: Record when LR IR received
#   id: 'record-lr-ir-received'
#   initial_state: true
#   mode: single
#   trigger:
#   - platform: state
#     entity_id: sensor.lr_ir_received
#   action: 
#   - service: input_text.set_value
#     entity_id: input_text.lr_ir_received
#     data:
#       value: "{{ trigger.to_state.state }}"
#   - delay: 0.5
#   - service: input_text.set_value
#     entity_id: input_text.lr_ir_received
#     data:
#       value: ' '


# - alias: Turn off lights and speakers when TV turned on with IR
#   id: 'esaengaH9lei7ahGhohfoh'
#   initial_state: true
#   mode: single
#   trigger:
#   - platform: state
#     entity_id: &lr_ir sensor.lr_ir_received
#     to: &ir_codes
#     # - '0XD5F2A' # Power (Google TV)
#     - '0X20DF10EF' # Power
#     - '0X20DFD728' # Netflix
#     - '0X00FF827D'
#   condition:
#   - condition: state
#     entity_id: *lr_tv
#     state:
#     - 'off'
#     - 'unavailable'
#   action:
#   - service: script.turn_on
#     entity_id: 
#     - script.pre_media
#     - script.ir_soundbar_vol_up
#   - service: homeassistant.reload_config_entry
#     data:
#       entry_id: 'c1b22a0aa916a426315558917f5182a1'


# - alias: Change living room TV auto-brightness
#   id: 'lr-tv-auto-brightness'
#   initial_state: true
#   trigger:
#   - platform: state
#     entity_id: &lr_tv_brightness_entities
#     - *lr_tv
#     - input_boolean.dark_inside
#     to: 'on'
#   condition:
#   - condition: state
#     entity_id: *lr_tv_brightness_entities
#     state: 'on'
#   action:
#   - service: script.turn_on
#     entity_id: script.lr_tv_auto_brightness


# - alias: Turn lights back on with TV IR
#   id: 'Ook9zahch9eish9Cheeroo'
#   initial_state: true
#   mode: single
#   trigger:
#   - platform: state
#     entity_id: *lr_ir
#     to: '0X20DF10EF'
#   condition:
#   - condition: state
#     entity_id: 
#     - *lr_tv
#     - input_boolean.dark_inside
#     state: 'on'
#   action:
#   - service: input_boolean.turn_on
#     entity_id: input_boolean.lr_tv_ir
#   - service: script.turn_on
#     entity_id: script.post_media


script:
  pre_media:
    alias: Turn stuff off when TV turned on
    sequence:
    - service: input_boolean.turn_off
      entity_id: input_boolean.lr_tv_ir
    - condition: state
      entity_id: input_boolean.dark_inside
      state: 'on'
    - service: light.turn_on
      entity_id: light.living_room_bias_lighting
      data:
        brightness_pct: 100
    - service: media_player.turn_off
      entity_id: media_player.kitchen_speaker
    - condition: state
      entity_id: light.living_room_lamps
      state: 'on'
    - service: light.turn_off
      entity_id:
      - light.living_room_lamps
      - light.entrance_lamp
      - light.the_loop
      data:
        transition: 2

  post_media:
    alias: Turn lights back on when TV turned off
    sequence:
    - service: light.turn_on
      data:
        entity_id: >
          light.buffet, light.cabinet_lights, light.entrance_lamp, light.the_loop
          {{- ', light.living_room_lamps' if is_state('light.living_room_lamps', 'off') else '' -}}
        brightness_pct: 100
        kelvin: 2700
        transition: 6
    - service: light.turn_off
      entity_id: light.living_room_bias_lighting
    - service: input_boolean.turn_off
      entity_id: input_boolean.lr_tv_ir


mqtt:
  sensor:
  - name: LR IR received
    state_topic: 'living_room/ir_received'

# input_text:
#   lr_ir_received:
#     name: Living room IR received

input_boolean:
  lr_tv_ir: