automation:
- alias: Notify when server CPU hot
  id: 'Wievoh1ii0phodei'
  initial_state: true
  trigger:
  - platform: template
    value_template: "{{ states('sensor.server_cpu_temp') | int(0) > 70 }}"
    for: '00:05:00'
  action:
  - service: notify.gotify_high
    data:
      title: "Server CPU temperature elevated"
      message: "CPU temperature has been above 70 °C for more than five minutes."


- alias: Notify when Home Assistant starts
  id: 'yo9Ju1Au6daePhaH'
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.gotify
    data:
      message: "Home Assistant started"
  - wait_template: "{{ is_state('persistent_notification.config_entry_discovery', 'notifying') }}"
    timeout: "00:01:00"
    continue_on_timeout: false
  - service: persistent_notification.dismiss
    data:
      notification_id: config_entry_discovery


- alias: Dismiss discovery notification
  id: 'mieGhe9xai9lieco'
  initial_state: true
  trigger:
    platform: state
    entity_id: persistent_notification.config_entry_discovery
    to: 'notifying'
  action:
    service: persistent_notification.dismiss
    data:
      notification_id: config_entry_discovery


- alias: Notify if IPv6 address changes
  id: 'ahRau6IuquahTh1n'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.server_ipv6_address
  condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != '' and trigger.from_state.state != '' }}"
  action:
  - service: notify.gotify
    data:
      title: "Server IPv6 address changed"
      message: "Check Home Assistant for details."
  - service: persistent_notification.create
    data_template:
      title: "Server IPv6 address changed"
      message: "IPv6 address is now {{ states('sensor.server_ipv6_address') }}."


- alias: Record internet outage
  id: 'WooWir8etaithoaz'
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.internet
    from: 
    - 'on'
    - 'off'
    to: 
    - 'off'
    - 'on'
    for: '00:00:40'
  action:
  - service_template: "input_boolean.turn_{{ trigger.to_state.state }}"
    entity_id: input_boolean.internet


- alias: Notify when internet out/restored
  id: 'quei5bohN1Ue0rip'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.internet
  action:
  - service: script.sms_send
    data_template:
      number: !secret phone_matt
      message: "Internet connection {{ 'lost' if trigger.to_state.state == 'off' else 'restored' }}."


- alias: Notify when Paygo balance low
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.paygo_balance
    below: 3
  action:
  - service: notify.gotify
    data:
      title: Paygo balance below $3
      message: Reload your Paygo balance as soon as possible.


input_boolean:
  internet: