automation:
- alias: Notification ACKs
  id: 'aicuo9oosoh3iquooTahge'
  initial_state: true
  trigger:
  - platform: webhook
    webhook_id: !secret ack0
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: &webhook-bool "input_boolean.{{ trigger.webhook_id }}"
  - delay: 15
  - service: input_boolean.turn_off
    data:
      entity_id: *webhook-bool


input_boolean:
  fridge_temp_ack: