automation:
- alias: Andy button
  id: 'Sheiqueer6sheex5zie9ai'
  initial_state: true
  mode: parallel
  trigger: &andy_triggers
  - platform: state
    id: single
    entity_id: &andy_button sensor.andy_button_action
    to: 
    - 'on'
    - 'off'
  - platform: state
    id: hold
    entity_id: *andy_button
    to: 
    - 'brightness_move_up'
    - 'brightness_move_down'
  action:
    service: >
      {% if trigger.id == 'single' %}
        {% if is_state('input_boolean.andy_sleep', 'off') %}
          script.good_night_andy
        {% else %}
          script.toggle_bedroom_fan
        {% endif %}
      {% else %}
        script.good_night{{ '_no_noise' if is_state('input_boolean.andy_sleep', 'on') else '' }}
      {% endif %}


- alias: Matt button
  id: 'iep4tahz8sah7riet7maiJ'
  initial_state: true
  mode: parallel
  trigger: &matt_triggers
  - platform: state
    id: single
    entity_id: &matt_button sensor.matt_button_action
    to: 'single'
  - platform: state
    id: hold
    entity_id: *matt_button
    to: 'hold'
  action:
  - service: script.turn_on
    data:
      entity_id: >
        {% if trigger.id == 'single' %}
          {% if is_state('input_boolean.sleep_mode', 'off') %}
            script.good_night{{ '_no_noise' if is_state('input_boolean.andy_sleep', 'on') else '' }}
          {% else %}
            script.{{ 'toggle_bedroom_fan' if is_state('media_player.bedroom_speaker', 'playing') else 'white_noise_bedroom' }}
          {% endif %}
        {% else %}
          script.toggle_bedroom_fan
        {% endif %}


script:
  toggle_bedroom_fan:
    sequence:
    - service: switch.toggle
      entity_id: switch.bedroom_fan

  early_departure:
    sequence:
    - service: media_player.turn_off
      entity_id:
      - media_player.bedroom_speaker
      - media_player.guest_bedroom_clock
    - service: input_boolean.turn_off
      entity_id:
      - input_boolean.sleep_mode
      - input_boolean.andy_sleep
      - input_boolean.white_noise
    - service: light.turn_on
      entity_id: 
      - light.main_bedroom_lamps
      - light.living_room_lamps
      - light.buffet
      data:
        transition: 30
        kelvin: 3000
        brightness_pct: 50
    - service: light.turn_on
      entity_id: light.cabinet_lights
      data:
        brightness_pct: 66
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home