automation:
- alias: Master bedroom remote main
  id: 'tohx5be8hahLa2yaeVexai9uv'
  initial_state: true
  mode: queued
  trigger:
  - platform: state
    entity_id: sensor.master_bedroom_remote_action
    to:
    - 'on_press'
    - 'off_press'
    - 'up_press'
    - 'down_press'
  action:
  - if:
    - "{{ trigger.to_state.state == 'on_press' }}"

    # using Zigbee scenes turns the lights on at the desired color without
    # turning on at the previous color and transitioning to the new color
    then:
    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/Matt/set'
        payload: &payload >
          {% if is_state('input_boolean.dark_inside', 'on') %}
            {% if now().hour > 21 or now().hour < 6 %}
              {# warm white at 67% brightness #}
              {% set scene_id = 3 %}
            {% else %}
              {# warm white at 100% brightness #}
              {% set scene_id = 2 %}
            {% endif %}
          {% else %}
            {# cool white at 100% brightness #}
            {% set scene_id = 1 %}
          {% endif %}
          {"scene_recall": {{ scene_id }}}

    - service: mqtt.publish
      data:
        topic: 'zigbee2mqtt/Andy/set'
        payload: *payload

    else:
    # when brightness up/down buttons or off button is pressed
    - service: light.turn_on
      data:
        brightness: >
          {% set hour = now().hour %}
          {% set light = states('light.master_bedroom_lamps') %}
          {% set trig = trigger.to_state.state %}
          {% set brt = state_attr('light.master_bedroom_lamps', 'brightness') | int(0) %}
          {% if trig == 'off_press' %}
            0
          {% else %}
            {% if light %}
              {% if trig == 'up_press' and brt < 231 %}
                {{ brt + 25 }}
              {% elif trig == 'down_press' and brt > 25 %}
                {{ brt - 25 }}
              {% else %}
                {{ brt }}
              {% endif %}
            {% endif %}
          {% endif %}
        entity_id: &br_lamps light.master_bedroom_lamps
        transition: 0.5


light:
- platform: group
  name: Master bedroom lamps
  entities:
  - light.andy
  - light.matt