automation:
- alias: Andy's desk remote
  id: 'AeGh4fuos1theiroej4zie'
  initial_state: true
  trigger:
  - platform: state
    entity_id: sensor.andy_office_remote_action
    to: &remote_states
    - 'on'
    - 'off'
    - 'brightness_down'
    - 'brightness_move_down'
    - 'brightness_move_up'
    - 'brightness_up'
    - 'colortemp_up'
    - 'colortemp_down'
  action:
  - choose:
    - conditions:
      - "{{ trigger.to_state.state in ['on', 'off'] }}"
      sequence:
      - service: media_player.turn_off
        entity_id: media_player.andy_office_hub
    - conditions:
      - "{{ 'brightness' in trigger.to_state.state }}"
      sequence:
      - service: script.turn_on
        entity_id: script.toggle_mute_craft_room_speaker
    - conditions:
      - "{{ 'colortemp' in trigger.to_state.state }}"
      sequence:
      - service: light.toggle
        entity_id: light.andy_office
        data:
          brightness_pct: 100
          kelvin: 2200


light:
- platform: group
  name: Andy office
  entities:
  - light.andy_desk
  - light.andy_shelf_lamp


script:
  toggle_mute_craft_room_speaker:
    sequence:
    - choose:
      - conditions:
        - condition: template
          value_template: "{{ state_attr('media_player.andy_office_hub', 'app_name') in ['Spotify'] }}"
        sequence:
        - service: media_player.media_play_pause
          entity_id: media_player.andy_office_hub
      default:
      - service: media_player.volume_mute
        entity_id: media_player.andy_office_hub
        data:
          is_volume_muted: "{{ false if state_attr('media_player.andy_office_hub', 'is_volume_muted') else true }}"