automation:
- alias: Turn basement stairs light on/off with door
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.basement_door
    from: 'on'
    to: 'off'
    for: '00:00:15'
  action:
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'on' }}"
      - condition: state
        entity_id:
        - light.basement_stairs
        - input_boolean.dark_inside
        state: 'off'
      sequence:
      - service: light.turn_on
        entity_id: light.basement_stairs_lights
        data:
          kelvin: 4000
          brightness_pct: 100
    - conditions:
      - "{{ trigger.to_state.state == 'on' }}"
      - condition: state
        entity_id: input_boolean.dark_inside
        state: 'on'
      sequence:
      - service: light.turn_on
        entity_id: light.basement_stairs_bottom
        data:
          kelvin: 3000
          brightness_pct: 100
    - conditions:
      - "{{ trigger.to_state.state == 'off' }}"
      sequence:
      - service: light.turn_off
        entity_id: light.basement_stairs_lights


- alias: Turn basement bathroom night light on
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.dark_inside
    - group.basement_lights
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: input_text.alarm
    from: 'armed_away'
    to: 'disarmed'
  condition:
  - condition: state
    entity_id: 
    - group.basement_lights
    - input_boolean.dark_inside
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.basement_bath_night_light


- alias: Turn basement bathroom night light off
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - group.basement_lights
    - input_boolean.dark_inside
    from: 'on'
    to: 'off'
  action:
  - service: light.turn_off
    entity_id:
    - light.basement_bath_night_light
    - light.basement_hallway


- alias: Turn basement hall light on/off
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - light.office_lamps
    - light.basement_main
    to:
    - 'on'
    - 'off'
  - platform: state
    entity_id: input_boolean.dark_inside
    to: 'on'
  - platform: homeassistant
    event: start
  action:
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'on' or trigger.platform == 'homeassistant' }}"
      - condition: state
        entity_id: light.basement
        state: 'off'
      - condition: state
        entity_id: 
        - light.office_lamps
        - input_boolean.dark_inside
        state: 'on'
      sequence: &bsmt_hall_light_on
      - service: light.turn_on
        entity_id: light.basement_hallway
        data:
          brightness_pct: 20
    - conditions:
      - "{{ trigger.to_state.state == 'on' or trigger.platform == 'homeassistant' }}"
      - condition: state
        entity_id: light.basement
        state: 'on'
      sequence:
      - service: light.turn_off
        entity_id: light.basement_hallway
    - conditions:
      - "{{ trigger.to_state.state == 'off' or trigger.platform == 'homeassistant' }}"
      - condition: state
        entity_id: 
        - light.office_lamps
        - input_boolean.dark_inside
        state: 'on'
      sequence: *bsmt_hall_light_on
    - conditions:
      - "{{ trigger.to_state.state == 'off' or trigger.platform == 'homeassistant' }}"
      - condition: state
        entity_id: light.office_lamps
        state: 'off'
      - condition: state
        entity_id: light.basement_hallway
        state: 'on'
      sequence:
      - service: light.turn_off
        entity_id: light.basement_hallway


- alias: Sync basement color lights
  initial_state: true
  trigger:
  - platform: state
    entity_id: &basement_color_lights
    - light.bar_lights
    - light.basement_fireplace_lights
  condition:
  - condition: state
    entity_id: input_boolean.sync_basement_color_lights
    state: 'on'
  action:
  - delay: 1
  - choose:
    - conditions:
      - "{{ trigger.to_state.state == 'off' }}"
      sequence:
      - service: light.turn_off
        entity_id: *basement_color_lights
    default:
    - service: light.turn_on
      entity_id: *basement_color_lights
      data:
        brightness: "{{ state_attr(trigger.to_state.entity_id, 'brightness') }}"
        rgb_color: "{{ state_attr(trigger.to_state.entity_id, 'rgb_color') }}"
  - delay: 2


- alias: Enable/disable basement motion night light
  initial_state: true
  trigger:
  - platform: state
    entity_id: group.basement_lights
    to:
    - 'on'
    - 'off'
  condition:
  - condition: state
    entity_id: input_boolean.dark_inside
    state: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: 'cmnd/basement_night_light/rule1'
      payload: "{{ 1 if trigger.to_state.state == 'off' else 0 }}"
  - condition: template
    value_template: "{{ trigger.to_state.state == 'on' }}"
  - service: light.turn_off
    entity_id: light.basement_night_light


light:
- platform: mqtt
  name: Basement stairs
  state_topic: "stat/basement_stairs/POWER1"
  command_topic: "cmnd/basement_stairs/EVENT"
  availability_topic: "tele/basement_stairs/LWT"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"

- platform: group
  name: Basement stairs lights
  entities:
  - light.basement_stairs
  - light.basement_stairs_bottom

- platform: group
  name: Basement fireplace lights
  entities:
  - light.basement_fireplace_left
  - light.basement_fireplace_right

- platform: group
  name: Basement lamps
  entities:
  - light.basement_lamp_left
  - light.basement_lamp_right


group:
  basement_lights:
    name: Basement lights
    entities:
    - light.bar_lights
    - light.basement
    - light.basement_lamps
    - light.basement_stairs_lights
    - light.craft_room
    - light.craft_room_lamps
    - light.office
    - light.office_lamps
    - light.right_lamp_basement


input_boolean:
  sync_basement_color_lights: