automation:
- alias: Turn guest bedroom lamp off with fan light
  id: 'Ka0wi5oowoocee2ohcoh7v'
  initial_state: true
  trigger:
  - platform: state
    entity_id: light.guest_bedroom_fan
    from: 'off'
    to: 'on'
  action:
  - service: light.turn_off
    entity_id: light.guest_bedroom_lamp