automation:
- alias: Turn laundry room lights on with door/motion
  id: 'aith6dooCu3Eir5pufeina'
  initial_state: true
  trigger:
  - platform: state
    entity_id: 
    - binary_sensor.laundry_room_door_front
    - binary_sensor.laundry_room_door_back
    - binary_sensor.laundry_room_motion
    - binary_sensor.storage_motion
    from: 'off'
    to: 'on'
  action: &laundry_room_light_action
  - service: "light.turn_{{ trigger.to_state.state }}"
    data:
      entity_id: >
        {% set trigger = trigger.to_state.object_id.replace('laundry_room_', '').replace('_motion', '') %}
        {% if trigger in ['storage', 'door_back'] %}
          light.storage, light.laundry_room
        {% else %}
          light.laundry_room
        {% endif %}


- alias: Turn laundry room lights off with motion
  initial_state: true
  trigger:
  - platform: state
    entity_id: &laundry_motion
    - binary_sensor.laundry_room_motion
    - binary_sensor.storage_motion
    from: 'on'
    to: 'off'
    for: &laundry_motion_off_time '00:05:00'
  condition:
  - condition: state
    entity_id: input_boolean.laundry_motion
    state: 'on'
  - condition: state
    entity_id: *laundry_motion
    state: 'off'
  action: *laundry_room_light_action


- alias: Disable laundry room light motion control
  id: 'fei7aapo1xah1eixuThu2p'
  initial_state: true
  trigger:
  - platform: mqtt
    topic: 'stat/laundry_room_motion'
  action:
  - service: "input_boolean.turn_{{ trigger.payload }}"
    entity_id: input_boolean.laundry_motion


input_boolean:
  laundry_motion: