automation:
- alias: Turn office lamps on at sunset
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_boolean.dark_inside
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.xbox
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.office_lamps
    data:
      kelvin: 3000
      transition: 10
      brightness_pct: 100


- alias: Turn basement ejector closet light on/off
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.bathroom_ejector_closet_door
    to:
    - 'on'
    - 'off'
  action:
  - service: "light.turn_{{ trigger.to_state.state }}"
    entity_id: light.bathroom_ejector_closet


- alias: Switch lights when Xbox turned on
  initial_state: true
  trigger:
  - platform: state
    entity_id: binary_sensor.xbox
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id:
    - input_boolean.dark_inside
    - light.office
    state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.office
    data:
      transition: 5
  - service: light.turn_on
    entity_id: light.office_lamps
    data:
      transition: 3
  - service: media_player.turn_off
    entity_id: media_player.office_speaker


- alias: Transition office lights to warm white at sunset if on
  initial_state: true
  trigger:
  - platform: sun
    event: sunset
    # offset: '-00:31:00'
  condition:
  - condition: state
    entity_id: light.office
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.office_cans
    data:
      kelvin: 2000
      transition: 20


- alias: Turn SE office light on when closet door opened
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_closet_door_left
    - binary_sensor.office_closet_door_right
    to:
    - 'on'
    - 'off'
  condition:
  - condition: state
    entity_id: light.office
    state: 'off'
  action:
  - service: "light.turn_{{ trigger.to_state.state }}"
    entity_id: light.office_se


light:
- platform: group
  name: Office cans
  entities:
  - light.office_ne
  - light.office_nw
  - light.office_middle
  - light.office_se
  - light.office_sw

- platform: group
  name: Office lamps
  entities:
  - light.office_shelf_lamp
  - light.office_table_lamp


input_boolean:
  office:

binary_sensor:
- platform: mqtt
  name: Xbox
  state_topic: 'xbox/status'
  payload_on: 'Available'
  payload_off: 'Unavailable'

- platform: mqtt
  name: Office TV
  state_topic: 'tv2mqtt/tv'
  payload_on: 'on'
  payload_off: 'standby'
  availability_topic: 'tv2mqtt/status'
  payload_available: 'online'