- alias: Notify when shutting down
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.ups_battery
    below: 20
  condition:
  - condition: state
    entity_id: sensor.ups_status
    state: 'ONBATT'
  action:
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Server shutting down"
      message: "Power critical, shutting down. See you later :("


- alias: Notify when power lost
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.ups_status
    from: 'ONLINE'
    to: 'ONBATT'
  action:
  - service: input_text.set_value
    entity_id: input_text.time_power_lost
    data_template:
      value: "{{ as_timestamp(now()) }}"
  - service: notify.mobile_app_pixel_xl
    data:
      title: "Power lost"
      message: "Running on battery."


- alias: Notify when power restored
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: sensor.ups_status
    from: 'ONBATT'
    to: 'ONLINE'
  action:
  - service: input_text.set_value
    entity_id: input_text.time_power_restored
    data_template:
      value: "{{ as_timestamp(now()) }}"
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Power restored"
      message: "System was on battery for {{ states('sensor.power_outage_length') }}"