- alias: Notify lights on when away
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - light.dining_room
    - light.living_room
    - light.master_bedroom
    - light.game_room
    - light.laundry_room
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
    service: notify.mobile_app_pixel_xl
    data_template:
      title: Lights have been turned on
      message: "{{ trigger.to_state.name }} lights have been turned on."
      data:
        actions:
        - action: lights_off
          title: Turn off


- alias: Notify entrance light on when away
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: switch.light_switch_1
    from: 'off'
    to: 'on'
    for: '00:00:45'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
  action:
    service: notify.mobile_app_pixel_xl
    data:
      message: "Entrance light has been turned on."


- alias: Notify lights off when away
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.lights_interior
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: alarm_control_panel.abode
    state: armed_away
    for: '00:01:00'
  action:
    service: notify.mobile_app_pixel_xl
    data:
      message: "Lights have been turned off."


- alias: Notify when storm door opened
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.storm_door
    from: 'off'
    to: 'on'
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'armed_away'] }}"
  action:
    service: notify.mobile_app_pixel_xl
    data:
      message: "Storm door has been opened!"


- alias: Notify when storm door closed
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.storm_door
    from: 'on'
    to: 'off'
  condition:
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'armed_away'] }}"
  action:
    service: notify.mobile_app_pixel_xl
    data:
      message: "Storm door has been closed."