automation:
- alias: Notify when sensor unresponsive
  initial_state: 'on'
  trigger:
  - platform: template
    value_template: >
      {% set front = state_attr('binary_sensor.front_door', 'no_response') %}
      {% set balcony = state_attr('binary_sensor.balcony_door', 'no_response') %}
      {% set drawer = state_attr('binary_sensor.drawer', 'no_response') %}
      {% set keypad = state_attr('binary_sensor.keypad', 'no_response') %}
      {% set camera = state_attr('camera.motion_camera', 'no_response') %}
      {{ front == true or balcony == true or drawer == true or keypad == true or camera == true }}
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "Sensor unresponsive"
      message: "{{ trigger.to_state.name }} sensor is not responding"


sensor:
- platform: template
  sensors:
    alarm_mode:
      friendly_name: "Alarm mode"
      value_template: >
        {% if is_state('alarm_control_panel.abode', 'armed_home') %}
          Armed home
        {% elif is_state('alarm_control_panel.abode', 'armed_away') %}
          Armed away
        {% elif is_state('alarm_control_panel.abode', 'disarmed') %}
          Disarmed
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% if is_state('alarm_control_panel.abode', 'armed_home') %}
          mdi:home-lock
        {% elif is_state('alarm_control_panel.abode', 'armed_away') %}
          mdi:lock
        {% elif is_state('alarm_control_panel.abode', 'disarmed') %}
          mdi:lock-open-outline
        {% else %}
          mdi:lock-question
        {% endif %}
    
    abode_door_1_battery:
      friendly_name: "Front door"
      value_template: >
        {% set battery = state_attr('binary_sensor.front_door', 'battery_low') %}
        {% if battery == false %}
          OK
        {% elif battery == true %}
          Low
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% set battery = state_attr('binary_sensor.front_door', 'battery_low') %}
        {% if battery == false %}
          mdi:battery
        {% elif battery == true %}
          mdi:battery-20
        {% else %}
          mdi:battery-unknown
        {% endif %}
    
    abode_door_2_battery:
      friendly_name: "Balcony door"
      value_template: >
        {% set battery = state_attr('binary_sensor.balcony_door', 'battery_low') %}
        {% if battery == false %}
          OK
        {% elif battery == true %}
          Low
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% set battery = state_attr('binary_sensor.balcony_door', 'battery_low') %}
        {% if battery == false %}
          mdi:battery
        {% elif battery == true %}
          mdi:battery-20
        {% else %}
          mdi:battery-unknown
        {% endif %}
    
    abode_door_3_battery:
      friendly_name: "Drawer"
      value_template: >
        {% set battery = state_attr('binary_sensor.drawer', 'battery_low') %}
        {% if battery == false %}
          OK
        {% elif battery == true %}
          Low
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% set battery = state_attr('binary_sensor.drawer', 'battery_low') %}
        {% if battery == false %}
          mdi:battery
        {% elif battery == true %}
          mdi:battery-20
        {% else %}
          mdi:battery-unknown
        {% endif %}
    
    abode_motion_1_battery:
      friendly_name: "Motion camera"
      value_template: >
        {% set battery = state_attr('camera.motion_camera', 'battery_low') %}
        {% if battery == false %}
          OK
        {% elif battery == true %}
          Low
        {% else %}
          Unknown
        {% endif %}
      icon_template: >
        {% set battery = state_attr('camera.motion_camera', 'battery_low') %}
        {% if battery == false %}
          mdi:battery
        {% elif battery == true %}
          mdi:battery-20
        {% else %}
          mdi:battery-unknown
        {% endif %}

- platform: rest
  resource: !secret abode_rest
  name: Abode
  value_template: "{{ value_json['updates']['em_ver'] }}"
  scan_interval: 43200


script:
  alarm_arm_home:
    alias: Arm alarm in home mode
    sequence:
    - service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.abode