automation:
- alias: Notify when washer/dryer done
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: 
    - input_boolean.washer
    - input_boolean.dryer
    from: 'on'
    to: 'off'
  condition:
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  action:
  - service: notify.mobile_app_pixel_xl
    data_template:
      title: "{{ trigger.to_state.name }} cycle done"
      message: "{{ 'Move clothes to the dryer.' if trigger.to_state.name == 'Washer' else 'Put your clothes away.' }}"


- alias: Poll power strip
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    seconds: '/15'
  condition:
  - condition: state
    entity_id: binary_sensor.laundry_room_door
    state: 'off'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: template
    value_template: "{{ states('alarm_control_panel.abode') in ['armed_home', 'disarmed'] }}"
  action:
  - service: zwave.refresh_entity
    data:
      entity_id: sensor.power_strip_outlet_1_power
  - service: zwave.refresh_entity
    data:
      entity_id: sensor.power_strip_outlet_2_power


- alias: Keep power strip happy
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    hours: "/4"
  condition:
  - condition: state
    entity_id: binary_sensor.laundry_room_door
    state: 'on'
  action:
  - service: zwave.refresh_entity
    data:
      entity_id: sensor.power_strip_outlet_1_power
  - service: zwave.refresh_entity
    data:
      entity_id: sensor.power_strip_outlet_2_power


- alias: Record washer on and off
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_1_power
    above: 550
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_1_power
    below: 1.5
  action:
  - service_template: "{{ 'input_boolean.turn_on' if states(trigger.to_state.entity_id) | float > 550 else 'input_boolean.turn_off' }}"
    entity_id: input_boolean.washer


- alias: Record dryer on and off
  initial_state: 'on'
  trigger:
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_2_power
    above: 250
    for: '00:05:00'
  - platform: numeric_state
    entity_id: sensor.power_strip_outlet_2_power
    below: 50
  action:
  - service_template: "{{ 'input_boolean.turn_on' if states(trigger.to_state.entity_id) | float > 250 else 'input_boolean.turn_off' }}"
    entity_id: input_boolean.dryer


input_boolean:
  washer:
    name: Washer
  dryer:
    name: Dryer